import type { CitySlug } from "./taiwan-cities";

export type TaiwanDistrict = {
  zh: string;
  slug: string;
};

/**
 * Official township-level names from the Ministry of the Interior NLSC
 * TOWN_MOI_1120317 boundary dataset. Slugs are stable public anchors.
 */
export const TAIWAN_DISTRICTS: Readonly<
  Record<CitySlug, ReadonlyArray<TaiwanDistrict>>
> = {
  taipei: [
    { zh: "士林區", slug: "shilin" },
    { zh: "大同區", slug: "taipei-datong" },
    { zh: "大安區", slug: "taipei-da-an" },
    { zh: "中山區", slug: "taipei-zhongshan" },
    { zh: "中正區", slug: "taipei-zhongzheng" },
    { zh: "內湖區", slug: "neihu" },
    { zh: "文山區", slug: "wenshan" },
    { zh: "北投區", slug: "beitou" },
    { zh: "松山區", slug: "songshan" },
    { zh: "信義區", slug: "taipei-xinyi" },
    { zh: "南港區", slug: "nangang" },
    { zh: "萬華區", slug: "wanhua" },
  ],
  new_taipei: [
    { zh: "八里區", slug: "bali" },
    { zh: "三芝區", slug: "sanzhi" },
    { zh: "三重區", slug: "sanchong" },
    { zh: "三峽區", slug: "sanxia" },
    { zh: "土城區", slug: "tucheng" },
    { zh: "中和區", slug: "zhonghe" },
    { zh: "五股區", slug: "wugu" },
    { zh: "平溪區", slug: "pingxi" },
    { zh: "永和區", slug: "yonghe" },
    { zh: "石門區", slug: "shimen" },
    { zh: "石碇區", slug: "shiding" },
    { zh: "汐止區", slug: "xizhi" },
    { zh: "坪林區", slug: "pinglin" },
    { zh: "板橋區", slug: "banqiao" },
    { zh: "林口區", slug: "linkou" },
    { zh: "金山區", slug: "jinshan" },
    { zh: "泰山區", slug: "taishan" },
    { zh: "烏來區", slug: "wulai" },
    { zh: "貢寮區", slug: "gongliao" },
    { zh: "淡水區", slug: "tamsui" },
    { zh: "深坑區", slug: "shenkeng" },
    { zh: "新店區", slug: "xindian" },
    { zh: "新莊區", slug: "xinzhuang" },
    { zh: "瑞芳區", slug: "ruifang" },
    { zh: "萬里區", slug: "wanli" },
    { zh: "樹林區", slug: "shulin" },
    { zh: "雙溪區", slug: "shuangxi" },
    { zh: "蘆洲區", slug: "luzhou" },
    { zh: "鶯歌區", slug: "yingge" },
  ],
  taoyuan: [
    { zh: "八德區", slug: "bade" },
    { zh: "大園區", slug: "dayuan" },
    { zh: "大溪區", slug: "daxi" },
    { zh: "中壢區", slug: "zhongli" },
    { zh: "平鎮區", slug: "pingzhen" },
    { zh: "桃園區", slug: "taoyuan-taoyuan" },
    { zh: "復興區", slug: "taoyuan-fuxing" },
    { zh: "新屋區", slug: "xinwu" },
    { zh: "楊梅區", slug: "yangmei" },
    { zh: "龍潭區", slug: "longtan" },
    { zh: "龜山區", slug: "guishan" },
    { zh: "蘆竹區", slug: "taoyuan-luzhu" },
    { zh: "觀音區", slug: "guanyin" },
  ],
  taichung: [
    { zh: "大甲區", slug: "dajia" },
    { zh: "大安區", slug: "taichung-da-an" },
    { zh: "大肚區", slug: "dadu" },
    { zh: "大里區", slug: "dali" },
    { zh: "大雅區", slug: "daya" },
    { zh: "中區", slug: "central" },
    { zh: "太平區", slug: "taiping" },
    { zh: "北屯區", slug: "beitun" },
    { zh: "北區", slug: "taichung-north" },
    { zh: "外埔區", slug: "waipu" },
    { zh: "石岡區", slug: "shigang" },
    { zh: "后里區", slug: "houli" },
    { zh: "西屯區", slug: "xitun" },
    { zh: "西區", slug: "taichung-west" },
    { zh: "沙鹿區", slug: "shalu" },
    { zh: "和平區", slug: "heping" },
    { zh: "東區", slug: "taichung-east" },
    { zh: "東勢區", slug: "taichung-dongshi" },
    { zh: "南屯區", slug: "nantun" },
    { zh: "南區", slug: "taichung-south" },
    { zh: "烏日區", slug: "wuri" },
    { zh: "神岡區", slug: "taichung-shengang" },
    { zh: "梧棲區", slug: "wuqi" },
    { zh: "清水區", slug: "qingshui" },
    { zh: "新社區", slug: "xinshe" },
    { zh: "潭子區", slug: "tanzi" },
    { zh: "龍井區", slug: "longjing" },
    { zh: "豐原區", slug: "fengyuan" },
    { zh: "霧峰區", slug: "taichung-wufeng" },
  ],
  tainan: [
    { zh: "七股區", slug: "qigu" },
    { zh: "下營區", slug: "xiaying" },
    { zh: "大內區", slug: "danei" },
    { zh: "山上區", slug: "shanshang" },
    { zh: "中西區", slug: "west-central" },
    { zh: "仁德區", slug: "rende" },
    { zh: "六甲區", slug: "liujia" },
    { zh: "北門區", slug: "beimen" },
    { zh: "北區", slug: "tainan-north" },
    { zh: "左鎮區", slug: "zuozhen" },
    { zh: "永康區", slug: "yongkang" },
    { zh: "玉井區", slug: "yujing" },
    { zh: "白河區", slug: "baihe" },
    { zh: "安平區", slug: "anping" },
    { zh: "安定區", slug: "anding" },
    { zh: "安南區", slug: "annan" },
    { zh: "西港區", slug: "xigang" },
    { zh: "佳里區", slug: "jiali" },
    { zh: "官田區", slug: "guantian" },
    { zh: "東山區", slug: "tainan-dongshan" },
    { zh: "東區", slug: "tainan-east" },
    { zh: "南化區", slug: "nanhua" },
    { zh: "南區", slug: "tainan-south" },
    { zh: "後壁區", slug: "houbi" },
    { zh: "柳營區", slug: "liuying" },
    { zh: "將軍區", slug: "jiangjun" },
    { zh: "麻豆區", slug: "madou" },
    { zh: "善化區", slug: "shanhua" },
    { zh: "新化區", slug: "xinhua" },
    { zh: "新市區", slug: "xinshi" },
    { zh: "新營區", slug: "xinying" },
    { zh: "楠西區", slug: "nanxi" },
    { zh: "學甲區", slug: "xuejia" },
    { zh: "龍崎區", slug: "longqi" },
    { zh: "歸仁區", slug: "guiren" },
    { zh: "關廟區", slug: "guanmiao" },
    { zh: "鹽水區", slug: "yanshui" },
  ],
  kaohsiung: [
    { zh: "三民區", slug: "sanmin" },
    { zh: "大社區", slug: "dashe" },
    { zh: "大寮區", slug: "daliao" },
    { zh: "大樹區", slug: "dashu" },
    { zh: "小港區", slug: "xiaogang" },
    { zh: "仁武區", slug: "renwu" },
    { zh: "內門區", slug: "neimen" },
    { zh: "六龜區", slug: "liugui" },
    { zh: "左營區", slug: "zuoying" },
    { zh: "永安區", slug: "yong-an" },
    { zh: "田寮區", slug: "tianliao" },
    { zh: "甲仙區", slug: "jiaxian" },
    { zh: "杉林區", slug: "shanlin" },
    { zh: "那瑪夏區", slug: "namaxia" },
    { zh: "岡山區", slug: "gangshan" },
    { zh: "林園區", slug: "linyuan" },
    { zh: "阿蓮區", slug: "alian" },
    { zh: "前金區", slug: "qianjin" },
    { zh: "前鎮區", slug: "qianzhen" },
    { zh: "美濃區", slug: "meinong" },
    { zh: "苓雅區", slug: "lingya" },
    { zh: "茂林區", slug: "maolin" },
    { zh: "茄萣區", slug: "qieding" },
    { zh: "桃源區", slug: "kaohsiung-taoyuan" },
    { zh: "梓官區", slug: "ziguan" },
    { zh: "鳥松區", slug: "niaosong" },
    { zh: "湖內區", slug: "hunei" },
    { zh: "新興區", slug: "xinxing" },
    { zh: "楠梓區", slug: "nanzi" },
    { zh: "路竹區", slug: "kaohsiung-luzhu" },
    { zh: "鼓山區", slug: "gushan" },
    { zh: "旗山區", slug: "qishan" },
    { zh: "旗津區", slug: "qijin" },
    { zh: "鳳山區", slug: "fengshan" },
    { zh: "橋頭區", slug: "qiaotou" },
    { zh: "燕巢區", slug: "yanchao" },
    { zh: "彌陀區", slug: "mituo" },
    { zh: "鹽埕區", slug: "yancheng" },
  ],
  keelung: [
    { zh: "七堵區", slug: "qidu" },
    { zh: "中山區", slug: "keelung-zhongshan" },
    { zh: "中正區", slug: "keelung-zhongzheng" },
    { zh: "仁愛區", slug: "keelung-ren-ai" },
    { zh: "安樂區", slug: "anle" },
    { zh: "信義區", slug: "keelung-xinyi" },
    { zh: "暖暖區", slug: "nuannuan" },
  ],
  hsinchu_city: [
    { zh: "北區", slug: "hsinchu-city-north" },
    { zh: "東區", slug: "hsinchu-city-east" },
    { zh: "香山區", slug: "xiangshan" },
  ],
  chiayi_city: [
    { zh: "西區", slug: "chiayi-city-west" },
    { zh: "東區", slug: "chiayi-city-east" },
  ],
  hsinchu_county: [
    { zh: "五峰鄉", slug: "hsinchu-county-wufeng" },
    { zh: "北埔鄉", slug: "beipu" },
    { zh: "尖石鄉", slug: "jianshi" },
    { zh: "竹北市", slug: "zhubei" },
    { zh: "竹東鎮", slug: "zhudong" },
    { zh: "芎林鄉", slug: "qionglin" },
    { zh: "峨眉鄉", slug: "emei" },
    { zh: "湖口鄉", slug: "hukou" },
    { zh: "新埔鎮", slug: "xinpu" },
    { zh: "新豐鄉", slug: "xinfeng" },
    { zh: "橫山鄉", slug: "hengshan" },
    { zh: "關西鎮", slug: "guanxi" },
    { zh: "寶山鄉", slug: "baoshan" },
  ],
  miaoli: [
    { zh: "三義鄉", slug: "sanyi" },
    { zh: "三灣鄉", slug: "sanwan" },
    { zh: "大湖鄉", slug: "dahu" },
    { zh: "公館鄉", slug: "gongguan" },
    { zh: "竹南鎮", slug: "zhunan" },
    { zh: "西湖鄉", slug: "miaoli-xihu" },
    { zh: "卓蘭鎮", slug: "zhuolan" },
    { zh: "南庄鄉", slug: "nanzhuang" },
    { zh: "後龍鎮", slug: "houlong" },
    { zh: "苑裡鎮", slug: "yuanli" },
    { zh: "苗栗市", slug: "miaoli" },
    { zh: "泰安鄉", slug: "tai-an" },
    { zh: "通霄鎮", slug: "tongxiao" },
    { zh: "造橋鄉", slug: "zaoqiao" },
    { zh: "獅潭鄉", slug: "shitan" },
    { zh: "銅鑼鄉", slug: "tongluo" },
    { zh: "頭份市", slug: "toufen" },
    { zh: "頭屋鄉", slug: "touwu" },
  ],
  changhua: [
    { zh: "二水鄉", slug: "ershui" },
    { zh: "二林鎮", slug: "erlin" },
    { zh: "大村鄉", slug: "dacun" },
    { zh: "大城鄉", slug: "dacheng" },
    { zh: "北斗鎮", slug: "beidou" },
    { zh: "永靖鄉", slug: "yongjing" },
    { zh: "田中鎮", slug: "tianzhong" },
    { zh: "田尾鄉", slug: "tianwei" },
    { zh: "竹塘鄉", slug: "zhutang" },
    { zh: "伸港鄉", slug: "changhua-shengang" },
    { zh: "秀水鄉", slug: "xiushui" },
    { zh: "和美鎮", slug: "hemei" },
    { zh: "社頭鄉", slug: "shetou" },
    { zh: "芬園鄉", slug: "fenyuan" },
    { zh: "花壇鄉", slug: "huatan" },
    { zh: "芳苑鄉", slug: "fangyuan" },
    { zh: "員林市", slug: "yuanlin" },
    { zh: "埔心鄉", slug: "puxin" },
    { zh: "埔鹽鄉", slug: "puyan" },
    { zh: "埤頭鄉", slug: "pitou" },
    { zh: "鹿港鎮", slug: "lukang" },
    { zh: "溪州鄉", slug: "xizhou" },
    { zh: "溪湖鎮", slug: "changhua-xihu" },
    { zh: "彰化市", slug: "changhua" },
    { zh: "福興鄉", slug: "changhua-fuxing" },
    { zh: "線西鄉", slug: "xianxi" },
  ],
  nantou: [
    { zh: "中寮鄉", slug: "zhongliao" },
    { zh: "仁愛鄉", slug: "nantou-ren-ai" },
    { zh: "水里鄉", slug: "shuili" },
    { zh: "名間鄉", slug: "mingjian" },
    { zh: "竹山鎮", slug: "zhushan" },
    { zh: "信義鄉", slug: "nantou-xinyi" },
    { zh: "南投市", slug: "nantou" },
    { zh: "埔里鎮", slug: "puli" },
    { zh: "草屯鎮", slug: "caotun" },
    { zh: "國姓鄉", slug: "guoxing" },
    { zh: "魚池鄉", slug: "yuchi" },
    { zh: "鹿谷鄉", slug: "lugu" },
    { zh: "集集鎮", slug: "jiji" },
  ],
  yunlin: [
    { zh: "二崙鄉", slug: "erlun" },
    { zh: "口湖鄉", slug: "kouhu" },
    { zh: "土庫鎮", slug: "tuku" },
    { zh: "大埤鄉", slug: "dabi" },
    { zh: "元長鄉", slug: "yuanchang" },
    { zh: "斗六市", slug: "douliu" },
    { zh: "斗南鎮", slug: "dounan" },
    { zh: "水林鄉", slug: "shuilin" },
    { zh: "北港鎮", slug: "beigang" },
    { zh: "古坑鄉", slug: "gukeng" },
    { zh: "四湖鄉", slug: "sihu" },
    { zh: "西螺鎮", slug: "xiluo" },
    { zh: "東勢鄉", slug: "yunlin-dongshi" },
    { zh: "林內鄉", slug: "linnei" },
    { zh: "虎尾鎮", slug: "huwei" },
    { zh: "崙背鄉", slug: "lunbei" },
    { zh: "麥寮鄉", slug: "mailiao" },
    { zh: "莿桐鄉", slug: "citong" },
    { zh: "臺西鄉", slug: "taixi" },
    { zh: "褒忠鄉", slug: "baozhong" },
  ],
  chiayi_county: [
    { zh: "大林鎮", slug: "dalin" },
    { zh: "大埔鄉", slug: "dapu" },
    { zh: "中埔鄉", slug: "zhongpu" },
    { zh: "六腳鄉", slug: "liujiao" },
    { zh: "太保市", slug: "taibao" },
    { zh: "水上鄉", slug: "shuishang" },
    { zh: "布袋鎮", slug: "budai" },
    { zh: "民雄鄉", slug: "minxiong" },
    { zh: "朴子市", slug: "puzi" },
    { zh: "竹崎鄉", slug: "zhuqi" },
    { zh: "東石鄉", slug: "chiayi-county-dongshi" },
    { zh: "阿里山鄉", slug: "alishan" },
    { zh: "梅山鄉", slug: "meishan" },
    { zh: "鹿草鄉", slug: "lucao" },
    { zh: "番路鄉", slug: "fanlu" },
    { zh: "新港鄉", slug: "xingang" },
    { zh: "溪口鄉", slug: "xikou" },
    { zh: "義竹鄉", slug: "yizhu" },
  ],
  pingtung: [
    { zh: "九如鄉", slug: "jiuru" },
    { zh: "三地門鄉", slug: "sandimen" },
    { zh: "內埔鄉", slug: "neipu" },
    { zh: "竹田鄉", slug: "zhutian" },
    { zh: "牡丹鄉", slug: "mudan" },
    { zh: "車城鄉", slug: "checheng" },
    { zh: "里港鄉", slug: "ligang" },
    { zh: "佳冬鄉", slug: "jiadong" },
    { zh: "來義鄉", slug: "laiyi" },
    { zh: "東港鎮", slug: "donggang" },
    { zh: "枋山鄉", slug: "fangshan" },
    { zh: "枋寮鄉", slug: "fangliao" },
    { zh: "林邊鄉", slug: "linbian" },
    { zh: "長治鄉", slug: "changzhi" },
    { zh: "南州鄉", slug: "nanzhou" },
    { zh: "屏東市", slug: "pingtung" },
    { zh: "恆春鎮", slug: "hengchun" },
    { zh: "春日鄉", slug: "chunri" },
    { zh: "崁頂鄉", slug: "kanding" },
    { zh: "泰武鄉", slug: "taiwu" },
    { zh: "琉球鄉", slug: "liuqiu" },
    { zh: "高樹鄉", slug: "gaoshu" },
    { zh: "新埤鄉", slug: "xinpi" },
    { zh: "新園鄉", slug: "xinyuan" },
    { zh: "獅子鄉", slug: "shizi" },
    { zh: "萬丹鄉", slug: "wandan" },
    { zh: "萬巒鄉", slug: "wanluan" },
    { zh: "滿州鄉", slug: "manzhou" },
    { zh: "瑪家鄉", slug: "majia" },
    { zh: "潮州鎮", slug: "chaozhou" },
    { zh: "霧臺鄉", slug: "wutai" },
    { zh: "麟洛鄉", slug: "linluo" },
    { zh: "鹽埔鄉", slug: "yanpu" },
  ],
  yilan: [
    { zh: "三星鄉", slug: "sanxing" },
    { zh: "大同鄉", slug: "yilan-datong" },
    { zh: "五結鄉", slug: "wujie" },
    { zh: "冬山鄉", slug: "yilan-dongshan" },
    { zh: "壯圍鄉", slug: "zhuangwei" },
    { zh: "宜蘭市", slug: "yilan" },
    { zh: "南澳鄉", slug: "nan-ao" },
    { zh: "員山鄉", slug: "yuanshan" },
    { zh: "頭城鎮", slug: "toucheng" },
    { zh: "礁溪鄉", slug: "jiaoxi" },
    { zh: "羅東鎮", slug: "luodong" },
    { zh: "蘇澳鎮", slug: "su-ao" },
  ],
  hualien: [
    { zh: "玉里鎮", slug: "yuli" },
    { zh: "光復鄉", slug: "guangfu" },
    { zh: "吉安鄉", slug: "ji-an" },
    { zh: "秀林鄉", slug: "xiulin" },
    { zh: "卓溪鄉", slug: "zhuoxi" },
    { zh: "花蓮市", slug: "hualien" },
    { zh: "富里鄉", slug: "fuli" },
    { zh: "新城鄉", slug: "xincheng" },
    { zh: "瑞穗鄉", slug: "ruisui" },
    { zh: "萬榮鄉", slug: "wanrong" },
    { zh: "壽豐鄉", slug: "shoufeng" },
    { zh: "鳳林鎮", slug: "fenglin" },
    { zh: "豐濱鄉", slug: "fengbin" },
  ],
  taitung: [
    { zh: "大武鄉", slug: "dawu" },
    { zh: "太麻里鄉", slug: "taimali" },
    { zh: "成功鎮", slug: "chenggong" },
    { zh: "池上鄉", slug: "chishang" },
    { zh: "卑南鄉", slug: "beinan" },
    { zh: "延平鄉", slug: "yanping" },
    { zh: "東河鄉", slug: "donghe" },
    { zh: "金峰鄉", slug: "jinfeng" },
    { zh: "長濱鄉", slug: "changbin" },
    { zh: "海端鄉", slug: "haiduan" },
    { zh: "鹿野鄉", slug: "luye" },
    { zh: "達仁鄉", slug: "daren" },
    { zh: "綠島鄉", slug: "ludao" },
    { zh: "臺東市", slug: "taitung" },
    { zh: "關山鎮", slug: "guanshan" },
    { zh: "蘭嶼鄉", slug: "lanyu" },
  ],
  penghu: [
    { zh: "七美鄉", slug: "qimei" },
    { zh: "白沙鄉", slug: "baisha" },
    { zh: "西嶼鄉", slug: "xiyu" },
    { zh: "馬公市", slug: "magong" },
    { zh: "望安鄉", slug: "wang-an" },
    { zh: "湖西鄉", slug: "huxi" },
  ],
  kinmen: [
    { zh: "金沙鎮", slug: "jinsha" },
    { zh: "金城鎮", slug: "jincheng" },
    { zh: "金湖鎮", slug: "jinhu" },
    { zh: "金寧鄉", slug: "jinning" },
    { zh: "烈嶼鄉", slug: "lieyu" },
    { zh: "烏坵鄉", slug: "wuqiu" },
  ],
  lienchiang: [
    { zh: "北竿鄉", slug: "beigan" },
    { zh: "東引鄉", slug: "dongyin" },
    { zh: "南竿鄉", slug: "nangan" },
    { zh: "莒光鄉", slug: "juguang" },
  ],
};
