const PROVIDERS = {
  serper: ["search", "images", "maps"],
  openai: ["chat_completions"],
  deepseek: ["chat_completions", "balance"],
  resend: ["send_email"],
  upstash: ["get_database", "get_stats"],
  sentry: ["get_error_events"],
  cloudflare: ["origin_probe"],
  turnstile: ["siteverify"],
  slack: ["post_slack_alert"],
  posthog: ["run_query"],
  "mit-registry": [
    "lookup_cert_number",
    "lookup_cert_numbers",
    "sync_registry",
  ],
  playwright: ["fetch_rendered"],
  scraper: ["scrape_url"],
  http: [
    "fetch_html",
    "fetch_html_with_metadata",
    "fetch_xml",
    "download_and_store_images",
  ],
  brands: [
    "adminRemoveChannel",
    "cleanupAdminBrandReviewImages",
    "completeBrandClaim",
    "confirmChannel",
    "createEvidence",
    "createReport",
    "declareMit",
    "deleteBrand",
    "mergeFeatureRequests",
    "publishDraft",
    "reviewCorrection",
    "reviewEvidence",
    "saveAdminBrandReview",
    "saveBrand",
    "saveDraft",
    "setBrandLike",
    "setFeatureRequestStatus",
    "setFeatureRequestVote",
    "setOwnerChannelStatus",
    "stageAdminBrandReviewImage",
    "stripDeclaration",
    "submitChannel",
    "submitCorrection",
    "submitFeatureRequest",
    "syncBrandImages",
    "unsaveBrand",
    "updateBrand",
    "updateProfile",
    "updateProfileAdmin",
    "updateReportStatus",
    "upsertBrandFaqEntries",
    "upsertEnrichedChannels",
    "verifyMitByCert",
    "withdrawDeclaration",
  ],
  cache: [
    "getCachedExploreBrandPool",
    "getCachedMetrics",
    "getCachedRecentBrandCount",
  ],
  claims: [
    "approveClaimRequest",
    "createClaimRequest",
    "processClaimProofCleanup",
    "rejectClaimRequest",
    "revokeOwnership",
    "verifyClaimEmailProof",
  ],
  curation: [
    "cancelCurationJob",
    "claimCurationDispatchWork",
    "claimCurationJob",
    "claimNextCurationJob",
    "dispatchCurationJob",
    "enqueueAdminCurationJob",
    "enqueueAutomaticRetry",
    "enqueueCurationResume",
    "enqueueManualRerun",
    "enqueueScheduledSubmissionJob",
    "ensureAutomaticRetries",
    "finalizeCurationJob",
    "heartbeatCurationJob",
    "markCurationJobDispatched",
    "recordCurationDispatchFailure",
    "recoverStaleJobs",
    "reportCircuitBreakerTrip",
    "reportJobFailure",
    "reportProviderFailures",
    "reportWorkerFailure",
    "runJob",
    "runScheduledCuration",
    "updateCurationJobTarget",
  ],
  email: [
    "adminUnsubscribeNewsletterSubscriber",
    "confirmSubscriber",
    "createEmailPreferences",
    "createSubscriber",
    "enrollInMarketingEmails",
    "evaluateDrips",
    "recordEmailSend",
    "requestNewsletterSubscription",
    "resendNewsletterConfirmation",
    "setLifecycleEmailPreference",
    "unsubscribeByToken",
    "unsubscribeNewsletter",
    "unsubscribeNewsletterByEmail",
  ],
  enrich: [
    "arbitrateBrandNames",
    "arbitrateSiteIdentity",
    "classifyProductTypeBatch",
    "detectBrandsBatch",
    "persistEnrichmentResults",
    "persistSubmissionEnrichmentResults",
    "rewriteBrandDescription",
    "runBrandImagePhase",
    "runChannelsPhase",
    "runClassifyImagesPhase",
    "runCleanPhase",
    "runDescriptionsPhase",
    "runDetectPhase",
    "runDiscoverPhase",
    "runEnrich",
    "runImageSearchPhase",
    "runLinksPhase",
    "runNamesPhase",
    "runReputationPhase",
    "runReputationResearch",
    "runSiteIdentityPhase",
    "runStandaloneClassification",
  ],
  images: [
    "deleteBrandImages",
    "deleteStoredImagePaths",
    "downloadAndStoreImages",
    "insertBrandImage",
    "loadVisionImage",
    "purgeExpiredClassifierJunk",
    "rejectBrandImages",
    "releaseBrandImageUrls",
    "syncHeroDenormalized",
    "uploadImageEvalAsset",
    "uploadPrivateFile",
    "uploadPrivateImage",
    "uploadPublicImage",
  ],
  submissions: [
    "applyBrandRefresh",
    "approveSubmission",
    "cleanupSubmissionDraftImages",
    "createSubmission",
    "dropNeedsDataSubmissions",
    "executeCommunitySubmissions",
    "markFlagsReviewed",
    "rejectSubmission",
    "reopenSubmission",
    "requestBrandRefresh",
    "requestBrandRefreshesBySlugs",
    "saveModerationFlags",
    "saveSubmissionReview",
    "stageSubmissionReviewImage",
    "submitBrandForReview",
    "updateModerationFlagStatus",
  ],
} as const;

export type ProviderRegistry = typeof PROVIDERS;
export type AuditProvider = keyof ProviderRegistry;

export function assertRegistered(provider: string, operation: string): void {
  if (!(provider in PROVIDERS)) {
    throw new Error(`Unknown audit provider: ${provider}`);
  }

  const operations = PROVIDERS[provider as AuditProvider] as readonly string[];
  if (!operations.includes(operation)) {
    throw new Error(`Unknown audit operation: ${provider}.${operation}`);
  }
}
