import { describe, expect, it } from "vitest";

import type { AuditCallContext } from "@/lib/audit";
import {
  BANNED_TERMS,
  detectBannedTerms,
  fixBannedTerms,
  reportBannedTerms,
} from "@/lib/i18n/banned-terms";

describe("detectBannedTerms", () => {
  it("detects a banned term and reports term, replacement, and offset", () => {
    const hits = detectBannedTerms("這個視頻很好");

    expect(hits).toHaveLength(1);
    expect(hits[0]).toMatchObject({
      term: "視頻",
      replacement: "影片",
      offset: 2,
    });
  });

  it("never mutates the input string", () => {
    const input = "這個視頻很好";
    const hits = detectBannedTerms(input);

    expect(input).toBe("這個視頻很好");
    expect(hits).toHaveLength(1);
  });

  it("does not flag 算法 inside 演算法", () => {
    expect(detectBannedTerms("這個演算法")).toHaveLength(0);
  });

  it("flags bare 算法", () => {
    const hits = detectBannedTerms("這個算法");

    expect(hits).toHaveLength(1);
    expect(hits[0]?.term).toBe("算法");
  });

  it("matches the one Latin-script term in any casing", () => {
    for (const spelling of ["yyds", "Yyds", "YYDS"]) {
      const hits = detectBannedTerms(`這首歌${spelling}`);

      expect(hits, spelling).toHaveLength(1);
      // The canonical entry, whatever the input casing: the audit trail records
      // the term as the list spells it, and the replacement is not case-derived.
      expect(hits[0], spelling).toMatchObject({
        term: "YYDS",
        replacement: "太神了",
        offset: 3,
      });
    }
  });

  it("does not flag the excluded terms", () => {
    const excluded = [
      "點擊",
      "支持",
      "保存",
      "項目",
      "文件",
      "社區",
      "數據",
      "打造",
      "通過",
      "水平",
      "落地",
      "程序",
      "土豆",
      "干貨",
      "乾貨",
      "優化",
      "智能",
      "智能體",
      "人工智能",
    ];

    for (const term of excluded) {
      expect(detectBannedTerms(term), term).toEqual([]);
    }
  });
});

describe("fixBannedTerms", () => {
  it("swaps every hit", () => {
    const result = fixBannedTerms("這個視頻很好");

    expect(result.text).toBe("這個影片很好");
    expect(result.substitutions).toHaveLength(1);
    expect(result.substitutions[0]?.term).toBe("視頻");
  });

  it("returns the input unchanged when there is nothing to fix", () => {
    const result = fixBannedTerms("這個演算法很好");

    expect(result.text).toBe("這個演算法很好");
    expect(result.substitutions).toEqual([]);
  });

  it("substitutes the canonical replacement for a lowercase Latin match", () => {
    const result = fixBannedTerms("這首歌yyds");

    expect(result.text).toBe("這首歌太神了");
    expect(result.substitutions).toHaveLength(1);
  });
});

describe("BANNED_TERMS", () => {
  it("has unique terms", () => {
    const terms = BANNED_TERMS.map((entry) => entry.term);
    expect(new Set(terms).size).toBe(terms.length);
  });

  /**
   * The list was generated by keeping the FIRST ／-separated variant of each
   * source cell, which silently collapsed 「正妹／帥哥」 onto both 小姐姐 and
   * 小哥哥 — rewriting a male referent into a female one, and recording it in
   * the audit trail as a successful fix.
   *
   * A shared replacement is fine in general (several terms legitimately map to
   * 流程). It is only ever wrong when the replacement carries gender, because
   * then one of the two terms must be the wrong one.
   */
  it("maps each gendered term to its own gendered replacement", () => {
    expect(BANNED_TERMS).toContainEqual({
      term: "小哥哥",
      replacement: "帥哥",
    });
    expect(BANNED_TERMS).toContainEqual({
      term: "小姐姐",
      replacement: "正妹",
    });

    for (const replacement of ["正妹", "帥哥"]) {
      const terms = BANNED_TERMS.filter(
        (entry) => entry.replacement === replacement,
      ).map((entry) => entry.term);
      expect(terms, replacement).toHaveLength(1);
    }
  });
});

describe("reportBannedTerms", () => {
  const span = (): AuditCallContext => ({ summary: {} });

  it("tags each hit with the column it was found in and stores nothing back", () => {
    const ctx = span();
    const text = "媒體報導以視頻形式呈現。";

    const reported = reportBannedTerms(ctx, [["reputation_summary", text]]);

    expect(reported).toEqual([
      {
        field: "reputation_summary",
        term: "視頻",
        replacement: "影片",
        count: 1,
      },
    ]);
    expect(ctx.summary.bannedTerms).toEqual(reported);
    expect(ctx.summary.bannedTermCount).toBe(1);
    // Report-only: the caller's value is what gets stored, byte for byte.
    expect(text).toBe("媒體報導以視頻形式呈現。");
  });

  it("records nothing at all for clean text", () => {
    const ctx = span();

    expect(
      reportBannedTerms(ctx, [["reputation_summary", "以影片呈現。"]]),
    ).toEqual([]);
    // Absent, not zero: an absent count is what says "scanned, nothing found".
    expect(ctx.summary.bannedTerms).toBeUndefined();
    expect(ctx.summary.bannedTermCount).toBeUndefined();
  });

  it.each(["台南市保安路的門市", "質量輕的材料"])(
    "reports the boundary false positive %s without rewriting it",
    (text) => {
      // Report-only exists BECAUSE the scan cannot tell these from a real hit:
      // a street name and a correct zh-TW word both contain a banned substring.
      // Flagging them for a human is fine; substituting them corrupted rows.
      const ctx = span();
      const before = text;

      expect(
        reportBannedTerms(ctx, [["reputation_summary", text]]),
      ).toHaveLength(1);
      expect(text).toBe(before);
    },
  );

  it("skips non-string and empty values", () => {
    const ctx = span();

    expect(
      reportBannedTerms(ctx, [
        ["reputation_summary", null],
        ["reputation_summary", ""],
        ["reputation_summary", 42],
      ]),
    ).toEqual([]);
    expect(ctx.summary.bannedTermCount).toBeUndefined();
  });

  it("accumulates across calls into one entry per (field, term)", () => {
    const ctx = span();

    reportBannedTerms(ctx, [["alt_zh", "視頻截圖"]]);
    reportBannedTerms(ctx, [["alt_zh", "視頻與視頻"]]);
    reportBannedTerms(ctx, [["reputation_summary", "視頻報導"]]);

    expect(ctx.summary.bannedTerms).toEqual([
      { field: "alt_zh", term: "視頻", replacement: "影片", count: 3 },
      {
        field: "reputation_summary",
        term: "視頻",
        replacement: "影片",
        count: 1,
      },
    ]);
    expect(ctx.summary.bannedTermCount).toBe(4);
  });

  it("keeps accumulating onto hits an earlier caller already published", () => {
    // The accumulator is incremental, so it must still be correct when the
    // array it is extending did not come from its own index.
    const ctx: AuditCallContext = {
      summary: {
        bannedTerms: [
          { field: "alt_zh", term: "視頻", replacement: "影片", count: 2 },
        ],
        bannedTermCount: 2,
      },
    };

    reportBannedTerms(ctx, [["alt_zh", "視頻"]]);

    expect(ctx.summary.bannedTerms).toEqual([
      { field: "alt_zh", term: "視頻", replacement: "影片", count: 3 },
    ]);
    expect(ctx.summary.bannedTermCount).toBe(3);
  });
});

/**
 * DEV-1547. Four terms were removed from the list on production evidence, not
 * on taste: in the first full production dry-run of `backfill:tw` each fired
 * ONLY on correct Taiwanese, never once on genuine zh-CN.
 *
 * They are pinned here rather than left as an absence because the list is a
 * flat 84 entries with no tiers and no allowlist (DEV-1543 decision D2), so
 * "why is 頭像 not banned?" has no answer inside the JSON. Re-adding any of
 * them needs a corpus hit that these strings do not cover.
 *
 * This is a prune, not a fix for the substring class — that class is unbounded
 * (street names and brand names cannot be enumerated) and the write paths
 * handle it by never mutating at all.
 */
describe("terms pruned on production evidence", () => {
  it.each([
    // 操作 belongs to 遠端操作 ("remote operation"); 作業系統 is an OS.
    ["手機遠端操作系統", "操作系統"],
    // A cake shaped like the pet's likeness, not a photo sticker.
    ["客製化寵物頭像鮮食蛋糕", "頭像"],
    // 數 + 組 = "several sets". 陣列 is a programming array.
    ["有數組不同顏色的平底鍋", "數組"],
    // 集成 straddles 密集 and 成長; 九款茶集成的 is 集 + 成, not "integrate".
    ["九款茶集成的台灣茶辦桌", "集成"],
  ])("no longer flags %s, which carried %s", (text, pruned) => {
    // Both halves, or the row is comment-grade data dressed as test data: a
    // sentence that never contained the pruned term would pass this case with
    // the term still on the list, and the table's second column would be free
    // to say anything.
    expect(text, pruned).toContain(pruned);
    expect(detectBannedTerms(text)).toHaveLength(0);
  });

  it("keeps the list free of the four pruned entries", () => {
    const terms = new Set(BANNED_TERMS.map((entry) => entry.term));
    for (const pruned of ["操作系統", "頭像", "數組", "集成"]) {
      expect(terms.has(pruned), pruned).toBe(false);
    }
  });

  /**
   * The other half of the same production evidence: of the 15 patches that run
   * proposed, 5 were correct, and every one of them is pinned here as the text
   * that produced it rather than as a bare term.
   *
   * The five patches carry only TWO distinct terms — 信息 on four image alt
   * texts and 用戶 on one brand description — which is why this is stated as
   * five patches and not, as the test was once named, five terms. Pruning is
   * decided on corpus hits, so the corpus strings are the fixture.
   */
  it.each([
    ["AROMASE促銷活動，介紹產品及優惠信息，包含插圖和文字。", "信息"],
    ["一個促銷活動的海報，包含多個商品和折扣信息。", "信息"],
    ["促銷活動，顯示折扣信息", "信息"],
    ["AROMASE夏季促銷活動，展示產品及優惠信息，包含日期。", "信息"],
    ["台灣用戶影像存放於台灣在地資料中心", "用戶"],
  ])("still flags the correct production patch on %s", (text, term) => {
    const hits = detectBannedTerms(text);
    expect(hits, text).toHaveLength(1);
    expect(hits[0]?.term, text).toBe(term);
  });
});
