import { describe, expect, it } from "vitest";

import {
  BANNED_TERMS,
  detectBannedTerms,
  fixBannedTerms,
} from "@/lib/i18n/banned-terms";

describe("detectBannedTerms", () => {
  it("detects a banned term and reports term, replacement, and offset", () => {
    const hits = detectBannedTerms("這個視頻很好");

    expect(hits).toHaveLength(1);
    expect(hits[0]).toMatchObject({
      term: "視頻",
      replacement: "影片",
      offset: 2,
    });
  });

  it("never mutates the input string", () => {
    const input = "這個視頻很好";
    const hits = detectBannedTerms(input);

    expect(input).toBe("這個視頻很好");
    expect(hits).toHaveLength(1);
  });

  it("does not flag 算法 inside 演算法", () => {
    expect(detectBannedTerms("這個演算法")).toHaveLength(0);
  });

  it("flags bare 算法", () => {
    const hits = detectBannedTerms("這個算法");

    expect(hits).toHaveLength(1);
    expect(hits[0]?.term).toBe("算法");
  });

  it("matches the one Latin-script term in any casing", () => {
    for (const spelling of ["yyds", "Yyds", "YYDS"]) {
      const hits = detectBannedTerms(`這首歌${spelling}`);

      expect(hits, spelling).toHaveLength(1);
      // The canonical entry, whatever the input casing: the audit trail records
      // the term as the list spells it, and the replacement is not case-derived.
      expect(hits[0], spelling).toMatchObject({
        term: "YYDS",
        replacement: "太神了",
        offset: 3,
      });
    }
  });

  it("does not flag the excluded terms", () => {
    const excluded = [
      "點擊",
      "支持",
      "保存",
      "項目",
      "文件",
      "社區",
      "數據",
      "打造",
      "通過",
      "水平",
      "落地",
      "程序",
      "土豆",
      "干貨",
      "乾貨",
      "優化",
      "智能",
      "智能體",
      "人工智能",
    ];

    for (const term of excluded) {
      expect(detectBannedTerms(term), term).toEqual([]);
    }
  });
});

describe("fixBannedTerms", () => {
  it("swaps every hit", () => {
    const result = fixBannedTerms("這個視頻很好");

    expect(result.text).toBe("這個影片很好");
    expect(result.substitutions).toHaveLength(1);
    expect(result.substitutions[0]?.term).toBe("視頻");
  });

  it("returns the input unchanged when there is nothing to fix", () => {
    const result = fixBannedTerms("這個演算法很好");

    expect(result.text).toBe("這個演算法很好");
    expect(result.substitutions).toEqual([]);
  });

  it("substitutes the canonical replacement for a lowercase Latin match", () => {
    const result = fixBannedTerms("這首歌yyds");

    expect(result.text).toBe("這首歌太神了");
    expect(result.substitutions).toHaveLength(1);
  });
});

describe("BANNED_TERMS", () => {
  it("has unique terms", () => {
    const terms = BANNED_TERMS.map((entry) => entry.term);
    expect(new Set(terms).size).toBe(terms.length);
  });

  /**
   * The list was generated by keeping the FIRST ／-separated variant of each
   * source cell, which silently collapsed 「正妹／帥哥」 onto both 小姐姐 and
   * 小哥哥 — rewriting a male referent into a female one, and recording it in
   * the audit trail as a successful fix.
   *
   * A shared replacement is fine in general (several terms legitimately map to
   * 流程). It is only ever wrong when the replacement carries gender, because
   * then one of the two terms must be the wrong one.
   */
  it("maps each gendered term to its own gendered replacement", () => {
    expect(BANNED_TERMS).toContainEqual({ term: "小哥哥", replacement: "帥哥" });
    expect(BANNED_TERMS).toContainEqual({ term: "小姐姐", replacement: "正妹" });

    for (const replacement of ["正妹", "帥哥"]) {
      const terms = BANNED_TERMS.filter(
        (entry) => entry.replacement === replacement,
      ).map((entry) => entry.term);
      expect(terms, replacement).toHaveLength(1);
    }
  });
});
