export { buildApprovalEmail } from '@emails/templates/submission-approved'
export { buildRejectionEmail } from '@emails/templates/submission-rejected'
export { buildClaimEmail } from '@emails/templates/claim-submitted'
export { buildClaimEmailVerificationEmail } from '@emails/templates/claim-verified'
export { buildClaimApprovedEmail } from '@emails/templates/claim-approved'
export { buildClaimRejectedEmail } from '@emails/templates/claim-rejected'
export { buildEditApprovedEmail } from '@emails/templates/edit-approved'
export { buildEditRejectedEmail } from '@emails/templates/edit-rejected'
export { buildWelcomeEmail } from '@emails/templates/welcome'
export { buildProfileNudgeEmail } from '@emails/templates/profile-nudge'
export { buildMicrositeSpotlightEmail } from '@emails/templates/microsite-spotlight'
export { buildReEngagementEmail } from '@emails/templates/re-engagement'
export type { EmailMessage } from '@emails/types'
export { escapeHtml } from '@emails/utils'
