/**
 * Generates the L2 category redirect block in `next.config.ts`.
 *
 * The DEV-1531 taxonomy transform dissolves two L1s. `crafts` loses twelve L2s
 * outright (ten technique nodes with no successor, two that describe a product
 * kind and relocate into `home`), and `kids-pets` is split, so seventeen L2s
 * keep their slug under a new parent. That is 29 previously indexed
 * `/categories/<parent>/<l2>` URLs which 404 the moment production takes the
 * new ontology — the L1-level rows already in `next.config.ts` do not cover
 * them, because a Next `source` is a literal path, not a prefix.
 *
 * The map is DERIVED, never hand-written: the old vocabulary is read from
 * `git show <BASELINE_REF>:src/lib/taxonomy/ontology.ts` (`PRODUCT_SUBCATEGORIES`)
 * and diffed against the working tree's `L2_SUBCATEGORIES`. A slug absent from
 * the new list is deleted; a slug whose `category` changed is reparented. The
 * only fact the diff cannot carry is where a deleted node's traffic should
 * land, so the two relocations are an explicit override table below, taken from
 * the header of `supabase/migrations/20260822090000_retire_crafts_l1.sql`.
 *
 * Every key is the PAIR `(parent, slug)`, never the bare slug. Two slugs make
 * that mandatory rather than tidy: `beverages` is a retired L1 `from` in
 * `RETIRED_CATEGORY_SLUGS` AND a live L2 under `food-drink`, and `ceramics`
 * leaves the L2 vocabulary while surviving as a material value. Bare-slug
 * keying would shadow the live `/categories/food-drink/beverages` page and
 * misread the material axis as a category.
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-category-redirects.ts --check   # exit 1 on drift
 *   pnpm exec tsx scripts/generate-category-redirects.ts --write   # rewrite the block
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { L1_CATEGORIES, L2_SUBCATEGORIES } from "@/lib/taxonomy/ontology";

const ROOT = resolve(import.meta.dirname, "..");

export const NEXT_CONFIG_PATH = resolve(ROOT, "next.config.ts");

/**
 * The pre-transform vocabulary lives on the production branch, not in history
 * generally: `main` IS the deployed ontology until this cutover merges, so it
 * is the only honest statement of which URLs Google currently has indexed.
 */
export const BASELINE_REF = "origin/main";

export const ONTOLOGY_PATH = "src/lib/taxonomy/ontology.ts";

export const BEGIN_MARKER =
  "// >>> generated by scripts/generate-category-redirects.ts - do not edit by hand";
export const END_MARKER = "// <<< end generated block";

/** Indentation of the region inside the `redirects()` array literal. */
const INDENT = "      ";

/** The directory root: the closest surviving intent for a node with no successor. */
export const NO_SUCCESSOR_DESTINATION = "/brands";

/**
 * Where a DELETED L2's traffic goes when it has a successor.
 *
 * Keyed `<oldParent>/<oldSlug>`. Not derivable from the diff — both rows are a
 * data rewrite in the migration, so the new ontology carries no trace of where
 * the old slug went. Source of truth is that migration's header; anything not
 * listed here is a node that left the vocabulary entirely.
 */
export const RELOCATED_L2: Readonly<Record<string, string>> = {
  "crafts/illustration-and-art": "/categories/home/wall-art",
  "crafts/dried-flowers-and-floral-design":
    "/categories/home/floral-arrangements",
};

export type LegacySubcategory = { slug: string; category: string };

export type L2RedirectRow = {
  /** `<oldParent>/<oldSlug>`, the path tail under `/categories/`. */
  from: string;
  /** A live, locale-free destination path. */
  to: string;
  kind: "deleted" | "relocated" | "reparented";
};

function gitShow(ref: string, path: string): string {
  const result = spawnSync("git", ["show", `${ref}:${path}`], {
    cwd: ROOT,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  if (result.error || result.status !== 0) {
    const detail = result.error?.message ?? result.stderr;
    throw new Error(
      `Could not read ${path} at ${ref}: ${detail.trim()}\n` +
        "Run `git fetch origin` first — the baseline is the production branch.",
    );
  }
  return result.stdout;
}

/**
 * Parses `PRODUCT_SUBCATEGORIES` out of a historical `ontology.ts`.
 *
 * A regex, unavoidably: the baseline is a git blob, not a module this process
 * can import. `scripts/model-ab/report.py:19` shows how that goes wrong — its
 * line-anchored regex silently under-counts entries that wrap differently. The
 * guard below is therefore not the parse but the cross-check: the number of
 * `slug:` keys in the array body must equal the number of rows extracted, so a
 * missed entry fails loudly instead of quietly dropping a redirect.
 */
export function parseLegacySubcategories(source: string): LegacySubcategory[] {
  const begin = source.indexOf("export const PRODUCT_SUBCATEGORIES");
  if (begin < 0) {
    throw new Error(
      `${BASELINE_REF}:${ONTOLOGY_PATH} declares no PRODUCT_SUBCATEGORIES`,
    );
  }
  const relativeEnd = source.slice(begin).search(/\n\]/);
  if (relativeEnd < 0) {
    throw new Error("PRODUCT_SUBCATEGORIES has no closing bracket");
  }
  const body = source.slice(begin, begin + relativeEnd);

  const rows: LegacySubcategory[] = [];
  const entryPattern =
    /\{\s*slug:\s*'([^']+)'[\s\S]*?category:\s*'([^']+)'/g;
  for (const match of body.matchAll(entryPattern)) {
    const [, slug, category] = match;
    if (!slug || !category) {
      throw new Error(`Malformed PRODUCT_SUBCATEGORIES entry: ${match[0]}`);
    }
    rows.push({ slug, category });
  }

  const declaredSlugs = body.match(/\bslug:/g)?.length ?? 0;
  if (declaredSlugs !== rows.length) {
    throw new Error(
      `Parsed ${rows.length} of ${declaredSlugs} PRODUCT_SUBCATEGORIES ` +
        "entries; the entry regex under-counted and redirects would be dropped",
    );
  }
  if (rows.length === 0) {
    throw new Error("PRODUCT_SUBCATEGORIES parsed to 0 entries");
  }
  return rows;
}

export function readLegacySubcategories(
  ref: string = BASELINE_REF,
): LegacySubcategory[] {
  return parseLegacySubcategories(gitShow(ref, ONTOLOGY_PATH));
}

/**
 * The `(parent, slug)` -> destination map, in baseline vocabulary order.
 *
 * Order is the old ontology's own so the emitted block is stable across runs
 * and diffs line-for-line when one node moves.
 */
export function buildL2RedirectRows(
  legacy: readonly LegacySubcategory[] = readLegacySubcategories(),
  current: readonly { slug: string; category: string }[] = L2_SUBCATEGORIES,
): L2RedirectRow[] {
  const currentParentBySlug = new Map(
    current.map((sub) => [sub.slug, sub.category]),
  );

  const rows: L2RedirectRow[] = [];
  const seen = new Set<string>();

  for (const { slug, category } of legacy) {
    const key = `${category}/${slug}`;
    if (seen.has(key)) {
      throw new Error(`Duplicate baseline subcategory for ${key}`);
    }
    seen.add(key);

    const currentParent = currentParentBySlug.get(slug);

    if (currentParent === undefined) {
      const relocated = RELOCATED_L2[key];
      rows.push(
        relocated
          ? { from: key, to: relocated, kind: "relocated" }
          : { from: key, to: NO_SUCCESSOR_DESTINATION, kind: "deleted" },
      );
      continue;
    }
    if (currentParent !== category) {
      rows.push({
        from: key,
        to: `/categories/${currentParent}/${slug}`,
        kind: "reparented",
      });
    }
  }

  const unknownOverride = Object.keys(RELOCATED_L2).find(
    (key) => !rows.some((row) => row.from === key && row.kind === "relocated"),
  );
  if (unknownOverride) {
    throw new Error(
      `RELOCATED_L2 names ${unknownOverride}, which is not a deleted ` +
        "baseline subcategory — the override table is stale",
    );
  }

  assertDestinationsAreLive(rows);
  return rows;
}

/**
 * Every destination has to be a page that still renders.
 *
 * A 301 into a 404 passes `pnpm build`, answers 308 to every status check, and
 * only surfaces weeks later as a deindexed page — the same failure the
 * `pets_is_a_live_route_not_a_redirect` case pins at L1 level.
 */
function assertDestinationsAreLive(rows: readonly L2RedirectRow[]): void {
  const liveL1 = new Set<string>(L1_CATEGORIES.map((category) => category.slug));
  const liveL2 = new Set(
    L2_SUBCATEGORIES.map((sub) => `${sub.category}/${sub.slug}`),
  );

  const dead = rows.filter(({ to }) => {
    if (to === NO_SUCCESSOR_DESTINATION) return false;
    const tail = to.replace(/^\/categories\//, "");
    if (tail === to) return true;
    const segments = tail.split("/");
    if (segments.length === 1) return !liveL1.has(tail);
    if (segments.length === 2) return !liveL2.has(tail);
    return true;
  });
  if (dead.length > 0) {
    throw new Error(
      `Dead redirect destinations: ${dead
        .map((row) => `/categories/${row.from} -> ${row.to}`)
        .join(", ")}`,
    );
  }
}

/**
 * Renders the marker-delimited region.
 *
 * The locale expansion is copied from the `RETIRED_CATEGORY_SLUGS` flatMap
 * above it, including the asymmetry: the zh-TW destination is prefix-free
 * because zh-TW is the unprefixed default locale, so `/zh-TW/...` -> `/...` is
 * one hop rather than a redirect into another redirect.
 */
export function renderRedirectBlock(rows: readonly L2RedirectRow[]): string {
  const counts = {
    deleted: rows.filter((row) => row.kind === "deleted").length,
    relocated: rows.filter((row) => row.kind === "relocated").length,
    reparented: rows.filter((row) => row.kind === "reparented").length,
  };

  const pairs = rows
    .map((row) => `${INDENT}    ["${row.from}", "${row.to}"],`)
    .join("\n");

  return [
    `${INDENT}${BEGIN_MARKER}`,
    `${INDENT}// ${rows.length} L2 URLs left the vocabulary with the dissolved L1s:`,
    `${INDENT}// ${counts.deleted} deleted with no successor, ${counts.relocated} relocated, ` +
      `${counts.reparented} reparented.`,
    `${INDENT}// Keys are (parent, slug) pairs — a bare slug would shadow the live`,
    `${INDENT}// /categories/food-drink/beverages page, whose slug is also a retired L1.`,
    `${INDENT}...(`,
    `${INDENT}  [`,
    pairs,
    `${INDENT}  ] as ReadonlyArray<readonly [from: string, to: string]>`,
    `${INDENT}).flatMap(([from, to]) => [`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/categories/\${from}\`,`,
    `${INDENT}    destination: to,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/en/categories/\${from}\`,`,
    `${INDENT}    destination: \`/en\${to}\`,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/zh-TW/categories/\${from}\`,`,
    `${INDENT}    destination: to,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}]),`,
    `${INDENT}${END_MARKER}`,
  ].join("\n");
}

export function applyRedirectBlock(config: string, block: string): string {
  const begin = config.indexOf(BEGIN_MARKER);
  const end = config.indexOf(END_MARKER, begin);
  if (begin < 0 || end < 0) {
    throw new Error(
      `${NEXT_CONFIG_PATH} carries no generated category-redirect block; ` +
        "add the BEGIN/END markers inside redirects() first",
    );
  }
  // Rewind to the start of the marker's own line so the indentation the block
  // renders is the indentation the file gets, not two copies of it.
  const lineStart = config.lastIndexOf("\n", begin) + 1;
  return (
    config.slice(0, lineStart) + block + config.slice(end + END_MARKER.length)
  );
}

export function main(argv: readonly string[] = process.argv.slice(2)): void {
  const mode = argv[0] ?? "--check";
  if (mode !== "--check" && mode !== "--write") {
    throw new Error(`Unknown mode "${mode}"; use --check or --write`);
  }

  const rows = buildL2RedirectRows();
  const current = readFileSync(NEXT_CONFIG_PATH, "utf8");
  const next = applyRedirectBlock(current, renderRedirectBlock(rows));

  if (mode === "--write") {
    if (next !== current) writeFileSync(NEXT_CONFIG_PATH, next);
    console.log(
      `category redirects: ${rows.length} sources written to ${NEXT_CONFIG_PATH}`,
    );
    return;
  }

  if (next !== current) {
    console.error(
      "The category redirect block in next.config.ts is stale against " +
        `${BASELINE_REF}:${ONTOLOGY_PATH}.\n` +
        "Run: pnpm exec tsx scripts/generate-category-redirects.ts --write",
    );
    process.exitCode = 1;
    return;
  }
  console.log(`category redirects: ${rows.length} sources, block is current`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main();
}
