/**
 * Generates the L2 category redirect block in `next.config.ts`.
 *
 * The DEV-1531 taxonomy transform dissolves two L1s. `crafts` loses twelve L2s
 * outright (ten technique nodes with no successor, two that describe a product
 * kind and relocate into `home`), and `kids-pets` is split, so seventeen L2s
 * keep their slug under a new parent. That is 29 previously indexed
 * `/categories/<parent>/<l2>` URLs which 404 the moment production takes the
 * new ontology — the L1-level rows already in `next.config.ts` do not cover
 * them, because a Next `source` is a literal path, not a prefix.
 *
 * The map is DERIVED, never hand-written: the pre-transform vocabulary is read
 * from the FROZEN snapshot at `scripts/category-redirect-baseline.json` and
 * diffed against the working tree's `L2_SUBCATEGORIES`. A slug absent from the
 * new list is deleted; a slug whose `category` changed is reparented. The only
 * fact the diff cannot carry is where a deleted node's traffic should land, so
 * the two relocations are an explicit override table below, taken from the
 * header of `supabase/migrations/20260822090000_retire_crafts_l1.sql`.
 *
 * The baseline is a checked-in snapshot and NOT `git show origin/main:...`,
 * which is what this generator used to do. Two independent reasons, either one
 * fatal:
 *   1. `origin/main` is the branch this very cutover promotes into. The moment
 *      it lands, `main` carries the RENAMED exports (`L2_SUBCATEGORIES`), the
 *      `PRODUCT_SUBCATEGORIES` parse throws, and both `--check` and `--write`
 *      die permanently — while the header comment in `next.config.ts` still
 *      tells the reader to run them. A maintainer "repairing" that by trimming
 *      the override table gets an empty array written over 87 live rules.
 *   2. CI checks out at `fetch-depth: 2` (`.github/workflows/frontend-ci.yml`),
 *      so no ref or commit older than the merge tip is in the clone at all. A
 *      pinned SHA would not survive there either.
 *
 * Regenerating the snapshot is a `--snapshot` run, needs a full clone, and is
 * a deliberate act: the legacy vocabulary is history, so a changed snapshot
 * means a changed statement about which URLs Google has indexed.
 *
 * Every key is the PAIR `(parent, slug)`, never the bare slug. Two slugs make
 * that mandatory rather than tidy: `beverages` is a retired L1 `from` in
 * `RETIRED_CATEGORY_SLUGS` AND a live L2 under `food-drink`, and `ceramics`
 * leaves the L2 vocabulary while surviving as a material value. Bare-slug
 * keying would shadow the live `/categories/food-drink/beverages` page and
 * misread the material axis as a category.
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-category-redirects.ts --check   # exit 1 on drift
 *   pnpm exec tsx scripts/generate-category-redirects.ts --write   # rewrite the block
 *   pnpm exec tsx scripts/generate-category-redirects.ts --snapshot  # re-derive the baseline
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { format, resolveConfig } from "prettier";
import { L1_CATEGORIES, L2_SUBCATEGORIES } from "@/lib/taxonomy/ontology";

const ROOT = resolve(import.meta.dirname, "..");

export const NEXT_CONFIG_PATH = resolve(ROOT, "next.config.ts");

/**
 * The commit `origin/main` pointed at on 2026-08-21, immediately before the
 * DEV-1531 promotion — the last production tip carrying the pre-transform
 * ontology.
 *
 * A full 40-character SHA and NEVER a branch name. A branch name moves; this
 * one moves *the instant this work ships*, which is the whole defect. It is
 * read only by `--snapshot`, so an ordinary `--check` never touches git.
 */
export const BASELINE_COMMIT = "1132c01d209e04fd6f476f6c569ef341d56eea1f";

export const ONTOLOGY_PATH = "src/lib/taxonomy/ontology.ts";

/** The export the pre-transform ontology declared; renamed by DEV-1513. */
export const LEGACY_EXPORT_NAME = "PRODUCT_SUBCATEGORIES";

/** The frozen baseline vocabulary, checked in as data. */
export const LEGACY_SNAPSHOT_PATH = resolve(
  ROOT,
  "scripts/category-redirect-baseline.json",
);

export const BEGIN_MARKER =
  "// >>> generated by scripts/generate-category-redirects.ts - do not edit by hand";
export const END_MARKER = "// <<< end generated block";

/** Indentation of the region inside the `redirects()` array literal. */
const INDENT = "      ";

/** The directory root: the closest surviving intent for a node with no successor. */
export const NO_SUCCESSOR_DESTINATION = "/brands";

/**
 * Where a DELETED L2's traffic goes when it has a successor.
 *
 * Keyed `<oldParent>/<oldSlug>`. Not derivable from the diff — both rows are a
 * data rewrite in the migration, so the new ontology carries no trace of where
 * the old slug went. Source of truth is that migration's header; anything not
 * listed here is a node that left the vocabulary entirely.
 */
export const RELOCATED_L2: Readonly<Record<string, string>> = {
  "crafts/illustration-and-art": "/categories/home/wall-art",
  "crafts/dried-flowers-and-floral-design":
    "/categories/home/floral-arrangements",
};

export type LegacySubcategory = { slug: string; category: string };

export type LegacySnapshot = {
  baselineCommit: string;
  ontologyPath: string;
  exportName: string;
  subcategories: LegacySubcategory[];
};

export type L2RedirectRow = {
  /** `<oldParent>/<oldSlug>`, the path tail under `/categories/`. */
  from: string;
  /** A live, locale-free destination path. */
  to: string;
  kind: "deleted" | "relocated" | "reparented";
};

function gitShow(ref: string, path: string): string {
  const result = spawnSync("git", ["show", `${ref}:${path}`], {
    cwd: ROOT,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  if (result.error || result.status !== 0) {
    const detail = result.error?.message ?? result.stderr;
    throw new Error(
      `Could not read ${path} at ${ref}: ${detail.trim()}\n` +
        "The baseline is a historical commit, so a shallow clone will not " +
        `have it — run \`git fetch --unshallow origin\` (or fetch ${ref} ` +
        "directly) before re-deriving the snapshot.",
    );
  }
  return result.stdout;
}

/**
 * Parses the legacy L2 export out of a historical `ontology.ts`.
 *
 * A regex, unavoidably: the baseline is a git blob, not a module this process
 * can import. `scripts/model-ab/report.py:19` shows how that goes wrong — its
 * line-anchored regex silently under-counts entries that wrap differently. The
 * guard below is therefore not the parse but the cross-check: the number of
 * `slug:` keys in the array body must equal the number of rows extracted, so a
 * missed entry fails loudly instead of quietly dropping a redirect.
 *
 * Only `--snapshot` calls this. It runs against a pinned pre-rename commit, so
 * a missing export means the caller pointed it at the wrong commit — not that
 * anything needs fetching.
 */
export function parseLegacySubcategories(source: string): LegacySubcategory[] {
  const begin = source.indexOf(`export const ${LEGACY_EXPORT_NAME}`);
  if (begin < 0) {
    throw new Error(
      `${BASELINE_COMMIT}:${ONTOLOGY_PATH} declares no ${LEGACY_EXPORT_NAME}. ` +
        "DEV-1513 renamed that export to L2_SUBCATEGORIES, so this is a " +
        "post-transform commit: the baseline must be a commit from BEFORE " +
        "the rename, never a branch tip.",
    );
  }
  const relativeEnd = source.slice(begin).search(/\n\]/);
  if (relativeEnd < 0) {
    throw new Error(`${LEGACY_EXPORT_NAME} has no closing bracket`);
  }
  const body = source.slice(begin, begin + relativeEnd);

  const rows: LegacySubcategory[] = [];
  const entryPattern = /\{\s*slug:\s*'([^']+)'[\s\S]*?category:\s*'([^']+)'/g;
  for (const match of body.matchAll(entryPattern)) {
    const [, slug, category] = match;
    if (!slug || !category) {
      throw new Error(`Malformed ${LEGACY_EXPORT_NAME} entry: ${match[0]}`);
    }
    rows.push({ slug, category });
  }

  const declaredSlugs = body.match(/\bslug:/g)?.length ?? 0;
  if (declaredSlugs !== rows.length) {
    throw new Error(
      `Parsed ${rows.length} of ${declaredSlugs} ${LEGACY_EXPORT_NAME} ` +
        "entries; the entry regex under-counted and redirects would be dropped",
    );
  }
  if (rows.length === 0) {
    throw new Error(`${LEGACY_EXPORT_NAME} parsed to 0 entries`);
  }
  return rows;
}

/**
 * Validates a snapshot as it is read back.
 *
 * The snapshot is the only statement of the indexed URL set, and a truncated
 * or hand-edited one produces a SHORTER redirect map — which is exactly the
 * failure mode with no symptom until a page is deindexed. So every field is
 * checked, including that the file still describes the pinned commit.
 */
export function parseLegacySnapshot(json: string): LegacySnapshot {
  const parsed: unknown = JSON.parse(json);
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error(`${LEGACY_SNAPSHOT_PATH} is not a JSON object`);
  }
  const snapshot = parsed as Partial<LegacySnapshot>;
  if (snapshot.baselineCommit !== BASELINE_COMMIT) {
    throw new Error(
      `${LEGACY_SNAPSHOT_PATH} was taken at ${String(snapshot.baselineCommit)}, ` +
        `but BASELINE_COMMIT is ${BASELINE_COMMIT}; re-run --snapshot`,
    );
  }
  if (!Array.isArray(snapshot.subcategories)) {
    throw new Error(`${LEGACY_SNAPSHOT_PATH} carries no subcategories array`);
  }
  const rows: LegacySubcategory[] = [];
  const seen = new Set<string>();
  for (const entry of snapshot.subcategories as unknown[]) {
    if (typeof entry !== "object" || entry === null) {
      throw new Error(`Malformed snapshot entry: ${JSON.stringify(entry)}`);
    }
    const { slug, category } = entry as Partial<LegacySubcategory>;
    if (typeof slug !== "string" || typeof category !== "string") {
      throw new Error(`Malformed snapshot entry: ${JSON.stringify(entry)}`);
    }
    const key = `${category}/${slug}`;
    if (seen.has(key)) {
      throw new Error(`Duplicate baseline subcategory for ${key}`);
    }
    seen.add(key);
    rows.push({ slug, category });
  }
  if (rows.length === 0) {
    throw new Error(`${LEGACY_SNAPSHOT_PATH} parsed to 0 entries`);
  }
  return {
    baselineCommit: BASELINE_COMMIT,
    ontologyPath: ONTOLOGY_PATH,
    exportName: LEGACY_EXPORT_NAME,
    subcategories: rows,
  };
}

export function readLegacySubcategories(
  snapshotPath: string = LEGACY_SNAPSHOT_PATH,
): LegacySubcategory[] {
  let json: string;
  try {
    json = readFileSync(snapshotPath, "utf8");
  } catch (error) {
    throw new Error(
      `Could not read the frozen baseline at ${snapshotPath}: ` +
        `${error instanceof Error ? error.message : String(error)}\n` +
        "Re-derive it from a full clone with " +
        "`pnpm exec tsx scripts/generate-category-redirects.ts --snapshot`.",
    );
  }
  return parseLegacySnapshot(json).subcategories;
}

export function renderLegacySnapshot(
  rows: readonly LegacySubcategory[],
): string {
  const snapshot: LegacySnapshot = {
    baselineCommit: BASELINE_COMMIT,
    ontologyPath: ONTOLOGY_PATH,
    exportName: LEGACY_EXPORT_NAME,
    subcategories: rows.map(({ slug, category }) => ({ slug, category })),
  };
  return `${JSON.stringify(snapshot, null, 2)}\n`;
}

/**
 * The `(parent, slug)` -> destination map, in baseline vocabulary order.
 *
 * Order is the old ontology's own so the emitted block is stable across runs
 * and diffs line-for-line when one node moves.
 */
export function buildL2RedirectRows(
  legacy: readonly LegacySubcategory[] = readLegacySubcategories(),
  current: readonly { slug: string; category: string }[] = L2_SUBCATEGORIES,
): L2RedirectRow[] {
  const currentParentBySlug = new Map(
    current.map((sub) => [sub.slug, sub.category]),
  );

  const rows: L2RedirectRow[] = [];
  const seen = new Set<string>();

  for (const { slug, category } of legacy) {
    const key = `${category}/${slug}`;
    if (seen.has(key)) {
      throw new Error(`Duplicate baseline subcategory for ${key}`);
    }
    seen.add(key);

    const currentParent = currentParentBySlug.get(slug);

    if (currentParent === undefined) {
      const relocated = RELOCATED_L2[key];
      rows.push(
        relocated
          ? { from: key, to: relocated, kind: "relocated" }
          : { from: key, to: NO_SUCCESSOR_DESTINATION, kind: "deleted" },
      );
      continue;
    }
    if (currentParent !== category) {
      rows.push({
        from: key,
        to: `/categories/${currentParent}/${slug}`,
        kind: "reparented",
      });
    }
  }

  const unknownOverride = Object.keys(RELOCATED_L2).find(
    (key) => !rows.some((row) => row.from === key && row.kind === "relocated"),
  );
  if (unknownOverride) {
    throw new Error(
      `RELOCATED_L2 names ${unknownOverride}, which is not a deleted ` +
        "baseline subcategory — the override table is stale",
    );
  }

  assertDestinationsAreLive(rows);
  return rows;
}

/**
 * Every destination has to be a page that still renders.
 *
 * A 301 into a 404 passes `pnpm build`, answers 308 to every status check, and
 * only surfaces weeks later as a deindexed page — the same failure the
 * `pets_is_a_live_route_not_a_redirect` case pins at L1 level.
 */
function assertDestinationsAreLive(rows: readonly L2RedirectRow[]): void {
  const liveL1 = new Set<string>(
    L1_CATEGORIES.map((category) => category.slug),
  );
  const liveL2 = new Set(
    L2_SUBCATEGORIES.map((sub) => `${sub.category}/${sub.slug}`),
  );

  const dead = rows.filter(({ to }) => {
    if (to === NO_SUCCESSOR_DESTINATION) return false;
    const tail = to.replace(/^\/categories\//, "");
    if (tail === to) return true;
    const segments = tail.split("/");
    if (segments.length === 1) return !liveL1.has(tail);
    if (segments.length === 2) return !liveL2.has(tail);
    return true;
  });
  if (dead.length > 0) {
    throw new Error(
      `Dead redirect destinations: ${dead
        .map((row) => `/categories/${row.from} -> ${row.to}`)
        .join(", ")}`,
    );
  }
}

/**
 * Renders the marker-delimited region.
 *
 * The locale expansion is copied from the `RETIRED_CATEGORY_SLUGS` flatMap
 * above it, including the asymmetry: the zh-TW destination is prefix-free
 * because zh-TW is the unprefixed default locale, so `/zh-TW/...` -> `/...` is
 * one hop rather than a redirect into another redirect.
 *
 * Line width is NOT hand-managed here. Two of these pairs exceed Prettier's
 * printWidth, and a generator that emits over-long lines fights `pnpm format`
 * forever: the formatter rewraps them, `--check` then reports drift, `--write`
 * un-formats the file, and the "do not edit by hand" invariant is broken by
 * the repo's own tooling. `formatConfig` below runs the whole rewritten file
 * through Prettier, so the generator's output is by construction what
 * `prettier --check` already expects.
 */
export function renderRedirectBlock(rows: readonly L2RedirectRow[]): string {
  const counts = {
    deleted: rows.filter((row) => row.kind === "deleted").length,
    relocated: rows.filter((row) => row.kind === "relocated").length,
    reparented: rows.filter((row) => row.kind === "reparented").length,
  };

  const pairs = rows
    .map((row) => `${INDENT}    ["${row.from}", "${row.to}"],`)
    .join("\n");

  return [
    `${INDENT}${BEGIN_MARKER}`,
    `${INDENT}// ${rows.length} L2 URLs left the vocabulary with the dissolved L1s:`,
    `${INDENT}// ${counts.deleted} deleted with no successor, ${counts.relocated} relocated, ` +
      `${counts.reparented} reparented.`,
    `${INDENT}// Keys are (parent, slug) pairs — a bare slug would shadow the live`,
    `${INDENT}// /categories/food-drink/beverages page, whose slug is also a retired L1.`,
    `${INDENT}...(`,
    `${INDENT}  [`,
    pairs,
    `${INDENT}  ] as ReadonlyArray<readonly [from: string, to: string]>`,
    `${INDENT}).flatMap(([from, to]) => [`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/categories/\${from}\`,`,
    `${INDENT}    destination: to,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/en/categories/\${from}\`,`,
    `${INDENT}    destination: \`/en\${to}\`,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}  {`,
    `${INDENT}    source: \`/zh-TW/categories/\${from}\`,`,
    `${INDENT}    destination: to,`,
    `${INDENT}    permanent: true,`,
    `${INDENT}  },`,
    `${INDENT}]),`,
    `${INDENT}${END_MARKER}`,
  ].join("\n");
}

export function applyRedirectBlock(config: string, block: string): string {
  const begin = config.indexOf(BEGIN_MARKER);
  const end = config.indexOf(END_MARKER, begin);
  if (begin < 0 || end < 0) {
    throw new Error(
      `${NEXT_CONFIG_PATH} carries no generated category-redirect block; ` +
        "add the BEGIN/END markers inside redirects() first",
    );
  }
  // Rewind to the start of the marker's own line so the indentation the block
  // renders is the indentation the file gets, not two copies of it.
  const lineStart = config.lastIndexOf("\n", begin) + 1;
  return (
    config.slice(0, lineStart) + block + config.slice(end + END_MARKER.length)
  );
}

/**
 * The repo's own Prettier, resolved from the repo's own config, so `--write`
 * output and `pnpm format` output are the same bytes.
 */
export async function formatConfig(
  source: string,
  filepath: string = NEXT_CONFIG_PATH,
): Promise<string> {
  const options = await resolveConfig(filepath);
  return format(source, { ...options, filepath });
}

/** The rewritten, Prettier-stable `next.config.ts` for the current ontology. */
export async function renderNextConfig(
  current: string,
  rows: readonly L2RedirectRow[],
): Promise<string> {
  return formatConfig(applyRedirectBlock(current, renderRedirectBlock(rows)));
}

/** `29 redirect pairs (87 rules)` — never "29 sources". */
function describeRows(rows: readonly L2RedirectRow[]): string {
  return `${rows.length} redirect pairs (${rows.length * 3} rules)`;
}

function writeSnapshot(): void {
  const rows = parseLegacySubcategories(
    gitShow(BASELINE_COMMIT, ONTOLOGY_PATH),
  );
  mkdirSync(dirname(LEGACY_SNAPSHOT_PATH), { recursive: true });
  writeFileSync(LEGACY_SNAPSHOT_PATH, renderLegacySnapshot(rows));
  console.log(
    `category redirects: ${rows.length} baseline subcategories captured from ` +
      `${BASELINE_COMMIT.slice(0, 8)} into ${LEGACY_SNAPSHOT_PATH}`,
  );
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
): Promise<void> {
  const mode = argv[0] ?? "--check";
  if (mode === "--snapshot") {
    writeSnapshot();
    return;
  }
  if (mode !== "--check" && mode !== "--write") {
    throw new Error(
      `Unknown mode "${mode}"; use --check, --write or --snapshot`,
    );
  }

  const rows = buildL2RedirectRows();
  const current = readFileSync(NEXT_CONFIG_PATH, "utf8");
  const next = await renderNextConfig(current, rows);

  if (mode === "--write") {
    if (next !== current) writeFileSync(NEXT_CONFIG_PATH, next);
    console.log(
      `category redirects: ${describeRows(rows)} written to ${NEXT_CONFIG_PATH}`,
    );
    return;
  }

  if (next !== current) {
    console.error(
      "The category redirect block in next.config.ts is stale against " +
        `${LEGACY_SNAPSHOT_PATH} + the working-tree ontology (or the file is ` +
        "not Prettier-formatted).\n" +
        "Run: pnpm exec tsx scripts/generate-category-redirects.ts --write",
    );
    process.exitCode = 1;
    return;
  }
  console.log(`category redirects: ${describeRows(rows)}, block is current`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
