/**
 * Generates the `public.taxonomy_terms` seed from `src/lib/taxonomy/ontology.ts`.
 *
 * `taxonomy_terms` is the SQL-side mirror of the TypeScript ontology. It exists
 * for one reason: once `brands.subcategories` stores English slugs (DEV-1510),
 * the `cjk_bigrams` arm of `brands_search_document` has no zh-TW text left to
 * index, and `後背包` stops matching a brand tagged `backpacks`. The search
 * trigger expands each stored slug back to its `name_zh` through this table
 * before tokenising.
 *
 * It is GENERATED, never hand-written. Two copies of a 200-term vocabulary
 * maintained by hand drift on the first rename, and a drifted row is invisible:
 * the slug still filters, the label just stops being indexed. The parity test
 * (`src/lib/taxonomy/__tests__/taxonomy-terms-parity.test.ts`) is the CI gate,
 * and it compares the ontology against the committed SQL, so it needs no
 * database.
 *
 * Deliberately NOT a regex over `ontology.ts`. `scripts/model-ab/report.py:19`
 * parses that file with a Python regex and silently under-counts — the same
 * regex shape reports 172 of the 175 L2 nodes, because three entries wrap
 * differently. This module imports the module and reads the values.
 *
 * Usage:
 *   pnpm exec tsx scripts/generate-taxonomy-terms.ts --check   # exit 1 on drift
 *   pnpm exec tsx scripts/generate-taxonomy-terms.ts --write   # rewrite the seed
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  L1_CATEGORIES,
  L2_SUBCATEGORIES,
  MATERIALS,
} from "@/lib/taxonomy/ontology";

export const TAXONOMY_TERM_AXES = ["l1", "l2", "material"] as const;

export type TaxonomyTermAxis = (typeof TAXONOMY_TERM_AXES)[number];

export type TaxonomyTermRow = {
  axis: TaxonomyTermAxis;
  slug: string;
  nameZh: string;
  nameEn: string;
};

const ROOT = resolve(import.meta.dirname, "..");

/**
 * The migration carrying the current seed.
 *
 * A migration is immutable once it is in the ledger, so a later vocabulary
 * change (DEV-1507 retires `crafts`) ships a NEW migration that re-seeds the
 * table and re-points this constant. The parity test always reads whichever
 * file this names, which is what keeps "the SQL matches the ontology" true
 * across those hand-offs instead of only on the day the table was created.
 */
export const TAXONOMY_TERMS_MIGRATION = resolve(
  ROOT,
  "supabase/migrations/20260820170000_material_slugs.sql",
);

export const SEED_BEGIN_MARKER =
  "-- >>> generated by scripts/generate-taxonomy-terms.ts - do not edit by hand";
export const SEED_END_MARKER = "-- <<< end generated block";

/**
 * Every axis reads slug, zh-TW label and English label straight off its ontology
 * entry — no external lookup on any arm.
 *
 * Materials used to be the exception: `MATERIALS` was a list of stored zh-TW
 * terms whose slug WAS the zh term, and the English side lived in the message
 * catalogue. DEV-1525 inverted that. `brands.material` stores `ceramic`,
 * `?material=` carries `ceramic`, and both labels ride on the ontology entry, so
 * no message catalogue is an input to this generator any more.
 */
export function buildTaxonomyTermRows(): TaxonomyTermRow[] {
  const rows: TaxonomyTermRow[] = [
    ...L1_CATEGORIES.map((category) => ({
      axis: "l1" as const,
      slug: category.slug,
      nameZh: category.nameZh,
      nameEn: category.name,
    })),
    ...L2_SUBCATEGORIES.map((subcategory) => ({
      axis: "l2" as const,
      slug: subcategory.slug,
      nameZh: subcategory.nameZh,
      nameEn: subcategory.nameEn,
    })),
    ...MATERIALS.map((material) => ({
      axis: "material" as const,
      slug: material.slug,
      nameZh: material.nameZh,
      nameEn: material.nameEn,
    })),
  ];

  const seen = new Set<string>();
  for (const row of rows) {
    const key = `${row.axis}:${row.slug}`;
    if (seen.has(key)) {
      throw new Error(`Duplicate taxonomy term for the composite key ${key}`);
    }
    seen.add(key);
    if (!row.nameZh || !row.nameEn) {
      throw new Error(`Taxonomy term ${key} is missing a display name`);
    }
  }
  return rows;
}

function quote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function axisCounts(
  rows: TaxonomyTermRow[],
): Record<TaxonomyTermAxis, number> {
  const counts: Record<TaxonomyTermAxis, number> = {
    l1: 0,
    l2: 0,
    material: 0,
  };
  for (const row of rows) counts[row.axis] += 1;
  return counts;
}

export function renderTaxonomyTermsSeed(rows: TaxonomyTermRow[]): string {
  const values = rows
    .map(
      (row) =>
        `  (${quote(row.axis)}, ${quote(row.slug)}, ` +
        `${quote(row.nameZh)}, ${quote(row.nameEn)})`,
    )
    .join(",\n");

  // The per-axis counts are emitted, not typed: a hand-written expectation is
  // a second source of truth that goes stale the first time the vocabulary
  // moves, and a truncated INSERT would then apply silently.
  const expected = JSON.stringify(axisCounts(rows));

  return [
    SEED_BEGIN_MARKER,
    "insert into public.taxonomy_terms (axis, slug, name_zh, name_en) values",
    `${values};`,
    "",
    "do $seed$",
    "declare",
    `  v_expected constant jsonb := ${quote(expected)}::jsonb;`,
    "  v_actual jsonb;",
    "begin",
    "  select coalesce(jsonb_object_agg(counted.axis, counted.total), '{}'::jsonb)",
    "    into v_actual",
    "    from (",
    "      select axis, count(*) as total",
    "      from public.taxonomy_terms",
    "      group by axis",
    "    ) as counted;",
    "",
    "  if v_actual is distinct from v_expected then",
    "    raise exception",
    "      'DEV-1510 taxonomy_terms axis counts are %, expected %',",
    "      v_actual, v_expected",
    "      using errcode = 'P0001';",
    "  end if;",
    "end",
    "$seed$;",
    SEED_END_MARKER,
  ].join("\n");
}

/**
 * Reads the seed block back out of a migration file. The parity test compares
 * this against `buildTaxonomyTermRows()`, so the round trip — ontology to SQL
 * to rows — is what the gate actually asserts.
 */
export function parseTaxonomyTermsSeed(sql: string): TaxonomyTermRow[] {
  const begin = sql.indexOf(SEED_BEGIN_MARKER);
  const end = sql.indexOf(SEED_END_MARKER, begin);
  if (begin < 0 || end < 0) {
    throw new Error(
      "The migration carries no generated taxonomy_terms seed block; " +
        "run `pnpm exec tsx scripts/generate-taxonomy-terms.ts --write`",
    );
  }

  // Only the INSERT is parsed, not the whole block: the count assertion that
  // follows it is plpgsql with its own quoted literals, and a regex allowed to
  // wander into it would read them as terms.
  const block = sql.slice(begin + SEED_BEGIN_MARKER.length, end);
  const valuesAt = block.indexOf("values");
  const insertEnd = block.indexOf(";", valuesAt);
  if (valuesAt < 0 || insertEnd < 0) {
    throw new Error("The generated taxonomy_terms block carries no INSERT");
  }
  const body = block.slice(valuesAt, insertEnd);

  const rows: TaxonomyTermRow[] = [];
  const rowPattern =
    /\(\s*'((?:[^'\n]|'')*)'\s*,\s*'((?:[^'\n]|'')*)'\s*,\s*'((?:[^'\n]|'')*)'\s*,\s*'((?:[^'\n]|'')*)'\s*\)/g;

  for (const match of body.matchAll(rowPattern)) {
    const [axis, slug, nameZh, nameEn] = match
      .slice(1)
      .map((value) => value.replaceAll("''", "'"));
    if (
      axis === undefined ||
      slug === undefined ||
      nameZh === undefined ||
      nameEn === undefined
    ) {
      throw new Error(`Malformed taxonomy_terms seed row: ${match[0]}`);
    }
    if (!(TAXONOMY_TERM_AXES as readonly string[]).includes(axis)) {
      throw new Error(
        `Unknown taxonomy_terms axis "${axis}" in the seed block`,
      );
    }
    rows.push({
      axis: axis as TaxonomyTermAxis,
      slug,
      nameZh,
      nameEn,
    });
  }

  if (rows.length === 0) {
    throw new Error("The generated taxonomy_terms seed block parsed to 0 rows");
  }
  return rows;
}

export function readTaxonomyTermsMigration(): string {
  return readFileSync(TAXONOMY_TERMS_MIGRATION, "utf8");
}

function applySeed(sql: string, seed: string): string {
  const begin = sql.indexOf(SEED_BEGIN_MARKER);
  const end = sql.indexOf(SEED_END_MARKER, begin);
  if (begin < 0 || end < 0) {
    throw new Error(
      `${TAXONOMY_TERMS_MIGRATION} has no seed markers to replace`,
    );
  }
  return sql.slice(0, begin) + seed + sql.slice(end + SEED_END_MARKER.length);
}

function main(): void {
  const mode = process.argv[2] ?? "--check";
  const rows = buildTaxonomyTermRows();
  const seed = renderTaxonomyTermsSeed(rows);
  const current = readTaxonomyTermsMigration();
  const next = applySeed(current, seed);

  if (mode === "--write") {
    if (next !== current) writeFileSync(TAXONOMY_TERMS_MIGRATION, next);
    console.log(
      `taxonomy_terms: ${rows.length} rows written to ${TAXONOMY_TERMS_MIGRATION}`,
    );
    return;
  }

  if (mode !== "--check") {
    throw new Error(`Unknown mode "${mode}"; use --check or --write`);
  }

  if (next !== current) {
    console.error(
      "taxonomy_terms seed is stale against src/lib/taxonomy/ontology.ts.\n" +
        "Run: pnpm exec tsx scripts/generate-taxonomy-terms.ts --write",
    );
    process.exitCode = 1;
    return;
  }
  console.log(`taxonomy_terms: ${rows.length} rows, seed is current`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main();
}
