/**
 * Copies a curated subset of production content into the staging project.
 *
 * Staging is seeded from `supabase/fixtures/staging.sql` with brand rows that
 * have a name, a slug and a placeholder description and nothing else: no
 * images, no real purchase channels, no event participation, no FAQ entries. A
 * staging environment in that state cannot exercise galleries, /where-to-buy,
 * the event sections, or the FAQ/JSON-LD surfaces at all, so a regression in
 * any of them is invisible until production.
 *
 * Two subcommands:
 *
 *   pnpm db:sync:staging:select   choose ~100 production brands and write the
 *                                selection to scripts/sync-staging/brand-slugs.json
 *   pnpm db:sync:staging          copy those brands and their content into staging
 *
 * The selection is committed rather than recomputed on every sync: a reviewer
 * can see which brands staging holds without running anything, and two runs a
 * month apart copy the same brands instead of silently drifting.
 *
 * ---------------------------------------------------------------------------
 * Safety model
 * ---------------------------------------------------------------------------
 *
 * This is the only script in the repo that holds a live handle on BOTH
 * projects at once, so "which client am I holding" is the failure that matters
 * and it is answered three separate ways:
 *
 *   1. Credentials come from `supabase projects api-keys --project-ref <ref>`,
 *      never from the environment. `.env.local` holds PRODUCTION under the
 *      generic names, so a script that read the environment would have
 *      production as its default target — exactly backwards. The package.json
 *      entries deliberately omit `--env-file`; do not add it.
 *   2. Every key is put through `validateSupabaseKeyIdentity`, which decodes
 *      the JWT and asserts the key claims the project it was fetched for. A
 *      client can only be built from a key that names its own project.
 *   3. The production client is wrapped in `createWriteBlockingClient`, so a
 *      write to production is structurally impossible rather than merely
 *      unwritten. A non-empty blocked tally at exit fails the run: it means a
 *      code path tried, and the next reader must know.
 *
 * The client types are branded so that passing the production client to a
 * write helper is a compile error, not a runtime surprise.
 *
 * The sync is ADDITIVE. There is no delete anywhere in this file, and there
 * are exactly two write calls: `upsertBatch` for rows and the storage upload
 * in `syncStorageObjects` for the bytes those rows point at.
 * `curated_products` is deliberately untouched — production has zero rows, and
 * staging's rows are the real authored supply, not a fixture (DEV-1485 deleted the synthetic one), so any
 * mirroring of that table would destroy the homepage product wall's only data.
 *
 * There is no seed ordering to respect any more: `db:seed:staging` no longer
 * writes curated products at all. If the wall's supply ever reaches zero,
 * `e2e/utils/wall-supply.ts` now counts it live and skips rather than failing —
 * that count, not this script, is where a missing wall gets diagnosed.
 */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import {
  createWriteBlockingClient,
  type BlockedWrite,
} from "./model-ab/readonly-client";
import {
  STAGING_PROJECT_REF,
  projectRefFromSupabaseUrl,
  validateSupabaseKeyIdentity,
} from "./staging-target";
import { TEST_BRAND_NAME_PATTERN } from "@/lib/services/public-brand-filter";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** The production project. Asserted, never derived from configuration. */
export const PRODUCTION_PROJECT_REF = "xkcayngbttpxyibgzern";

/**
 * The two refs must differ, checked at compile time rather than at run time.
 *
 * A runtime `prodRef === STAGING_PROJECT_REF` guard reads well but is dead code:
 * both refs are string literals, so the comparison is resolved by the type
 * checker and can never fire. Encoding it as a type makes the guard real — edit
 * either constant to match the other and this stops compiling, which is the
 * moment the mistake actually happens.
 */
type RefsMustDiffer =
  typeof PRODUCTION_PROJECT_REF extends typeof STAGING_PROJECT_REF
    ? never
    : true;
const _refsDiffer: RefsMustDiffer = true;
void _refsDiffer;

export const SELECTION_FILE = path.join(
  ROOT,
  "scripts/sync-staging/brand-slugs.json",
);

/** Carried in the committed file so its purpose is legible without this script. */
const SELECTION_FILE_NOTE =
  "Regenerated by `pnpm db:sync:staging:select`, which reads production and staging. Committed so a reviewer can see which brands staging holds without running anything. `slugs` is the only field `pnpm db:sync:staging` reads; `rationale` explains the pick. An empty `slugs` array means select has not been run yet and sync will refuse.";

/**
 * The description `supabase/fixtures/staging.sql` writes. Selected brands that
 * still carry it after a sync mean the fixture ran last and clobbered the
 * copied content — see `assertNoFixtureDescriptions`.
 */
export const FIXTURE_DESCRIPTION =
  "Staging fixture record for private QA. Public fields only.";

// ---------------------------------------------------------------------------
// Branded clients
// ---------------------------------------------------------------------------

/**
 * `__prod` / `__staging` are phantom fields: nothing ever reads them, they
 * exist so `tsc` refuses to pass one client where the other is expected.
 * `scripts/**\/*.ts` is inside the tsconfig include, so CI enforces it.
 */
export type ProdClient = SupabaseClient & { readonly __prod: unique symbol };
export type StagingClient = SupabaseClient & {
  readonly __staging: unique symbol;
};

export type Row = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Table policy
// ---------------------------------------------------------------------------

/** Copy order. Parents first; every brand-keyed child follows `brands`. */
export const COPY_ORDER = [
  "events",
  "event_exhibitors",
  "brands",
  "brand_images",
  "brand_faq_entries",
  "brand_channels",
  "event_brands",
  "brand_slug_redirects",
  "mit_registry",
] as const;

export type CopyTable = (typeof COPY_ORDER)[number];

/**
 * Copy order as a plain array. A function rather than a bare re-export so the
 * ordering invariants (brands before its children; events and exhibitors
 * before event_brands) have something to assert against.
 */
export function planCopyOrder(): CopyTable[] {
  return [...COPY_ORDER];
}

/**
 * `curated_products` is read for its row count only. It is on this list so the
 * post-condition can prove the sync did not touch it, not because it is copied.
 */
export const COUNTED_TABLES = [...COPY_ORDER, "curated_products"] as const;

/**
 * Authoritative column lists, transcribed from
 * `src/lib/supabase/database.types.ts`.
 *
 * Reads use `select("*")` so a new production column is never silently
 * dropped, and the planners then reject any column that is not on these lists.
 * That is deliberately noisy: a new column may be a plain content field, or it
 * may be another FK into `auth.users` that must be nulled, and only a human can
 * tell the difference. The alternative — a hand-picked projection — fails
 * quietly, and the brand detail page reads `brands` twice with different
 * projections, so "the columns the page needs" is not a stable set.
 */
export const KNOWN_COLUMNS: Record<CopyTable, readonly string[]> = {
  events: [
    "id",
    "slug",
    "name",
    "name_en",
    "summary",
    "summary_en",
    "description",
    "description_en",
    "starts_on",
    "ends_on",
    "venue_name",
    "venue_name_en",
    "venue_address",
    "city",
    "organizer_name",
    "schedule_note",
    "schedule_note_en",
    "admission_note",
    "admission_note_en",
    "travel_note",
    "travel_note_en",
    "lineup_note",
    "lineup_note_en",
    "official_url",
    "ticket_url",
    "is_free",
    "hero_image_url",
    "hero_image_storage_path",
    "status",
    "created_at",
    "updated_at",
  ],
  event_exhibitors: [
    "id",
    "event_id",
    "source_key",
    "source_url",
    "name",
    "name_en",
    "booth",
    "area",
    "area_en",
    "zone",
    "event_category",
    "summary_zh",
    "summary_en",
    "image_url",
    "image_storage_path",
    "image_alt_zh",
    "image_alt_en",
    "content_source",
    "content_submission_id",
    "content_verified_at",
    "website_url",
    "sort_order",
    "verified_at",
    "created_at",
    "updated_at",
  ],
  brands: [
    "id",
    "slug",
    "name",
    "romanized_name",
    "status",
    "source",
    "is_demo",
    "description",
    "description_en",
    "blurb",
    "blurb_en",
    "city",
    "founding_year",
    "category",
    "subcategories",
    "subcategories_en",
    "material",
    "hero_image_url",
    "hero_image_storage_path",
    "other_urls",
    "purchase_website",
    "purchase_pinkoi",
    "purchase_shopee",
    "purchase_myship",
    "social_facebook",
    "social_instagram",
    "social_threads",
    "reputation_summary",
    "site_content",
    "mit_status",
    "mit_story",
    "mit_evidence",
    "mit_declared_at",
    "mit_declared_by",
    "mit_declared_scope",
    "mit_verified_at",
    "model_faq_count",
    "seo_promoted",
    "search_vector",
    "contact_email",
    "draft_data",
    "draft_updated_at",
    "onboarding_dismissed_at",
    "brand_enriched_at",
    "submitted_at",
    "approved_at",
    "created_at",
    "updated_at",
  ],
  brand_images: [
    "id",
    "brand_id",
    "url",
    "source",
    "source_url",
    "storage_path",
    "status",
    "sort_order",
    "alt_zh",
    "alt_en",
    "tags",
    "width",
    "height",
    "score",
    "sharpness",
    "entropy",
    "phash",
    "dominant_color",
    "provider_metadata",
    "rejected_at",
    "rejection_reasons",
    "created_at",
  ],
  brand_faq_entries: [
    "brand_id",
    "preset_id",
    "position",
    "question_zh",
    "question_en",
    "answer_zh",
    "answer_en",
    "source",
    "updated_at",
  ],
  brand_channels: [
    "id",
    "brand_id",
    "name",
    "normalized_name",
    "location_type",
    "region_label",
    "country",
    "district",
    "address",
    "url",
    "source",
    "source_url",
    "provider_metadata",
    "owner_status",
    "owner_status_by",
    "last_confirmed_at",
    "fetched_at",
    "removed_at",
    "removed_by",
    "created_by",
    "created_at",
    "updated_at",
  ],
  event_brands: [
    "id",
    "event_id",
    "brand_id",
    "event_exhibitor_id",
    "booth",
    "area",
    "area_en",
    "note",
    "note_en",
    "sort_order",
    "created_at",
  ],
  brand_slug_redirects: ["old_slug", "new_slug", "created_at"],
  mit_registry: [
    "id",
    "cert_number",
    "brand_name",
    "company_name",
    "product_name",
    "product_model",
    "industry_type",
    "valid_until",
    "synced_at",
  ],
};

export type TablePolicy = {
  /** PostgREST `onConflict` target. */
  onConflict: string;
  /** Columns stripped from the payload entirely. */
  omit: readonly string[];
  /** Columns forced to null in the payload. */
  nullify: readonly string[];
  /** Column holding a production brand id that must be remapped, if any. */
  brandIdColumn: string | null;
  /** Upsert batch size. */
  batchSize: number;
};

export const TABLE_POLICIES: Record<CopyTable, TablePolicy> = {
  // Production ids are preserved so `event_brands.event_id` and
  // `event_brands.event_exhibitor_id` stay valid without a second remap.
  events: {
    onConflict: "id",
    omit: [],
    nullify: [],
    brandIdColumn: null,
    batchSize: 500,
  },
  // `content_submission_id` points at a `content_submissions` row this sync
  // never copies. Left as-is it is a dangling FK; nulled it simply means "no
  // curated copy", which is what staging should show.
  event_exhibitors: {
    onConflict: "id",
    omit: [],
    nullify: ["content_submission_id"],
    brandIdColumn: null,
    batchSize: 500,
  },
  // `id` MUST be omitted. `ON CONFLICT (slug) DO UPDATE` with `id` in the
  // payload executes `set id = excluded.id`, rewriting the primary key of
  // every fixture row that matched — which cascades into staging's existing
  // brand_channels and its seeded curated_products. Omitting it means new brands
  // get staging-generated uuids and the remap applies uniformly to all of them.
  //
  // `seo_promoted` is GENERATED ALWAYS ... STORED: naming it in an INSERT is a
  // hard error. `search_vector` is trigger-maintained and must be recomputed
  // locally or `/brands?q=` stops matching the copied rows. `model_faq_count`
  // is owned by the `sync_brand_model_faq_count` trigger — copying the number
  // without the FAQ rows feeds a lie straight into `seo_promoted` and into
  // sitemap membership.
  //
  // `mit_declared_by` is a uuid FK to `auth.users` and hard-fails the insert.
  // `contact_email` is owner PII. `draft_*` and `onboarding_dismissed_at`
  // belong to a claimed owner's session, and copied brands stay unclaimed.
  brands: {
    onConflict: "slug",
    omit: ["id", "seo_promoted", "search_vector", "model_faq_count"],
    nullify: [
      "contact_email",
      "mit_declared_by",
      "draft_data",
      "draft_updated_at",
      "onboarding_dismissed_at",
    ],
    brandIdColumn: null,
    batchSize: 200,
  },
  // Partitioned at write time — see `planImageUpserts`. This conflict target
  // applies to the rows that have a source_url.
  brand_images: {
    onConflict: "brand_id,source_url",
    omit: ["id"],
    nullify: [],
    brandIdColumn: "brand_id",
    batchSize: 500,
  },
  brand_faq_entries: {
    onConflict: "brand_id,preset_id,position",
    omit: [],
    nullify: [],
    brandIdColumn: "brand_id",
    batchSize: 500,
  },
  // Cannot conflict on `id`: staging already holds fixture channels for all of
  // the pinned brands under their own ids, and production's channels for the
  // same brand carry different ones, so an id-targeted upsert raises 23505 on
  // the (brand_id, normalized_name) unique index instead.
  //
  // `removed_by` is a bare uuid with NO foreign key, so it does not fail the
  // insert — it silently carries production user ids into staging. Nulled for
  // privacy, alongside the two columns that do have FKs.
  brand_channels: {
    onConflict: "brand_id,normalized_name",
    omit: ["id"],
    nullify: ["created_by", "owner_status_by", "removed_by"],
    brandIdColumn: "brand_id",
    batchSize: 500,
  },
  event_brands: {
    onConflict: "event_id,brand_id",
    omit: ["id"],
    nullify: [],
    brandIdColumn: "brand_id",
    batchSize: 500,
  },
  brand_slug_redirects: {
    onConflict: "old_slug",
    omit: [],
    nullify: [],
    brandIdColumn: null,
    batchSize: 500,
  },
  mit_registry: {
    onConflict: "cert_number",
    omit: ["id"],
    nullify: [],
    brandIdColumn: null,
    batchSize: 500,
  },
};

// ---------------------------------------------------------------------------
// Storage objects
// ---------------------------------------------------------------------------

/**
 * The bucket every rendered brand image lives in.
 *
 * Copying ROWS used to be enough: `brand_images.url` was an absolute URL into
 * PRODUCTION's public bucket, so staging rendered production's bytes. DEV-1551
 * replaced that with the same-origin `/i/<storage_path>` proxy, which
 * downloads from the DEPLOYING project's own bucket
 * (`src/app/i/[...path]/route.ts`). A row-only sync therefore leaves staging
 * holding rows for galleries with no bytes behind them — every `/i/` request
 * 404s and `next/image` turns that into a 400.
 */
export const STORAGE_BUCKET = "brand-images";

/**
 * The key prefixes this sync copies.
 *
 * `submissions/` is here even though the public read proxy deny-lists it
 * unconditionally (`PRIVATE_IMAGE_PREFIXES` in `src/lib/images/image-proxy.ts`),
 * so a copied `submissions/` object never serves a page directly. It is copied
 * because it is the SOURCE `promote-submission-images.ts` reads: promotion is a
 * server-side copy inside one bucket, so the source bytes must already be in the
 * project being promoted. Run against a staging bucket that holds only
 * `brands/`, promotion reports `Object not found` for every row — measured
 * 2026-08-23, 781/781.
 *
 * The alternative is promoting in PRODUCTION first and syncing the rewritten
 * keys, which makes a `brands/`-only copy sufficient. That is the better end
 * state and is tracked as DEV-1568; it is not a prerequisite for a usable
 * staging, which is why both prefixes are copied here.
 *
 * Widening this to `events/` or `event-exhibitors/` is a one-line change plus
 * the corresponding surfaces going through `/i/`; the stage reports what it
 * skipped so the gap is visible rather than inferred.
 */
export const SYNCED_STORAGE_PREFIXES = ["brands/", "submissions/"] as const;

/** Columns that hold a bucket-relative key, per copied table. */
const STORAGE_KEY_COLUMNS: Partial<Record<CopyTable, readonly string[]>> = {
  brands: ["hero_image_storage_path"],
  brand_images: ["storage_path"],
  events: ["hero_image_storage_path"],
  event_exhibitors: ["image_storage_path"],
};

/**
 * Whether a row's key is worth copying.
 *
 * `brand_images` keeps rejected rows with their `storage_path` intact, but
 * `brand-storage-maintenance.ts` purges the objects underneath them — so a
 * rejected key resolves to nothing in production and copying it can only fail.
 * Measured 2026-08-23: production holds 6,193 active and 1,718 rejected rows,
 * and a sync that asked for all of them reported 524 `Object not found`.
 *
 * The public read filters on the same column (`brand-images.ts` selects
 * `status = 'active'`), so this matches what actually renders. A row with no
 * `status` column at all is kept: the other key-bearing tables have no such
 * concept and must not be filtered out by an absent field.
 */
/**
 * Whether Storage refused the upload because of the object's media type.
 *
 * Matched on the message because storage-js reports this as a generic 400 with
 * no distinguishing code. Narrow on purpose: a broader match would swallow
 * retryable 400s and silently stop failing runs that ought to fail.
 */
function isUnsupportedMimeError(error: unknown): boolean {
  const message =
    typeof error === "object" && error !== null && "message" in error
      ? String((error as { message: unknown }).message)
      : "";
  return /mime type .* is not supported/i.test(message);
}

function isRenderableImageRow(table: CopyTable, row: Row): boolean {
  if (table !== "brand_images") return true;
  const status = row.status;
  return typeof status !== "string" || status === "active";
}

export type StorageKeyPlan = {
  /** Distinct keys under a synced prefix, sorted. What the copy stage moves. */
  keys: string[];
  /** Distinct keys under some other prefix. Reported, never copied. */
  skippedByPrefix: string[];
};

/**
 * The bucket keys the copied rows reference.
 *
 * Reads every key-bearing column of every table this sync writes, then
 * partitions on `SYNCED_STORAGE_PREFIXES`. `curated_products` is absent on
 * purpose: this sync does not copy that table (see the header), so copying its
 * objects would seed staging with bytes no synced row points at.
 */
export function planStorageKeys(
  rowsByTable: Partial<Record<CopyTable, readonly Row[]>>,
): StorageKeyPlan {
  const wanted = new Set<string>();
  const skipped = new Set<string>();
  for (const [table, columns] of Object.entries(STORAGE_KEY_COLUMNS)) {
    for (const row of rowsByTable[table as CopyTable] ?? []) {
      if (!isRenderableImageRow(table as CopyTable, row)) continue;
      for (const column of columns ?? []) {
        const value = row[column];
        if (typeof value !== "string") continue;
        const key = value.trim();
        if (key.length === 0) continue;
        if (SYNCED_STORAGE_PREFIXES.some((prefix) => key.startsWith(prefix)))
          wanted.add(key);
        else skipped.add(key);
      }
    }
  }
  return {
    keys: [...wanted].sort(),
    skippedByPrefix: [...skipped].sort(),
  };
}

/** The folder each key lives in, deduplicated. One `list` call apiece. */
export function storageFoldersOf(keys: readonly string[]): string[] {
  const folders = new Set<string>();
  for (const key of keys) {
    const cut = key.lastIndexOf("/");
    folders.add(cut < 0 ? "" : key.slice(0, cut));
  }
  return [...folders].sort();
}

/** Objects copied concurrently. Bounded: each one holds a whole image in memory. */
const STORAGE_COPY_CONCURRENCY = 6;
/** Folder listings run concurrently. Metadata only, so a wider fan-out is fine. */
const STORAGE_LIST_CONCURRENCY = 20;
/** storage-js caps a page well below this; the loop stops on an empty page. */
const STORAGE_PAGE_SIZE = 1000;

export type StorageCopyReport = {
  planned: number;
  copied: number;
  /** Already in staging under the same key. Re-running a partial run is cheap. */
  skippedPresent: number;
  /** Retryable. A re-run should clear these; a non-zero count fails the run. */
  failed: number;
  /**
   * Refused by the destination bucket's mime policy. Reported, never retried,
   * and deliberately does NOT fail the run — see the upload branch.
   */
  rejectedByBucket: number;
  /** One line per failing object, capped for the console. */
  errors: string[];
};

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function isRecord(value: unknown): value is Row {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * supabase-js serializes `.in()` into the query string. Fifty uuids is already
 * a ~1.9KB request URI; a few hundred produces a bare HTTP 414 from the
 * fronting proxy with no PostgREST error body at all.
 */
export const IN_CHUNK_SIZE = 50;

/** PostgREST's own hard ceiling on a single response. */
export const PAGE_SIZE = 1000;

export function chunked<T>(values: T[], size = IN_CHUNK_SIZE): T[][] {
  const chunks: T[][] = [];
  for (let index = 0; index < values.length; index += size) {
    chunks.push(values.slice(index, index + size));
  }
  return chunks;
}

/** Stable, seed-dependent ordering key. Never `Math.random`: a selection that
 * changes between runs cannot be reviewed, and hashing rather than sorting by
 * slug keeps the pick from clustering on the alphabet. */
export function selectionHash(seed: number, slug: string): string {
  return createHash("sha256").update(`${seed}:${slug}`).digest("hex");
}

// ---------------------------------------------------------------------------
// Selection planner
// ---------------------------------------------------------------------------

export type SelectionCandidate = {
  id: string;
  slug: string;
  name: string;
  category: string | null;
  city: string | null;
  model_faq_count: number;
  mit_status: string;
  mit_evidence: unknown;
  description: string | null;
  purchase_website: string | null;
  purchase_pinkoi: string | null;
  purchase_shopee: string | null;
  purchase_myship: string | null;
  imageCount: number;
  channelCount: number;
  isEventBrand: boolean;
  isRedirectTarget: boolean;
};

export type SelectionCoverage = {
  faqZero: number;
  mitVerified: number;
  eventBrands: number;
  redirectTargets: number;
  seoPromotedFalse: number;
  cityNull: number;
  cityPresent: number;
};

export type SelectionPlan = {
  target: number;
  seed: number;
  slugs: string[];
  rationale: {
    byCategory: Record<string, number>;
    pinned: string[];
    /**
     * Pinned staging slugs with no production brand. They stay in staging
     * untouched — there is simply nothing to copy onto them.
     */
    pinnedMissingFromProduction: string[];
    coverage: SelectionCoverage;
  };
};

const UNKNOWN_CATEGORY = "unknown";

/**
 * The `seo_promoted` generated column, recomputed locally.
 *
 * Postgres owns the real value and this never writes it. It exists so the
 * selection can guarantee staging holds brands that fall BELOW the content
 * bar — the sitemap-exclusion and directory-ordering paths have no test data
 * otherwise. Mirrors 20260808150000_brand_seo_promotion_bar.sql exactly; if
 * that migration's formula changes, this must change with it.
 */
export function computeSeoPromoted(
  brand: Pick<
    SelectionCandidate,
    | "description"
    | "city"
    | "model_faq_count"
    | "purchase_website"
    | "purchase_pinkoi"
    | "purchase_shopee"
    | "purchase_myship"
  >,
): boolean {
  const hasChannel = [
    brand.purchase_website,
    brand.purchase_pinkoi,
    brand.purchase_shopee,
    brand.purchase_myship,
  ].some((value) => (value ?? "").trim().length > 0);
  return (
    (brand.description ?? "").length >= 200 &&
    hasChannel &&
    ((brand.city ?? "").trim().length > 0 || brand.model_faq_count >= 3)
  );
}

export function categorySlugKey(value: string | null): string {
  const trimmed = (value ?? "").trim();
  return trimmed.length > 0 ? trimmed : UNKNOWN_CATEGORY;
}

/** Coverage floors. Below these the corresponding page or query has no data. */
export const COVERAGE_FLOORS = {
  eventBrands: 10,
  redirectTargets: 5,
  seoPromotedFalse: 5,
  cityNull: 3,
  cityPresent: 3,
} as const;

/**
 * Picks the brands to copy. Pure and deterministic: same candidates plus same
 * seed always produce the same slugs, in the same order.
 *
 * Order of operations matters. Pinned brands come first because staging
 * already holds them and leaving one behind would leave a fixture stub sitting
 * next to fully populated neighbours. Coverage forcing comes second, before
 * any proportional filling, because the shapes it protects — a brand with zero
 * FAQ entries, a verified MIT brand, a redirect target — are rare enough that
 * a proportional draw reliably misses them. The quota fill gets whatever
 * budget is left, which is what keeps staging's category mix recognisably
 * production's.
 */
export function planBrandSelection(input: {
  candidates: SelectionCandidate[];
  pinnedSlugs: string[];
  target: number;
  seed: number;
}): SelectionPlan {
  const { candidates, pinnedSlugs, target, seed } = input;
  if (target < 1) throw new Error("Selection target must be at least 1");

  const bySlug = new Map(candidates.map((brand) => [brand.slug, brand]));
  const ordered = [...candidates].sort((a, b) =>
    selectionHash(seed, a.slug).localeCompare(selectionHash(seed, b.slug)),
  );

  const selected = new Map<string, SelectionCandidate>();
  const take = (brand: SelectionCandidate): void => {
    selected.set(brand.slug, brand);
  };

  // 1. Pinned — every brand staging already holds.
  const pinned: string[] = [];
  const pinnedMissingFromProduction: string[] = [];
  for (const slug of [...new Set(pinnedSlugs)].sort()) {
    const brand = bySlug.get(slug);
    if (!brand) {
      pinnedMissingFromProduction.push(slug);
      continue;
    }
    pinned.push(slug);
    take(brand);
  }

  // 2. Coverage floors, in descending order of scarcity.
  for (const brand of ordered) {
    if (brand.mit_status === "verified") take(brand);
  }

  const faqZeroTypes = new Set(
    [...selected.values()]
      .filter((brand) => brand.model_faq_count === 0)
      .map((brand) => categorySlugKey(brand.category)),
  );
  for (const brand of ordered) {
    if (brand.model_faq_count !== 0) continue;
    const type = categorySlugKey(brand.category);
    if (faqZeroTypes.has(type)) continue;
    faqZeroTypes.add(type);
    take(brand);
  }

  const fillFloor = (
    predicate: (brand: SelectionCandidate) => boolean,
    floor: number,
  ): void => {
    let have = [...selected.values()].filter(predicate).length;
    for (const brand of ordered) {
      if (have >= floor) return;
      if (!predicate(brand) || selected.has(brand.slug)) continue;
      take(brand);
      have += 1;
    }
  };

  fillFloor((brand) => brand.isEventBrand, COVERAGE_FLOORS.eventBrands);
  fillFloor((brand) => brand.isRedirectTarget, COVERAGE_FLOORS.redirectTargets);
  fillFloor(
    (brand) => !computeSeoPromoted(brand),
    COVERAGE_FLOORS.seoPromotedFalse,
  );
  // A null city and a present city travel different code paths on the detail
  // page and in the city facet, so staging needs both.
  fillFloor(
    (brand) => (brand.city ?? "").trim().length === 0,
    COVERAGE_FLOORS.cityNull,
  );
  fillFloor(
    (brand) => (brand.city ?? "").trim().length > 0,
    COVERAGE_FLOORS.cityPresent,
  );

  // 3. Proportional fill on production's own approved distribution, computed
  //    from the candidates rather than hard-coded: a frozen distribution rots
  //    the first time a category grows.
  const quotas = planCategoryQuotas(candidates, target);
  const remaining = ordered.filter((brand) => !selected.has(brand.slug));
  const byRichness = [...remaining].sort(compareRichness(seed));

  for (const [type, quota] of quotas) {
    let have = [...selected.values()].filter(
      (brand) => categorySlugKey(brand.category) === type,
    ).length;
    for (const brand of byRichness) {
      if (selected.size >= target) break;
      if (have >= quota) break;
      if (selected.has(brand.slug)) continue;
      if (categorySlugKey(brand.category) !== type) continue;
      take(brand);
      have += 1;
    }
  }

  // 4. Top-up. A category can run out of candidates before its quota is
  //    met; without this the run lands short of `target` for a reason nobody
  //    would think to look for.
  for (const brand of byRichness) {
    if (selected.size >= target) break;
    if (selected.has(brand.slug)) continue;
    take(brand);
  }

  const chosen = [...selected.values()];
  const byCategory: Record<string, number> = {};
  for (const brand of chosen) {
    const type = categorySlugKey(brand.category);
    byCategory[type] = (byCategory[type] ?? 0) + 1;
  }

  return {
    target,
    seed,
    // Sorted so the committed file has a reviewable diff: adding one brand
    // shows as one added line, not as a reshuffle.
    slugs: chosen.map((brand) => brand.slug).sort(),
    rationale: {
      byCategory: Object.fromEntries(
        Object.entries(byCategory).sort(([a], [b]) => a.localeCompare(b)),
      ),
      pinned,
      pinnedMissingFromProduction,
      coverage: {
        faqZero: chosen.filter((brand) => brand.model_faq_count === 0).length,
        mitVerified: chosen.filter((brand) => brand.mit_status === "verified")
          .length,
        eventBrands: chosen.filter((brand) => brand.isEventBrand).length,
        redirectTargets: chosen.filter((brand) => brand.isRedirectTarget)
          .length,
        seoPromotedFalse: chosen.filter((brand) => !computeSeoPromoted(brand))
          .length,
        cityNull: chosen.filter(
          (brand) => (brand.city ?? "").trim().length === 0,
        ).length,
        cityPresent: chosen.filter(
          (brand) => (brand.city ?? "").trim().length > 0,
        ).length,
      },
    },
  };
}

/**
 * Largest-remainder apportionment of `target` seats across category, on
 * the candidate distribution. Ties break on the type name so the result does
 * not depend on Postgres' row order.
 */
export function planCategoryQuotas(
  candidates: SelectionCandidate[],
  target: number,
): Map<string, number> {
  const counts = new Map<string, number>();
  for (const brand of candidates) {
    const type = categorySlugKey(brand.category);
    counts.set(type, (counts.get(type) ?? 0) + 1);
  }
  const total = candidates.length;
  if (total === 0) return new Map();

  const exact = [...counts.entries()].map(([type, count]) => ({
    type,
    share: (count * target) / total,
  }));
  const quotas = new Map(
    exact.map(({ type, share }) => [type, Math.floor(share)]),
  );
  let assigned = [...quotas.values()].reduce((sum, value) => sum + value, 0);

  const byRemainder = [...exact].sort((a, b) => {
    const remainderA = a.share - Math.floor(a.share);
    const remainderB = b.share - Math.floor(b.share);
    if (remainderA !== remainderB) return remainderB - remainderA;
    return a.type.localeCompare(b.type);
  });
  let cursor = 0;
  while (assigned < target && byRemainder.length > 0) {
    const entry = byRemainder[cursor % byRemainder.length];
    quotas.set(entry.type, (quotas.get(entry.type) ?? 0) + 1);
    assigned += 1;
    cursor += 1;
  }

  return new Map([...quotas.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

/** Richest first: a brand with images and channels exercises more of the app. */
function compareRichness(
  seed: number,
): (a: SelectionCandidate, b: SelectionCandidate) => number {
  return (a, b) => {
    if (a.imageCount !== b.imageCount) return b.imageCount - a.imageCount;
    if (a.channelCount !== b.channelCount)
      return b.channelCount - a.channelCount;
    const lengthA = (a.description ?? "").length;
    const lengthB = (b.description ?? "").length;
    if (lengthA !== lengthB) return lengthB - lengthA;
    return selectionHash(seed, a.slug).localeCompare(
      selectionHash(seed, b.slug),
    );
  };
}

// ---------------------------------------------------------------------------
// Selection file
// ---------------------------------------------------------------------------

/**
 * Deliberately NOT `isValidSlug` from src/lib/services/brands.ts.
 *
 * That one is a write-path validator: it constrains slugs `submissions.ts` is
 * about to mint, so it demands ASCII kebab-case. These slugs are read back out
 * of production, where 45 of 795 approved brands carry Han characters
 * (`廣源良-mit`, `新北坪林阿純茶園`) from an earlier import path. Validating live
 * data against the generator's rules rejects rows the site serves today.
 *
 * So this checks for a slug that is safe to put in a URL segment and in a
 * PostgREST filter — no whitespace, no separators, no control characters,
 * bounded length — and nothing about the alphabet.
 */
const UNSAFE_SLUG_CHARS = /[\s/\\?#&=%+.,;:'\"<>()[\]{}|^`~!*$@]/;
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/;
const MAX_SLUG_LENGTH = 80;

/** Hyphens are legal and common in these slugs; the characters above are not. */
export function isSafeSelectionSlug(value: string): boolean {
  return (
    value.length > 0 &&
    value.length <= MAX_SLUG_LENGTH &&
    !UNSAFE_SLUG_CHARS.test(value) &&
    !CONTROL_CHARS.test(value) &&
    !value.startsWith("-") &&
    !value.endsWith("-")
  );
}

/**
 * Validates the committed selection. `slugs` is the ONLY field `sync` reads;
 * `rationale` exists for the reviewer. A malformed file must fail here rather
 * than reaching the database as a query for a slug that cannot exist.
 */
export function parseSelectionFile(raw: unknown): string[] {
  if (!isRecord(raw)) {
    throw new Error("Selection file must contain a JSON object");
  }
  const slugs = raw.slugs;
  if (!Array.isArray(slugs)) {
    throw new Error("Selection file must contain a slugs array");
  }
  if (slugs.length === 0) {
    throw new Error(
      "Selection file lists no slugs; run `pnpm db:sync:staging:select` first",
    );
  }
  const seen = new Set<string>();
  for (const value of slugs) {
    if (typeof value !== "string" || !isSafeSelectionSlug(value)) {
      throw new Error(
        `Selection file slug ${JSON.stringify(value)} is not URL-safe`,
      );
    }
    if (seen.has(value)) {
      throw new Error(`Selection file lists "${value}" more than once`);
    }
    seen.add(value);
  }
  return slugs as string[];
}

// ---------------------------------------------------------------------------
// Row planners
// ---------------------------------------------------------------------------

function assertKnownColumns(table: CopyTable, row: Row): void {
  const known = new Set(KNOWN_COLUMNS[table]);
  for (const column of Object.keys(row)) {
    if (known.has(column)) continue;
    throw new Error(
      `${table}.${column} exists in production but is not in KNOWN_COLUMNS. Decide whether it is safe to copy (a plain content column) or must be nulled (any FK into auth.users, any owner PII) and add it.`,
    );
  }
}

function applyPolicy(table: CopyTable, row: Row): Row {
  const policy = TABLE_POLICIES[table];
  const payload: Row = {};
  for (const [column, value] of Object.entries(row)) {
    if (policy.omit.includes(column)) continue;
    payload[column] = value;
  }
  // Written explicitly rather than deleted: on an update the column must be
  // overwritten with null, and an absent key leaves the previous value.
  for (const column of policy.nullify) payload[column] = null;
  return payload;
}

/**
 * Production `brands` rows to staging upsert payloads. See TABLE_POLICIES for
 * why each excluded column is excluded.
 */
export function planBrandRows(prodBrands: Row[]): Row[] {
  return prodBrands.map((row) => {
    assertKnownColumns("brands", row);
    return applyPolicy("brands", row);
  });
}

export type BrandRef = { id: string; slug: string };

export type BrandIdRemap = {
  map: Map<string, string>;
  /** Selected slugs with no staging row. Non-empty means the brands upsert
   * did not land, and every child write after this point would attach to
   * nothing. The caller throws. */
  missing: string[];
};

/**
 * Maps production brand ids to the staging ids the brands upsert produced.
 *
 * The slug-equality assertion is not defensive padding. A wrong entry here
 * attaches production brand A's photographs, channels and FAQ answers to
 * staging brand B; every page still renders, every query still succeeds, and
 * nothing anywhere reports an error. There is no later stage that can catch
 * it, so it is caught here or not at all.
 */
export function planBrandIdRemap(
  prodBrands: BrandRef[],
  stagingBrands: BrandRef[],
): BrandIdRemap {
  const stagingById = new Map<string, BrandRef>();
  const stagingBySlug = new Map<string, BrandRef>();
  for (const row of stagingBrands) {
    if (stagingBySlug.has(row.slug)) {
      throw new Error(`Staging returned two brands with slug "${row.slug}"`);
    }
    stagingBySlug.set(row.slug, row);
    stagingById.set(row.id, row);
  }

  const map = new Map<string, string>();
  const missing: string[] = [];
  for (const brand of prodBrands) {
    const target = stagingBySlug.get(brand.slug);
    if (!target) {
      missing.push(brand.slug);
      continue;
    }
    const confirmed = stagingById.get(target.id);
    if (!confirmed || confirmed.slug !== brand.slug) {
      throw new Error(
        `Brand id remap for "${brand.slug}" resolves to staging row ${target.id}, whose slug is "${confirmed?.slug ?? "missing"}"`,
      );
    }
    map.set(brand.id, target.id);
  }
  return { map, missing };
}

export type ChildRowPlan = {
  rows: Row[];
  /** Source brand ids with no remap entry. Reported so the run can fail with
   * the ids named, rather than writing a quietly short table. */
  unmapped: string[];
};

/**
 * Applies a child table's policy and rewrites its brand id. Tables with no
 * brand column (`events`, `event_exhibitors`) pass through the same path so
 * their nullify lists live in one place.
 */
export function planChildRows(
  table: CopyTable,
  rows: Row[],
  idMap: Map<string, string>,
): ChildRowPlan {
  const policy = TABLE_POLICIES[table];
  const planned: Row[] = [];
  const unmapped: string[] = [];

  for (const row of rows) {
    assertKnownColumns(table, row);
    const payload = applyPolicy(table, row);
    if (policy.brandIdColumn) {
      const sourceId = row[policy.brandIdColumn];
      const mapped =
        typeof sourceId === "string" ? idMap.get(sourceId) : undefined;
      if (!mapped) {
        unmapped.push(String(sourceId));
        continue;
      }
      payload[policy.brandIdColumn] = mapped;
    }
    planned.push(payload);
  }

  return { rows: planned, unmapped };
}

export type ImageUpsertPlan = {
  /** Upserted on (brand_id, source_url), production id dropped. */
  withSourceUrl: Row[];
  /** Upserted on id, production id preserved — see below. */
  withoutSourceUrl: Row[];
  unmapped: string[];
};

/**
 * Splits brand_images by whether it has a source_url.
 *
 * The unique index is (brand_id, source_url) and source_url is NULLABLE. NULL
 * never conflicts with NULL in a unique index, so a single natural-key upsert
 * inserts a fresh duplicate of every null-source row on every run and the
 * gallery grows without bound. Those rows conflict on `id` instead, which
 * means keeping production's id for them and only for them.
 *
 * `provider_metadata` is copied verbatim including nulls. The
 * brand_images_copy_provider_metadata BEFORE INSERT trigger tries to backfill
 * a null from `submission_images`, and staging has no matching submissions, so
 * whatever production holds is the only value staging will ever have.
 */
export function planImageUpserts(
  images: Row[],
  idMap: Map<string, string>,
): ImageUpsertPlan {
  const withSourceUrl: Row[] = [];
  const withoutSourceUrl: Row[] = [];
  const unmapped: string[] = [];

  for (const row of images) {
    assertKnownColumns("brand_images", row);
    const sourceBrandId = row.brand_id;
    const mapped =
      typeof sourceBrandId === "string" ? idMap.get(sourceBrandId) : undefined;
    if (!mapped) {
      unmapped.push(String(sourceBrandId));
      continue;
    }

    const hasSourceUrl =
      typeof row.source_url === "string" && row.source_url.length > 0;
    const payload = applyPolicy("brand_images", row);
    payload.brand_id = mapped;
    if (hasSourceUrl) {
      withSourceUrl.push(payload);
    } else {
      withoutSourceUrl.push({ ...payload, id: row.id });
    }
  }

  return { withSourceUrl, withoutSourceUrl, unmapped };
}

export type SlugRedirectPlan = {
  rows: Row[];
  /** Redirects whose old_slug is a live staging brand slug. Inserting one
   * would shadow a real staging brand behind a redirect to another. */
  skippedOldSlugs: string[];
};

export function planSlugRedirects(
  redirects: Row[],
  selectedSlugs: string[],
  stagingBrandSlugs: string[],
): SlugRedirectPlan {
  const selected = new Set(selectedSlugs);
  const live = new Set(stagingBrandSlugs);
  const rows: Row[] = [];
  const skippedOldSlugs: string[] = [];

  for (const row of redirects) {
    assertKnownColumns("brand_slug_redirects", row);
    const newSlug = row.new_slug;
    const oldSlug = row.old_slug;
    if (typeof newSlug !== "string" || !selected.has(newSlug)) continue;
    if (typeof oldSlug === "string" && live.has(oldSlug)) {
      skippedOldSlugs.push(oldSlug);
      continue;
    }
    rows.push(applyPolicy("brand_slug_redirects", row));
  }

  return { rows, skippedOldSlugs };
}

/**
 * `mit_registry` has no brand key at all. The only sound link is the cert
 * number a verified brand already stores in `mit_evidence.mit_smile_cert`,
 * which is what `verifyMitByCert` matches on. Fuzzy name matching would be the
 * obvious alternative and is deliberately not built: the table has no public
 * read path, so a wrong match buys nothing and a missing row costs nothing.
 */
export function planMitRegistryCerts(prodBrands: Row[]): string[] {
  const certs = new Set<string>();
  for (const brand of prodBrands) {
    const evidence = brand.mit_evidence;
    if (!isRecord(evidence)) continue;
    const cert = evidence.mit_smile_cert;
    if (typeof cert !== "string") continue;
    const trimmed = cert.trim();
    if (trimmed) certs.add(trimmed);
  }
  return [...certs].sort();
}

// ---------------------------------------------------------------------------
// Preflight planners
// ---------------------------------------------------------------------------

/**
 * Pulls table -> column names out of a PostgREST OpenAPI document. PostgREST
 * emits Swagger 2 (`definitions`); the key is read defensively because a
 * platform upgrade to OpenAPI 3 moves it to `components.schemas`.
 */
export function parseOpenApiColumns(doc: unknown): Map<string, Set<string>> {
  const columns = new Map<string, Set<string>>();
  if (!isRecord(doc)) return columns;
  const components = isRecord(doc.components) ? doc.components : undefined;
  const schemas = isRecord(doc.definitions)
    ? doc.definitions
    : components && isRecord(components.schemas)
      ? components.schemas
      : undefined;
  if (!schemas) return columns;

  for (const [table, definition] of Object.entries(schemas)) {
    if (!isRecord(definition) || !isRecord(definition.properties)) continue;
    columns.set(table, new Set(Object.keys(definition.properties)));
  }
  return columns;
}

export type ColumnDrift = { table: string; columns: string[] };

/**
 * Production columns missing from staging, per table.
 *
 * Worth doing even though both projects run the same migrations: the two
 * curated-product reads swallow PGRST205/42703 and return `[]`, and the
 * service client carries no `Database` generic, so a schema that has drifted
 * shows up as empty pages rather than as an error.
 */
export function planColumnDrift(
  prodColumns: Map<string, Set<string>>,
  stagingColumns: Map<string, Set<string>>,
  tables: readonly string[],
): ColumnDrift[] {
  const drift: ColumnDrift[] = [];
  for (const table of tables) {
    const production = prodColumns.get(table);
    if (!production) {
      drift.push({ table, columns: ["<table missing from production>"] });
      continue;
    }
    const staging = stagingColumns.get(table);
    if (!staging) {
      drift.push({ table, columns: ["<table missing from staging>"] });
      continue;
    }
    const missing = [...production].filter((column) => !staging.has(column));
    if (missing.length > 0) drift.push({ table, columns: missing.sort() });
  }
  return drift;
}

export type WriteDiff = {
  wouldInsert: number;
  wouldUpdate: number;
  unchanged: number;
};

/**
 * Compares planned rows against what staging holds today, keyed on the same
 * columns the upsert conflicts on. Used for the dry-run report — an operator
 * needs to know whether a run is a first copy or a no-op before authorising it.
 */
export function planWriteDiff(
  planned: Row[],
  existing: Row[],
  keyColumns: string[],
): WriteDiff {
  const keyOf = (row: Row): string =>
    keyColumns.map((column) => JSON.stringify(row[column] ?? null)).join(" ");
  const existingByKey = new Map(existing.map((row) => [keyOf(row), row]));

  let wouldInsert = 0;
  let wouldUpdate = 0;
  let unchanged = 0;
  for (const row of planned) {
    const current = existingByKey.get(keyOf(row));
    if (!current) {
      wouldInsert += 1;
      continue;
    }
    const same = Object.entries(row).every(
      ([column, value]) =>
        JSON.stringify(value ?? null) ===
        JSON.stringify(current[column] ?? null),
    );
    if (same) unchanged += 1;
    else wouldUpdate += 1;
  }
  return { wouldInsert, wouldUpdate, unchanged };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

export type SelectArgs = { target: number; seed: number; dryRun: boolean };
export type SyncArgs = {
  dryRun: boolean;
  only: CopyTable[] | null;
  slugs: string[] | null;
};

function flagValue(argv: string[], name: string): string | undefined {
  const inline = argv.find((arg) => arg.startsWith(`${name}=`));
  if (inline) return inline.slice(name.length + 1);
  const index = argv.indexOf(name);
  return index >= 0 ? argv[index + 1] : undefined;
}

export function parseSelectArgs(argv: string[]): SelectArgs {
  const target = Number(flagValue(argv, "--target") ?? 100);
  const seed = Number(flagValue(argv, "--seed") ?? 1);
  if (!Number.isInteger(target) || target < 1) {
    throw new Error("--target must be a positive integer");
  }
  if (!Number.isInteger(seed)) throw new Error("--seed must be an integer");
  return { target, seed, dryRun: argv.includes("--dry-run") };
}

export function parseSyncArgs(argv: string[]): SyncArgs {
  const onlyRaw = flagValue(argv, "--only");
  let only: CopyTable[] | null = null;
  if (onlyRaw !== undefined) {
    const names = onlyRaw
      .split(",")
      .map((name) => name.trim())
      .filter(Boolean);
    if (names.length === 0) throw new Error("--only requires a table list");
    for (const name of names) {
      if (!(COPY_ORDER as readonly string[]).includes(name)) {
        throw new Error(
          `--only names unknown table "${name}"; expected one of ${COPY_ORDER.join(", ")}`,
        );
      }
    }
    only = names as CopyTable[];
  }

  const slugs = argv.flatMap((arg, index) =>
    arg === "--slug" && argv[index + 1] ? [argv[index + 1]] : [],
  );

  return {
    dryRun: argv.includes("--dry-run"),
    only,
    slugs: slugs.length > 0 ? slugs : null,
  };
}

// ---------------------------------------------------------------------------
// Credentials and clients
// ---------------------------------------------------------------------------

type ApiKeyEntry = { id?: unknown; type?: unknown; api_key?: unknown };

/**
 * Fetches a project's legacy service_role key from the Supabase CLI.
 *
 * Never from the environment, for two reasons. `.env.local` holds PRODUCTION
 * under the generic `NEXT_PUBLIC_SUPABASE_URL` / `SUPABASE_SERVICE_ROLE_KEY`
 * names, so an environment-reading script would default to writing production.
 * And `scripts/check-service-registry.mjs`, which runs before lint on every CI
 * leg, hard-fails on any unregistered credential-shaped env var — a second
 * pair of names would have to be registered as a service this script does not
 * have.
 *
 * Only the legacy JWT form is accepted: it is the only key format that carries
 * a verifiable project ref, which is what makes the identity check below more
 * than a comment.
 */
export function resolveServiceRoleKey(ref: string): {
  url: string;
  key: string;
} {
  const result = spawnSync(
    "pnpm",
    [
      "exec",
      "supabase",
      "projects",
      "api-keys",
      "--project-ref",
      ref,
      "-o",
      "json",
    ],
    { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
  );
  if (result.status !== 0) {
    throw new Error(
      `supabase projects api-keys failed for ${ref}: ${result.stderr.trim() || "no output"}. Run \`pnpm exec supabase login\` first.`,
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(result.stdout) as unknown;
  } catch {
    throw new Error(`supabase projects api-keys returned non-JSON for ${ref}`);
  }
  if (!Array.isArray(parsed)) {
    throw new Error(
      `supabase projects api-keys returned no key list for ${ref}`,
    );
  }

  const entry = (parsed as ApiKeyEntry[]).find(
    (candidate) =>
      isRecord(candidate) &&
      candidate.id === "service_role" &&
      candidate.type === "legacy",
  );
  const key = entry && typeof entry.api_key === "string" ? entry.api_key : "";
  if (!key) {
    throw new Error(`No legacy service_role key found for project ${ref}`);
  }

  validateSupabaseKeyIdentity(key, `service_role@${ref}`, ref, "service_role");
  return { url: `https://${ref}.supabase.co`, key };
}

/**
 * The production handle. Write-blocked, so a stray write cannot reach Postgres
 * even if a future edit adds one; the blocked tally is checked at exit.
 */
function createProductionClient(): {
  client: ProdClient;
  blocked: BlockedWrite[];
  url: string;
  key: string;
} {
  const { url, key } = resolveServiceRoleKey(PRODUCTION_PROJECT_REF);
  const ref = projectRefFromSupabaseUrl(url);
  if (ref !== PRODUCTION_PROJECT_REF) {
    throw new Error(`Production URL identifies project ${ref}`);
  }
  const { client, blocked } = createWriteBlockingClient(url, key);
  return { client: client as ProdClient, blocked, url, key };
}

/**
 * The staging handle. Under `--dry-run` it is wrapped in the same write
 * blocker as production — the opposite direction, the same primitive. A dry
 * run then cannot leak a write no matter which branch it takes, and the
 * blocked tally doubles as the "what would have been written" report.
 */
function createStagingClient(dryRun: boolean): {
  client: StagingClient;
  blocked: BlockedWrite[];
  url: string;
  key: string;
} {
  const { url, key } = resolveServiceRoleKey(STAGING_PROJECT_REF);
  const ref = projectRefFromSupabaseUrl(url);
  if (ref !== STAGING_PROJECT_REF) {
    throw new Error(`Staging URL identifies project ${ref}`);
  }
  if (dryRun) {
    const { client, blocked } = createWriteBlockingClient(url, key);
    return { client: client as StagingClient, blocked, url, key };
  }
  return {
    client: createClient(url, key) as StagingClient,
    blocked: [],
    url,
    key,
  };
}

// ---------------------------------------------------------------------------
// Read helpers
// ---------------------------------------------------------------------------

type QueryResult = { data: unknown; error: unknown };

function describeError(error: unknown): string {
  if (isRecord(error) && typeof error.message === "string")
    return error.message;
  return String(error);
}

/**
 * Reads every row a query matches, one PostgREST page at a time.
 *
 * A single `.select()` silently stops at the server's max-rows ceiling, so a
 * table read without paging looks complete and is not. The loop stops at the
 * first short page.
 */
async function readAllPages<T>(
  build: (from: number, to: number) => PromiseLike<QueryResult>,
  label: string,
): Promise<T[]> {
  const collected: T[] = [];
  for (let offset = 0; ; offset += PAGE_SIZE) {
    const { data, error } = await build(offset, offset + PAGE_SIZE - 1);
    if (error) throw new Error(`${label} failed: ${describeError(error)}`);
    const page = (data ?? []) as T[];
    collected.push(...page);
    if (page.length < PAGE_SIZE) return collected;
  }
}

/** Paged read of a whole table. */
async function readTable<T>(
  client: ProdClient | StagingClient,
  table: string,
  columns: string,
  orderColumns: string[],
): Promise<T[]> {
  return readAllPages<T>((from, to) => {
    let query = client.from(table).select(columns);
    for (const column of orderColumns) query = query.order(column);
    return query.range(from, to);
  }, `read ${table}`);
}

/** Paged, chunked read of the rows matching a value list. */
async function readByValues<T>(
  client: ProdClient | StagingClient,
  table: string,
  columns: string,
  column: string,
  values: string[],
  orderColumns: string[],
): Promise<T[]> {
  const collected: T[] = [];
  for (const chunk of chunked(values)) {
    const page = await readAllPages<T>((from, to) => {
      let query = client.from(table).select(columns).in(column, chunk);
      for (const orderColumn of orderColumns) query = query.order(orderColumn);
      return query.range(from, to);
    }, `read ${table} by ${column}`);
    collected.push(...page);
  }
  return collected;
}

async function countRows(
  client: ProdClient | StagingClient,
  table: string,
): Promise<number> {
  const { count, error } = await client
    .from(table)
    .select("*", { count: "exact", head: true });
  if (error) throw new Error(`count ${table} failed: ${describeError(error)}`);
  return count ?? 0;
}

// ---------------------------------------------------------------------------
// The one write
// ---------------------------------------------------------------------------

/**
 * The ONLY write in this file. Sequential by design: parallel batches against
 * the same conflict target deadlock each other, and a failure mid-flight would
 * leave a set of half-applied tables nobody can reason about.
 *
 * A failing batch fails the table. Continuing past one would report a copied
 * count that no longer describes what staging holds.
 */
async function upsertBatch(
  client: StagingClient,
  table: string,
  rows: Row[],
  onConflict: string,
  batchSize: number,
): Promise<number> {
  let written = 0;
  for (const batch of chunked(rows, batchSize)) {
    const { error } = await client.from(table).upsert(batch, { onConflict });
    if (error) {
      throw new Error(
        `upsert ${table} (${written}/${rows.length} written) failed: ${describeError(error)}`,
      );
    }
    written += batch.length;
  }
  return written;
}

// ---------------------------------------------------------------------------
// The other write: storage objects
// ---------------------------------------------------------------------------

/**
 * The keys a project already holds under the given folders.
 *
 * Folder-scoped rather than a whole-bucket walk: the sync knows exactly which
 * folders its keys live in (`brands/<brand-id>/`), and a recursive listing of
 * a production-sized bucket is thousands of round trips for an answer we do
 * not need. Only files are collected — storage-js reports a folder as an entry
 * with a null id.
 */
export async function listStorageKeys(
  /**
   * Unbranded on purpose: this is the one storage helper that cannot write, so
   * "which project am I holding" is not a hazard here, and
   * `check-image-resolvability.ts` needs the same listing against either one.
   */
  client: SupabaseClient,
  folders: readonly string[],
): Promise<Set<string>> {
  const found = new Set<string>();

  const listFolder = async (folder: string): Promise<void> => {
    for (let offset = 0; ;) {
      const { data, error } = await client.storage
        .from(STORAGE_BUCKET)
        .list(folder, {
          limit: STORAGE_PAGE_SIZE,
          offset,
          sortBy: { column: "name", order: "asc" },
        });
      if (error) {
        throw new Error(
          `storage list "${folder || "/"}" failed: ${describeError(error)}`,
        );
      }
      const page = data ?? [];
      // The endpoint may cap a page below the requested limit, so a SHORT page
      // is not the end of the listing — only an empty one is.
      if (page.length === 0) return;
      offset += page.length;
      for (const entry of page) {
        if (entry.id === null) continue;
        found.add(folder ? `${folder}/${entry.name}` : entry.name);
      }
    }
  };

  for (
    let index = 0;
    index < folders.length;
    index += STORAGE_LIST_CONCURRENCY
  ) {
    await Promise.all(
      folders.slice(index, index + STORAGE_LIST_CONCURRENCY).map(listFolder),
    );
  }
  return found;
}

/**
 * Copies the referenced objects from production's bucket into staging's.
 *
 * Additive and idempotent, like the row sync: `upsert: true` means a re-run
 * overwrites rather than conflicts, and nothing is ever removed from either
 * side. That is what makes a partial run safe — an object that failed on
 * attempt one is simply copied on attempt two.
 *
 * A per-object failure is recorded and the stage continues. Aborting on the
 * first one would leave the bucket in a state whose only description is "some
 * prefix of a sorted key list", which nobody can act on; a tally of what did
 * not make it is actionable.
 */
async function syncStorageObjects(input: {
  production: ProdClient;
  staging: StagingClient;
  keys: readonly string[];
  dryRun: boolean;
}): Promise<StorageCopyReport> {
  const { production, staging, keys, dryRun } = input;
  const report: StorageCopyReport = {
    planned: keys.length,
    copied: 0,
    skippedPresent: 0,
    failed: 0,
    rejectedByBucket: 0,
    errors: [],
  };
  if (keys.length === 0) return report;

  const present = await listStorageKeys(staging, storageFoldersOf(keys));
  const missing = keys.filter((key) => !present.has(key));
  report.skippedPresent = keys.length - missing.length;

  // A dry run reports the plan without moving bytes. Downloading thousands of
  // images to then discard them is the kind of cost that stops people running
  // the dry run at all.
  if (dryRun) return report;

  const copyOne = async (key: string): Promise<void> => {
    const { data, error } = await production.storage
      .from(STORAGE_BUCKET)
      .download(key);
    if (error || !data) {
      report.failed += 1;
      if (report.errors.length < 20) {
        report.errors.push(`download ${key}: ${describeError(error)}`);
      }
      return;
    }
    const { error: uploadError } = await staging.storage
      .from(STORAGE_BUCKET)
      .upload(key, data, {
        upsert: true,
        contentType: data.type || "application/octet-stream",
      });
    if (uploadError) {
      // A mime the destination bucket refuses is not a transient failure: the
      // bytes are what they are, and every re-run rejects them identically.
      // Counting it with the retryable failures would leave this command
      // permanently exit-1, which teaches operators to ignore a red sync.
      // Production holds at least one SVG stored under a `.jpg` key
      // (measured 2026-08-23); that is bad data to fix at the source, not here.
      if (isUnsupportedMimeError(uploadError)) {
        report.rejectedByBucket += 1;
      } else {
        report.failed += 1;
      }
      if (report.errors.length < 20) {
        report.errors.push(`upload ${key}: ${describeError(uploadError)}`);
      }
      return;
    }
    report.copied += 1;
  };

  for (
    let index = 0;
    index < missing.length;
    index += STORAGE_COPY_CONCURRENCY
  ) {
    await Promise.all(
      missing.slice(index, index + STORAGE_COPY_CONCURRENCY).map(copyOne),
    );
  }
  return report;
}

// ---------------------------------------------------------------------------
// select
// ---------------------------------------------------------------------------

const SELECTION_BRAND_COLUMNS = [
  "id",
  "slug",
  "name",
  "category",
  "city",
  "model_faq_count",
  "mit_status",
  "mit_evidence",
  "description",
  "purchase_website",
  "purchase_pinkoi",
  "purchase_shopee",
  "purchase_myship",
].join(",");

async function runSelect(argv: string[]): Promise<void> {
  const args = parseSelectArgs(argv);
  const production = createProductionClient();
  const staging = createStagingClient(true);

  console.log(
    `Reading production (${PRODUCTION_PROJECT_REF}) and staging (${STAGING_PROJECT_REF}).`,
  );

  // Approved, non-test brands only: the [E2E-TEST] prefix is excluded from
  // every public surface, and copying one into staging would put it back into
  // the counts the exclusion exists to protect. The pattern constant is shared
  // with `excludeTestBrands`; the helper itself is not used here because its
  // generic wants a builder whose `not()` takes a plain string operator, and
  // the paged read below threads the builder through a callback instead.
  const candidates = await readAllPages<Row>(
    (from, to) =>
      production.client
        .from("brands")
        .select(SELECTION_BRAND_COLUMNS)
        .eq("status", "approved")
        .not("name", "like", TEST_BRAND_NAME_PATTERN)
        .order("id")
        .range(from, to),
    "read production brands",
  );

  const images = await readTable<{ brand_id: string }>(
    production.client,
    "brand_images",
    "brand_id",
    ["brand_id"],
  );
  const channels = await readTable<{ brand_id: string }>(
    production.client,
    "brand_channels",
    "brand_id",
    ["brand_id"],
  );
  const eventBrands = await readTable<{ brand_id: string }>(
    production.client,
    "event_brands",
    "brand_id",
    ["brand_id"],
  );
  const redirects = await readTable<{ new_slug: string }>(
    production.client,
    "brand_slug_redirects",
    "new_slug",
    ["new_slug"],
  );
  const stagingBrands = await readTable<{ slug: string }>(
    staging.client,
    "brands",
    "slug",
    ["slug"],
  );

  const imageCounts = tally(images.map((row) => row.brand_id));
  const channelCounts = tally(channels.map((row) => row.brand_id));
  const eventBrandIds = new Set(eventBrands.map((row) => row.brand_id));
  const redirectTargets = new Set(redirects.map((row) => row.new_slug));

  const enriched: SelectionCandidate[] = candidates.map((row) => ({
    id: String(row.id),
    slug: String(row.slug),
    name: String(row.name),
    category: (row.category as string | null) ?? null,
    city: (row.city as string | null) ?? null,
    model_faq_count: Number(row.model_faq_count ?? 0),
    mit_status: String(row.mit_status ?? ""),
    mit_evidence: row.mit_evidence,
    description: (row.description as string | null) ?? null,
    purchase_website: (row.purchase_website as string | null) ?? null,
    purchase_pinkoi: (row.purchase_pinkoi as string | null) ?? null,
    purchase_shopee: (row.purchase_shopee as string | null) ?? null,
    purchase_myship: (row.purchase_myship as string | null) ?? null,
    imageCount: imageCounts.get(String(row.id)) ?? 0,
    channelCount: channelCounts.get(String(row.id)) ?? 0,
    isEventBrand: eventBrandIds.has(String(row.id)),
    isRedirectTarget: redirectTargets.has(String(row.slug)),
  }));

  const plan = planBrandSelection({
    candidates: enriched,
    pinnedSlugs: stagingBrands.map((row) => row.slug),
    target: args.target,
    seed: args.seed,
  });

  const file = {
    note: SELECTION_FILE_NOTE,
    generatedAt: new Date().toISOString(),
    ...plan,
  };
  const serialized = `${JSON.stringify(file, null, 2)}\n`;

  assertNoProductionWrites(production.blocked);

  if (args.dryRun) {
    console.log(serialized);
    console.log("[dry-run] selection not written");
    return;
  }

  await mkdir(path.dirname(SELECTION_FILE), { recursive: true });
  await writeFile(SELECTION_FILE, serialized, "utf8");
  console.log(
    `Wrote ${plan.slugs.length} slugs to ${path.relative(ROOT, SELECTION_FILE)}`,
  );
}

function tally(values: string[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return counts;
}

// ---------------------------------------------------------------------------
// sync
// ---------------------------------------------------------------------------

function assertNoProductionWrites(blocked: BlockedWrite[]): void {
  if (blocked.length === 0) return;
  console.error("A code path attempted to WRITE PRODUCTION:");
  for (const attempt of blocked) {
    console.error(`  ${attempt.table}.${attempt.method}`);
  }
  console.error(
    "The write was blocked, but the path exists. Fix it before running again.",
  );
  process.exit(1);
}

async function fetchOpenApiColumns(
  url: string,
  key: string,
  label: string,
): Promise<Map<string, Set<string>>> {
  const response = await fetch(`${url}/rest/v1/`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` },
  });
  if (!response.ok) {
    throw new Error(
      `Could not read the ${label} schema document (HTTP ${response.status})`,
    );
  }
  return parseOpenApiColumns((await response.json()) as unknown);
}

/**
 * The column a dry run scopes its "what does staging already hold" read by,
 * per table. Always a column that survives the table's own policy, so it is
 * present on the planned rows themselves.
 */
const DIFF_LOOKUP_COLUMN: Record<CopyTable, string> = {
  events: "id",
  event_exhibitors: "id",
  brands: "slug",
  brand_images: "brand_id",
  brand_faq_entries: "brand_id",
  brand_channels: "brand_id",
  event_brands: "brand_id",
  brand_slug_redirects: "old_slug",
  mit_registry: "cert_number",
};

/** Staging rows in scope for a planned batch, for the dry-run diff. */
async function readExistingForDiff(
  client: StagingClient,
  table: CopyTable,
  rows: Row[],
): Promise<Row[]> {
  const column = DIFF_LOOKUP_COLUMN[table];
  const values = [
    ...new Set(
      rows
        .map((row) => row[column])
        .filter((value): value is string => typeof value === "string"),
    ),
  ];
  if (values.length === 0) return [];
  return readByValues<Row>(client, table, "*", column, values, [column]);
}

/** Placeholder staging ids for a dry run, where the brands upsert never ran
 * and the rows it would have created therefore do not exist yet. */
function dryRunPlaceholderId(index: number): string {
  return `00000000-0000-4000-8000-${String(index).padStart(12, "0")}`;
}

async function runSync(argv: string[]): Promise<void> {
  const args = parseSyncArgs(argv);
  const production = createProductionClient();
  const staging = createStagingClient(args.dryRun);

  const wants = (table: CopyTable): boolean =>
    args.only === null || args.only.includes(table);

  console.log(
    `${args.dryRun ? "[dry-run] " : ""}Syncing ${PRODUCTION_PROJECT_REF} -> ${STAGING_PROJECT_REF}`,
  );

  // --- Selection -----------------------------------------------------------
  const selectionRaw = JSON.parse(
    await readFile(SELECTION_FILE, "utf8"),
  ) as unknown;
  let slugs = parseSelectionFile(selectionRaw);
  if (args.slugs) {
    const requested = new Set(args.slugs);
    const unknown = args.slugs.filter((slug) => !slugs.includes(slug));
    if (unknown.length > 0) {
      throw new Error(
        `--slug names ${unknown.join(", ")}, which the selection file does not list`,
      );
    }
    slugs = slugs.filter((slug) => requested.has(slug));
  }
  console.log(`Selection: ${slugs.length} brands`);

  // --- Preflight -----------------------------------------------------------
  const prodColumns = await fetchOpenApiColumns(
    production.url,
    production.key,
    "production",
  );
  const stagingColumns = await fetchOpenApiColumns(
    staging.url,
    staging.key,
    "staging",
  );
  const drift = planColumnDrift(prodColumns, stagingColumns, COPY_ORDER);
  if (drift.length > 0) {
    for (const entry of drift) {
      console.error(
        `Schema drift: staging.${entry.table} is missing ${entry.columns.join(", ")}`,
      );
    }
    throw new Error(
      "Staging schema is behind production. Run `pnpm db:migrate` against staging first.",
    );
  }

  // The same comparison against KNOWN_COLUMNS. The row planners reject an
  // unknown column too, but they do so table by table, so without this the run
  // would already have written `events` and `brands` before discovering that a
  // new `brand_images` column needs a decision. Here it costs nothing.
  const unknownColumns = planColumnDrift(
    prodColumns,
    new Map<string, Set<string>>(
      COPY_ORDER.map((table): [string, Set<string>] => [
        table,
        new Set(KNOWN_COLUMNS[table]),
      ]),
    ),
    COPY_ORDER,
  );
  if (unknownColumns.length > 0) {
    for (const entry of unknownColumns) {
      console.error(
        `Unmapped production column(s) on ${entry.table}: ${entry.columns.join(", ")}`,
      );
    }
    throw new Error(
      "Production has columns this sync has never been told about. Add each to KNOWN_COLUMNS, and to a nullify list if it is an auth.users reference or owner PII.",
    );
  }

  const before = new Map<string, number>();
  for (const table of COUNTED_TABLES) {
    before.set(table, await countRows(staging.client, table));
  }
  console.log(
    `Staging before: ${COUNTED_TABLES.map((table) => `${table}=${before.get(table)}`).join(" ")}`,
  );

  // A selected brand still carrying the fixture description means the fixture
  // ran after the last sync and overwrote the copied content. It is a warning
  // rather than a refusal because this sync is the repair: refusing would make
  // the stated remedy impossible, and on a first run every fixture brand is in
  // exactly this state.
  const stagingSelected = await readByValues<Row>(
    staging.client,
    "brands",
    "slug,description",
    "slug",
    slugs,
    ["slug"],
  );
  const fixtureStubs = stagingSelected.filter(
    (row) => row.description === FIXTURE_DESCRIPTION,
  );
  if (fixtureStubs.length > 0) {
    console.warn(
      `${fixtureStubs.length} selected brand(s) still hold the staging fixture description; this run replaces it. If that count grows after a sync, db:seed:staging ran last — re-run this sync.`,
    );
  }

  // --- Read production -----------------------------------------------------
  const prodBrands = await readByValues<Row>(
    production.client,
    "brands",
    "*",
    "slug",
    slugs,
    ["slug"],
  );
  const foundSlugs = new Set(prodBrands.map((row) => String(row.slug)));
  const missingInProduction = slugs.filter((slug) => !foundSlugs.has(slug));
  if (missingInProduction.length > 0) {
    throw new Error(
      `Production has no brand for ${missingInProduction.join(", ")}. Re-run db:sync:staging:select.`,
    );
  }
  const prodBrandIds = prodBrands.map((row) => String(row.id));

  const prodEventBrands = await readByValues<Row>(
    production.client,
    "event_brands",
    "*",
    "brand_id",
    prodBrandIds,
    ["id"],
  );
  const eventIds = [
    ...new Set(prodEventBrands.map((row) => String(row.event_id))),
  ];
  const prodEvents =
    eventIds.length > 0
      ? await readByValues<Row>(
          production.client,
          "events",
          "*",
          "id",
          eventIds,
          ["id"],
        )
      : [];
  // Every exhibitor of a referenced event, not only the linked ones:
  // event_brands.event_exhibitor_id can point at any of them, and the floor
  // map renders the unlinked rows too.
  const prodExhibitors =
    eventIds.length > 0
      ? await readByValues<Row>(
          production.client,
          "event_exhibitors",
          "*",
          "event_id",
          eventIds,
          ["id"],
        )
      : [];

  // A staging event that shares a slug with a production event but has a
  // different id would fail the events upsert on the slug unique index, after
  // the conflict target (id) has already missed it.
  const stagingEvents = await readTable<{ id: string; slug: string }>(
    staging.client,
    "events",
    "id,slug",
    ["id"],
  );
  const stagingEventIdBySlug = new Map(
    stagingEvents.map((row) => [row.slug, row.id]),
  );
  for (const event of prodEvents) {
    const existingId = stagingEventIdBySlug.get(String(event.slug));
    if (existingId && existingId !== String(event.id)) {
      throw new Error(
        `Staging already has an event "${String(event.slug)}" under a different id (${existingId}). Resolve it by hand before syncing.`,
      );
    }
  }

  const prodImages = await readByValues<Row>(
    production.client,
    "brand_images",
    "*",
    "brand_id",
    prodBrandIds,
    ["id"],
  );
  const prodFaq = await readByValues<Row>(
    production.client,
    "brand_faq_entries",
    "*",
    "brand_id",
    prodBrandIds,
    ["brand_id", "preset_id", "position"],
  );
  const prodChannels = await readByValues<Row>(
    production.client,
    "brand_channels",
    "*",
    "brand_id",
    prodBrandIds,
    ["id"],
  );
  const prodRedirects = await readByValues<Row>(
    production.client,
    "brand_slug_redirects",
    "*",
    "new_slug",
    slugs,
    ["old_slug"],
  );
  const certs = planMitRegistryCerts(prodBrands);
  const prodRegistry =
    certs.length > 0
      ? await readByValues<Row>(
          production.client,
          "mit_registry",
          "*",
          "cert_number",
          certs,
          ["cert_number"],
        )
      : [];

  const copied = new Map<string, number>();
  const planned = new Map<string, number>();
  /** Every planned batch, keyed by table + conflict target. brand_images
   * appears twice (see planImageUpserts) and each partition diffs separately. */
  const plannedBatches: {
    table: CopyTable;
    onConflict: string;
    rows: Row[];
  }[] = [];

  const write = async (
    table: CopyTable,
    rows: Row[],
    onConflict = TABLE_POLICIES[table].onConflict,
  ): Promise<void> => {
    planned.set(table, (planned.get(table) ?? 0) + rows.length);
    plannedBatches.push({ table, onConflict, rows });
    if (rows.length === 0) return;
    const written = await upsertBatch(
      staging.client,
      table,
      rows,
      onConflict,
      TABLE_POLICIES[table].batchSize,
    );
    copied.set(table, (copied.get(table) ?? 0) + written);
  };

  // --- 1-2. Events and exhibitors -----------------------------------------
  if (wants("events")) {
    await write("events", planChildRows("events", prodEvents, new Map()).rows);
  }
  if (wants("event_exhibitors")) {
    await write(
      "event_exhibitors",
      planChildRows("event_exhibitors", prodExhibitors, new Map()).rows,
    );
  }

  // --- 3. Brands -----------------------------------------------------------
  if (wants("brands")) {
    await write("brands", planBrandRows(prodBrands));
  }

  // --- 4. Remap ------------------------------------------------------------
  const stagingBrandRefs = await readByValues<BrandRef>(
    staging.client,
    "brands",
    "id,slug",
    "slug",
    slugs,
    ["slug"],
  );
  const remap = planBrandIdRemap(
    prodBrands.map((row) => ({ id: String(row.id), slug: String(row.slug) })),
    stagingBrandRefs,
  );
  if (remap.missing.length > 0) {
    if (!args.dryRun) {
      throw new Error(
        `${remap.missing.length} selected brand(s) are absent from staging after the brands upsert: ${remap.missing.slice(0, 10).join(", ")}`,
      );
    }
    // A dry run never inserted them, so they cannot be there. Placeholders let
    // the child planners run and report their real row counts.
    console.log(
      `[dry-run] ${remap.missing.length} brand(s) would be created in staging`,
    );
    remap.missing.forEach((slug, index) => {
      const brand = prodBrands.find((row) => String(row.slug) === slug);
      if (brand) remap.map.set(String(brand.id), dryRunPlaceholderId(index));
    });
  }

  // --- 5-8. Brand-keyed children ------------------------------------------
  if (wants("brand_images")) {
    const imagePlan = planImageUpserts(prodImages, remap.map);
    assertMapped("brand_images", imagePlan.unmapped);
    await write("brand_images", imagePlan.withSourceUrl);
    // Null source_url never conflicts with null in a unique index, so these
    // rows go through their primary key instead — see planImageUpserts.
    await write("brand_images", imagePlan.withoutSourceUrl, "id");
  }
  if (wants("brand_faq_entries")) {
    const plan = planChildRows("brand_faq_entries", prodFaq, remap.map);
    assertMapped("brand_faq_entries", plan.unmapped);
    await write("brand_faq_entries", plan.rows);
  }
  if (wants("brand_channels")) {
    const plan = planChildRows("brand_channels", prodChannels, remap.map);
    assertMapped("brand_channels", plan.unmapped);
    await write("brand_channels", plan.rows);
  }
  if (wants("event_brands")) {
    const plan = planChildRows("event_brands", prodEventBrands, remap.map);
    assertMapped("event_brands", plan.unmapped);
    await write("event_brands", plan.rows);
  }

  // --- 9. Slug redirects ---------------------------------------------------
  if (wants("brand_slug_redirects")) {
    const oldSlugs = prodRedirects.map((row) => String(row.old_slug));
    const liveStagingSlugs =
      oldSlugs.length > 0
        ? (
            await readByValues<{ slug: string }>(
              staging.client,
              "brands",
              "slug",
              "slug",
              oldSlugs,
              ["slug"],
            )
          ).map((row) => row.slug)
        : [];
    const plan = planSlugRedirects(prodRedirects, slugs, liveStagingSlugs);
    if (plan.skippedOldSlugs.length > 0) {
      console.warn(
        `Skipped ${plan.skippedOldSlugs.length} redirect(s) whose old_slug is a live staging brand: ${plan.skippedOldSlugs.join(", ")}`,
      );
    }
    await write("brand_slug_redirects", plan.rows);
  }

  // --- 10. MIT registry ----------------------------------------------------
  if (wants("mit_registry")) {
    await write(
      "mit_registry",
      prodRegistry.map((row) => {
        assertKnownColumns("mit_registry", row);
        return applyPolicy("mit_registry", row);
      }),
    );
  }

  // --- 11. Storage objects -------------------------------------------------
  // Gated on brand_images: it holds all but a handful of the referenced keys,
  // and `brands.hero_image_storage_path` is a denormalized copy of one of its
  // rows rather than an independent object.
  let storage: StorageCopyReport | null = null;
  if (wants("brand_images")) {
    const keyPlan = planStorageKeys({
      brands: prodBrands,
      brand_images: prodImages,
      events: prodEvents,
      event_exhibitors: prodExhibitors,
    });
    if (keyPlan.skippedByPrefix.length > 0) {
      const prefixes = tally(
        keyPlan.skippedByPrefix.map((key) => `${key.split("/").at(0) ?? key}/`),
      );
      console.log(
        `Storage: not copying ${keyPlan.skippedByPrefix.length} key(s) outside ${SYNCED_STORAGE_PREFIXES.join(", ")} (${[
          ...prefixes,
        ]
          .map(([prefix, count]) => `${prefix}=${count}`)
          .join(" ")})`,
      );
    }
    storage = await syncStorageObjects({
      production: production.client,
      staging: staging.client,
      keys: keyPlan.keys,
      dryRun: args.dryRun,
    });
    console.log(
      args.dryRun
        ? `[dry-run] storage: would copy ${storage.planned - storage.skippedPresent} object(s), ${storage.skippedPresent} already present`
        : `  storage: ${storage.copied} copied, ${storage.skippedPresent} already present, ${storage.failed} failed, ${storage.rejectedByBucket} refused by bucket mime policy (of ${storage.planned})`,
    );
    for (const message of storage.errors) console.error(`    ${message}`);
  }

  // --- Report --------------------------------------------------------------
  if (args.dryRun) {
    console.log("\n[dry-run] planned writes:");
    for (const batch of plannedBatches) {
      if (batch.rows.length === 0) continue;
      const existing = await readExistingForDiff(
        staging.client,
        batch.table,
        batch.rows,
      );
      const diff = planWriteDiff(
        batch.rows,
        existing,
        batch.onConflict.split(","),
      );
      console.log(
        `  ${batch.table} (on ${batch.onConflict}): insert ${diff.wouldInsert}, update ${diff.wouldUpdate}, unchanged ${diff.unchanged}`,
      );
    }
    console.log(
      `\n[dry-run] staging writes blocked: ${staging.blocked.length}. Nothing was written.`,
    );
    assertNoProductionWrites(production.blocked);
    printRunNotes();
    return;
  }

  for (const table of planCopyOrder()) {
    const plannedRows = planned.get(table) ?? 0;
    const copiedRows = copied.get(table) ?? 0;
    if (plannedRows === 0 && copiedRows === 0) continue;
    console.log(`  ${table}: ${copiedRows}/${plannedRows} row(s)`);
    if (copiedRows !== plannedRows) {
      throw new Error(
        `${table}: copied ${copiedRows} of ${plannedRows} planned rows`,
      );
    }
  }

  await assertPostConditions({
    staging: staging.client,
    production,
    slugs,
    before,
    remap: remap.map,
    checkImages: wants("brand_images"),
    checkFaq: wants("brand_faq_entries"),
  });

  printRunNotes();

  // Last, so the row report and the run notes are on screen first: a storage
  // failure is repaired by re-running this same command, and the operator
  // needs to see what did land before being told to run it again.
  if (storage && storage.failed > 0) {
    throw new Error(
      `${storage.failed} of ${storage.planned} storage object(s) did not copy. The stage is idempotent — re-run \`pnpm db:sync:staging\` to retry only the missing ones.`,
    );
  }
}

function assertMapped(table: string, unmapped: string[]): void {
  if (unmapped.length === 0) return;
  throw new Error(
    `${table}: ${unmapped.length} row(s) reference production brand ids with no staging counterpart (${[...new Set(unmapped)].slice(0, 5).join(", ")})`,
  );
}

async function assertPostConditions(input: {
  staging: StagingClient;
  production: { blocked: BlockedWrite[] };
  slugs: string[];
  before: Map<string, number>;
  remap: Map<string, string>;
  checkImages: boolean;
  checkFaq: boolean;
}): Promise<void> {
  const { staging, production, slugs, before, remap } = input;

  assertNoProductionWrites(production.blocked);

  const brands = await readByValues<Row>(
    staging,
    "brands",
    "id,slug,status,description,model_faq_count",
    "slug",
    slugs,
    ["slug"],
  );
  const bySlug = new Map(brands.map((row) => [String(row.slug), row]));
  for (const slug of slugs) {
    const brand = bySlug.get(slug);
    if (!brand)
      throw new Error(`Post-condition: ${slug} is missing in staging`);
    if (brand.status !== "approved") {
      throw new Error(
        `Post-condition: ${slug} has status ${String(brand.status)}, expected approved`,
      );
    }
    if (brand.description === FIXTURE_DESCRIPTION) {
      throw new Error(
        `Post-condition: ${slug} still holds the staging fixture description. Re-run db:seed:staging before this sync, not after.`,
      );
    }
  }

  for (const table of COUNTED_TABLES) {
    const after = await countRows(staging, table);
    const previous = before.get(table) ?? 0;
    if (after < previous) {
      throw new Error(
        `Post-condition: staging ${table} fell from ${previous} to ${after}. This sync is additive; something deleted rows.`,
      );
    }
  }

  const stagingIds = [...remap.values()];
  if (input.checkImages) {
    const images = await readByValues<{ brand_id: string }>(
      staging,
      "brand_images",
      "brand_id",
      "brand_id",
      stagingIds,
      ["brand_id"],
    );
    const counts = tally(images.map((row) => row.brand_id));
    const empty = brands.filter(
      (row) => (counts.get(String(row.id)) ?? 0) === 0,
    );
    if (empty.length > 0) {
      throw new Error(
        `Post-condition: ${empty.length} brand(s) have no images in staging (${empty
          .slice(0, 5)
          .map((row) => String(row.slug))
          .join(", ")})`,
      );
    }
  }

  if (input.checkFaq) {
    const faq = await readByValues<{ brand_id: string }>(
      staging,
      "brand_faq_entries",
      "brand_id",
      "brand_id",
      stagingIds,
      ["brand_id"],
    );
    const counts = tally(faq.map((row) => row.brand_id));
    for (const brand of brands) {
      const expected = counts.get(String(brand.id)) ?? 0;
      if (Number(brand.model_faq_count ?? 0) !== expected) {
        throw new Error(
          `Post-condition: ${String(brand.slug)} reports model_faq_count ${String(brand.model_faq_count)} but holds ${expected} FAQ entries. The sync_brand_model_faq_count trigger did not fire.`,
        );
      }
    }
  }
}

function printRunNotes(): void {
  console.log(
    [
      "",
      "Run order: `pnpm db:seed:staging` FIRST, then `pnpm db:sync:staging`.",
      "The reverse order lets the fixture overwrite copied brand content with",
      "its placeholder description.",
      "",
      "Images render through the same-origin /i/ proxy, which reads THIS",
      "project's own bucket (DEV-1551). The sync therefore copies the objects",
      "too, under `brands/` AND `submissions/`. Copying the bytes is not enough",
      "on its own: the proxy deny-lists a `submissions/` key whether the bytes",
      "are there or not, so run",
      "`pnpm tsx scripts/promote-submission-images.ts promote --live` against",
      "STAGING afterwards to rewrite those rows to `brands/` keys. Promotion is",
      "a server-side copy inside one bucket, which is why it needs the source",
      "bytes here first. Verify with `pnpm check:image-resolvability`.",
      "",
      "Re-run this sync to repair a gallery with missing bytes; it copies only",
      "what staging lacks. `event-exhibitors/` and `events/` keys are NOT",
      "copied — those surfaces stay image-blind on staging.",
    ].join("\n"),
  );
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const [subcommand, ...rest] = process.argv.slice(2);
  if (subcommand === "select") return runSelect(rest);
  if (subcommand === "sync") return runSync(rest);
  throw new Error(
    `Unknown subcommand ${JSON.stringify(subcommand ?? "")}; expected "select" or "sync"`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
