-- DEV-1525 — the material axis moves from zh-TW labels to English slugs.
--
-- ---------------------------------------------------------------------------
-- WHY
-- ---------------------------------------------------------------------------
--
-- `brands.material` was the last taxonomy axis storing a Chinese label as its
-- identifier. DEV-1510 converted `brands.subcategories` and `brands.category` to
-- slugs; material stayed on 陶瓷 / 木 / 織品, which meant the stored value, the
-- CHECK vocabulary and the `?material=` URL segment were all one zh-TW string.
-- After this migration the column stores `ceramic`, and the Chinese term is a
-- display-only field on the `MATERIALS` entry in
-- `src/lib/taxonomy/ontology.ts` — the same shape every other axis already has.
--
-- ---------------------------------------------------------------------------
-- ORDER OF OPERATIONS
-- ---------------------------------------------------------------------------
--
-- Both CHECKs are dropped BEFORE the conversion and re-added after it. A
-- narrowing CHECK validates every existing row as it is added, so re-adding the
-- slug version is itself the proof that the conversion left no zh-TW term
-- behind; there is no window in which a row can satisfy neither vocabulary,
-- because the whole file is one transaction.
--
-- The mapping is a bijection over twelve pairs, and its write order matches the
-- `MATERIALS` array element for element. `sameMaterialSet` in the corrections
-- service compares sets, but an ordering that disagreed with the ontology would
-- still make every admin diff read as a pending change.
--
-- ---------------------------------------------------------------------------
-- TRIGGERS
-- ---------------------------------------------------------------------------
--
-- `brands_updated_at` is suppressed for the conversion, the same treatment
-- 20260820140000:129 gave the backfill that wrote these values. A vocabulary
-- migration changes how a fact is spelled, not the fact — a moved `updated_at`
-- would churn sitemap `lastmod` for every brand carrying a material.
-- `brands_search_vector_trigger` does not list `material`, so no search
-- document is rebuilt.
--
-- ---------------------------------------------------------------------------
-- `taxonomy_terms` IS RE-SEEDED IN FULL
-- ---------------------------------------------------------------------------
--
-- The seed block below is generated by `scripts/generate-taxonomy-terms.ts` and
-- carries all 200 rows, not a material-only delta: the generator rewrites
-- whatever sits between its markers, and the parity test compares the parsed
-- block against the whole ontology.

begin;

-- 1. Precondition: both CHECKs must still hold the zh vocabulary.
do $migration$
declare
  v_expected constant text := 'CHECK ((material <@ ARRAY[''陶瓷''::text, ''木''::text, '
    || '''織品''::text, ''玻璃''::text, ''金屬''::text, ''竹''::text, ''羊毛''::text, '
    || '''皮革''::text, ''紙''::text, ''石''::text, ''藤''::text, ''漆''::text]))';
  v_name text;
  v_actual text;
begin
  foreach v_name in array array['brands_material_check', 'curated_products_material_check'] loop
    select pg_get_constraintdef(oid) into v_actual from pg_constraint where conname = v_name;
    if v_actual is distinct from v_expected then
      raise exception 'DEV-1525 % is %, expected the zh vocabulary',
        v_name, coalesce(v_actual, '<missing>') using errcode = 'P0001';
    end if;
  end loop;
end
$migration$;

alter table public.brands drop constraint brands_material_check;
alter table public.curated_products drop constraint curated_products_material_check;

-- 2. Convert. `brands_updated_at` is suppressed so a vocabulary migration does not
--    read as an editorial edit (same treatment as 20260820140000:129).
create temporary table dev1525_material_snapshot on commit drop as
select id, material from public.brands where cardinality(material) > 0;

alter table public.brands disable trigger brands_updated_at;

update public.brands as b
set material = (
  select coalesce(array_agg(mapping.slug order by mapping.rank), '{}')
  from unnest(b.material) as term
  join (values
    ('陶瓷','ceramic',1), ('木','wood',2),      ('織品','textile',3), ('玻璃','glass',4),
    ('金屬','metal',5),   ('竹','bamboo',6),    ('羊毛','wool',7),    ('皮革','leather',8),
    ('紙','paper',9),     ('石','stone',10),    ('藤','rattan',11),   ('漆','lacquer',12)
  ) as mapping(label, slug, rank) on mapping.label = term
)
where cardinality(b.material) > 0;

alter table public.brands enable trigger brands_updated_at;

-- 3. Post-conditions: nothing lost, nothing invented.
do $migration$
declare v_before bigint; v_after bigint; v_bad text;
begin
  select count(*) into v_before from dev1525_material_snapshot;
  select count(*) into v_after from public.brands where cardinality(material) > 0;
  if v_before <> v_after then
    raise exception 'DEV-1525 brands carrying material went % -> %', v_before, v_after
      using errcode = 'P0001';
  end if;

  select string_agg(s.id::text, ', ') into v_bad
    from dev1525_material_snapshot s
    join public.brands b on b.id = s.id
   where cardinality(b.material) <> cardinality(s.material);
  if v_bad is not null then
    raise exception 'DEV-1525 material cardinality changed for brand(s): %', v_bad
      using errcode = 'P0001';
  end if;

  select string_agg(distinct m, ', ') into v_bad
    from public.brands, unnest(material) m
   where m <> all (array['ceramic','wood','textile','glass','metal','bamboo',
                         'wool','leather','paper','stone','rattan','lacquer']);
  if v_bad is not null then
    raise exception 'DEV-1525 unmapped material value(s) survived: %', v_bad
      using errcode = 'P0001';
  end if;

  if exists (select 1 from public.curated_products where cardinality(material) > 0) then
    raise exception 'DEV-1525 curated_products.material is no longer empty; add a conversion arm'
      using errcode = 'P0001';
  end if;
end
$migration$;

-- 4. Install the slug CHECKs. `add constraint` validates existing rows as it runs.
alter table public.brands add constraint brands_material_check check (
  material <@ array['ceramic','wood','textile','glass','metal','bamboo',
                    'wool','leather','paper','stone','rattan','lacquer']::text[]);
alter table public.curated_products add constraint curated_products_material_check check (
  material <@ array['ceramic','wood','textile','glass','metal','bamboo',
                    'wool','leather','paper','stone','rattan','lacquer']::text[]);

comment on column public.brands.material is
  'Materials the brand works in, e.g. {ceramic,wood}. Closed 12-slug vocabulary, CHECK-constrained by brands_material_check; mirrored by MATERIALS in src/lib/taxonomy/ontology.ts.';
comment on column public.curated_products.material is
  'Materials this product is made of. Closed 12-slug vocabulary, CHECK-constrained by curated_products_material_check; mirrored by MATERIALS in src/lib/taxonomy/ontology.ts.';

-- 5. Re-seed taxonomy_terms IN FULL. Safe: no triggers, no inbound FKs.
delete from public.taxonomy_terms;
-- >>> generated by scripts/generate-taxonomy-terms.ts - do not edit by hand
insert into public.taxonomy_terms (axis, slug, name_zh, name_en) values
  ('l1', 'fashion', '服飾鞋履', 'Fashion & Apparel'),
  ('l1', 'bags-accessories', '包袋配件', 'Bags & Accessories'),
  ('l1', 'jewelry', '飾品珠寶', 'Jewelry'),
  ('l1', 'beauty', '美妝保養', 'Beauty & Personal Care'),
  ('l1', 'home', '居家生活', 'Home & Living'),
  ('l1', 'food-drink', '食品飲料', 'Food & Beverage'),
  ('l1', 'crafts', '工藝文創', 'Crafts & Art'),
  ('l1', 'stationery', '文具設計', 'Stationery & Design'),
  ('l1', 'tech', '3C科技', 'Tech & Electronics'),
  ('l1', 'outdoor', '戶外露營', 'Outdoor & Camping'),
  ('l1', 'fitness', '運動健身', 'Sports & Fitness'),
  ('l1', 'kids', '母嬰童', 'Kids & Baby'),
  ('l1', 'pets', '寵物', 'Pets'),
  ('l2', 'tops-and-tshirts', '上衣・T恤', 'Tops & T-shirts'),
  ('l2', 'dresses', '洋裝', 'Dresses'),
  ('l2', 'skirts', '裙裝', 'Skirts'),
  ('l2', 'pants', '褲裝', 'Pants'),
  ('l2', 'outerwear', '外套', 'Outerwear'),
  ('l2', 'underwear-and-intimates', '貼身衣物', 'Underwear & Intimates'),
  ('l2', 'loungewear', '睡衣・居家服', 'Loungewear'),
  ('l2', 'swimwear', '泳裝', 'Swimwear'),
  ('l2', 'performance-apparel', '機能服飾', 'Performance Apparel'),
  ('l2', 'activewear', '運動服飾', 'Activewear'),
  ('l2', 'socks', '襪子', 'Socks'),
  ('l2', 'casual-shoes', '休閒鞋', 'Casual Shoes'),
  ('l2', 'leather-shoes', '皮鞋', 'Leather Shoes'),
  ('l2', 'heels', '高跟鞋', 'Heels'),
  ('l2', 'sandals-and-slippers', '涼鞋・拖鞋', 'Sandals & Slippers'),
  ('l2', 'boots', '靴子', 'Boots'),
  ('l2', 'backpacks', '後背包', 'Backpacks'),
  ('l2', 'tote-bags', '托特包', 'Tote Bags'),
  ('l2', 'crossbody-bags', '斜背包', 'Crossbody Bags'),
  ('l2', 'handbags', '手提包', 'Handbags'),
  ('l2', 'clutches', '手拿包', 'Clutches'),
  ('l2', 'clasp-frame-bags', '口金包', 'Clasp-Frame Bags'),
  ('l2', 'bucket-bags', '水桶包', 'Bucket Bags'),
  ('l2', 'belt-and-sling-bags', '腰包・胸包', 'Belt & Sling Bags'),
  ('l2', 'eco-and-shopping-bags', '環保袋・購物袋', 'Eco & Shopping Bags'),
  ('l2', 'wallets', '皮夾・錢包', 'Wallets'),
  ('l2', 'coin-purses', '零錢包', 'Coin Purses'),
  ('l2', 'card-holders', '卡夾・證件套', 'Card Holders'),
  ('l2', 'storage-pouches', '收納包', 'Storage Pouches'),
  ('l2', 'cosmetic-bags', '化妝包', 'Cosmetic Bags'),
  ('l2', 'laptop-bags', '筆電包', 'Laptop Bags'),
  ('l2', 'camera-bags', '相機包', 'Camera Bags'),
  ('l2', 'luggage-and-travel', '行李箱・旅行袋', 'Luggage & Travel'),
  ('l2', 'hats', '帽子', 'Hats'),
  ('l2', 'scarves-and-shawls', '圍巾・披肩', 'Scarves & Shawls'),
  ('l2', 'eyewear', '眼鏡・太陽眼鏡', 'Eyewear'),
  ('l2', 'watches', '手錶', 'Watches'),
  ('l2', 'keychains', '鑰匙圈', 'Keychains'),
  ('l2', 'charms', '吊飾', 'Charms'),
  ('l2', 'phone-bags', '手機袋', 'Phone Bags'),
  ('l2', 'phone-straps', '手機背帶', 'Phone Straps'),
  ('l2', 'umbrellas', '雨傘・陽傘', 'Umbrellas'),
  ('l2', 'gloves', '手套', 'Gloves & Mittens'),
  ('l2', 'earrings', '耳環', 'Earrings'),
  ('l2', 'necklaces', '項鍊', 'Necklaces'),
  ('l2', 'rings', '戒指', 'Rings'),
  ('l2', 'bracelets-and-bangles', '手鍊・手環', 'Bracelets & Bangles'),
  ('l2', 'wedding-and-couple-rings', '婚戒・對戒', 'Wedding & Couple Rings'),
  ('l2', 'brooches', '胸針', 'Brooches'),
  ('l2', 'hair-accessories', '髮飾', 'Hair Accessories'),
  ('l2', 'cufflinks-and-tie-clips', '袖扣・領帶夾', 'Cufflinks & Tie Clips'),
  ('l2', 'handmade-soap', '手工皂', 'Handmade Soap'),
  ('l2', 'skincare', '臉部保養', 'Skincare'),
  ('l2', 'face-masks', '面膜', 'Face Masks'),
  ('l2', 'body-care', '身體保養', 'Body Care'),
  ('l2', 'bath-and-shower', '洗沐清潔', 'Bath & Shower'),
  ('l2', 'hair-care', '髮品・頭皮護理', 'Hair Care'),
  ('l2', 'makeup', '彩妝', 'Makeup'),
  ('l2', 'sun-care', '防曬', 'Sun Care'),
  ('l2', 'fragrance', '香水', 'Fragrance'),
  ('l2', 'essential-oils-and-hydrosols', '精油・純露', 'Essential Oils & Hydrosols'),
  ('l2', 'oral-care', '口腔護理', 'Oral Care'),
  ('l2', 'protective-sprays', '防蚊・止汗噴霧', 'Protective Sprays'),
  ('l2', 'feminine-care', '生理用品', 'Feminine Care'),
  ('l2', 'beauty-tools', '美妝工具・儀器', 'Beauty Tools & Devices'),
  ('l2', 'bedding', '寢具', 'Bedding'),
  ('l2', 'mattresses', '床墊', 'Mattresses'),
  ('l2', 'furniture', '家具', 'Furniture'),
  ('l2', 'kids-furniture', '兒童家具', 'Kids'' Furniture'),
  ('l2', 'lighting', '燈飾', 'Lighting'),
  ('l2', 'clocks', '時鐘', 'Clocks'),
  ('l2', 'home-decor', '居家擺飾', 'Home Décor'),
  ('l2', 'towels', '毛巾', 'Towels'),
  ('l2', 'home-textiles', '居家織品', 'Home Textiles'),
  ('l2', 'rugs-and-mats', '地墊・地毯', 'Rugs & Mats'),
  ('l2', 'tableware', '餐具', 'Tableware'),
  ('l2', 'tea-and-coffee-ware', '茶具・咖啡器具', 'Tea & Coffee Ware'),
  ('l2', 'cookware', '鍋具', 'Cookware'),
  ('l2', 'tumblers-and-bottles', '隨行杯・保溫瓶', 'Tumblers & Bottles'),
  ('l2', 'reusable-utensils-and-straws', '環保餐具・吸管', 'Reusable Utensils & Straws'),
  ('l2', 'storage', '收納用品', 'Storage'),
  ('l2', 'cleaning', '清潔用品', 'Cleaning'),
  ('l2', 'home-appliances', '生活家電', 'Home Appliances'),
  ('l2', 'home-fragrance', '居家香氛', 'Home Fragrance'),
  ('l2', 'candles', '蠟燭', 'Candles'),
  ('l2', 'floral-arrangements', '花藝', 'Floral Arrangements'),
  ('l2', 'plants', '植栽', 'Plants'),
  ('l2', 'curtains', '窗簾', 'Curtains'),
  ('l2', 'bath-accessories', '衛浴用品', 'Bath Accessories'),
  ('l2', 'hand-tools', '手工具', 'Hand Tools'),
  ('l2', 'pest-control', '防蟲用品', 'Pest Control'),
  ('l2', 'figurines-and-plush', '公仔・玩偶', 'Figurines & Plush'),
  ('l2', 'tea', '茶葉', 'Tea'),
  ('l2', 'tea-bags', '茶包', 'Tea Bags'),
  ('l2', 'tea-drinks', '茶飲', 'Tea Drinks'),
  ('l2', 'coffee', '咖啡', 'Coffee'),
  ('l2', 'chocolate-and-cacao', '巧克力・可可', 'Chocolate & Cacao'),
  ('l2', 'honey', '蜂蜜', 'Honey'),
  ('l2', 'jams-and-spreads', '果醬・抹醬', 'Jams & Spreads'),
  ('l2', 'desserts-and-pastries', '甜點・糕點', 'Desserts & Pastries'),
  ('l2', 'cookies-and-rice-crackers', '餅乾・米餅', 'Cookies & Rice Crackers'),
  ('l2', 'snacks', '零食', 'Snacks'),
  ('l2', 'dried-fruits', '果乾', 'Dried Fruits'),
  ('l2', 'rice-and-grains', '米・雜糧', 'Rice & Grains'),
  ('l2', 'fresh-produce', '生鮮蔬果', 'Fresh Produce'),
  ('l2', 'dairy', '乳製品', 'Dairy'),
  ('l2', 'milk-powder', '奶粉', 'Milk Powder'),
  ('l2', 'alcohol', '酒類', 'Alcohol'),
  ('l2', 'beverages', '飲品', 'Beverages'),
  ('l2', 'seasonings-and-sauces', '調味料・醬料', 'Seasonings & Sauces'),
  ('l2', 'ready-meals', '料理包・加工食品', 'Ready Meals'),
  ('l2', 'supplements', '保健食品', 'Supplements'),
  ('l2', 'ceramics', '陶瓷・陶藝', 'Ceramics'),
  ('l2', 'woodcraft', '木藝・木作', 'Woodcraft'),
  ('l2', 'metalwork', '金工', 'Metalwork'),
  ('l2', 'bamboo-craft', '竹編・竹藝', 'Bamboo Craft'),
  ('l2', 'glass-art', '玻璃・琉璃', 'Glass Art'),
  ('l2', 'natural-dyeing', '藍染・植物染', 'Natural Dyeing'),
  ('l2', 'leather-craft', '皮革工藝', 'Leather Craft'),
  ('l2', 'embroidery', '刺繡', 'Embroidery'),
  ('l2', 'needle-felting', '羊毛氈', 'Needle Felting'),
  ('l2', 'weaving-and-crochet', '編織・鉤織', 'Weaving & Crochet'),
  ('l2', 'illustration-and-art', '插畫・畫作', 'Illustration & Art'),
  ('l2', 'dried-flowers-and-floral-design', '乾燥花・花藝設計', 'Dried Flowers & Floral Design'),
  ('l2', 'journals-and-notebooks', '手帳・筆記本', 'Journals & Notebooks'),
  ('l2', 'washi-tape', '紙膠帶', 'Washi Tape'),
  ('l2', 'stickers', '貼紙', 'Stickers'),
  ('l2', 'stamps-and-seals', '印章', 'Stamps & Seals'),
  ('l2', 'cards-and-postcards', '卡片・明信片', 'Cards & Postcards'),
  ('l2', 'pens-and-writing', '筆具', 'Pens & Writing'),
  ('l2', 'calendars', '月曆・日曆', 'Calendars'),
  ('l2', 'desk-mats', '桌墊', 'Desk Mats'),
  ('l2', 'paper-goods', '紙品', 'Paper Goods'),
  ('l2', 'desk-organization', '文具收納', 'Desk Organization'),
  ('l2', 'bookmarks', '書籤', 'Bookmarks'),
  ('l2', 'craft-kits-and-supplies', '手作材料・工具', 'Craft Kits & Supplies'),
  ('l2', 'phone-cases', '手機殼', 'Phone Cases'),
  ('l2', 'device-sleeves', '保護套・皮套', 'Device Sleeves'),
  ('l2', 'chargers-and-cables', '充電器・充電線', 'Chargers & Cables'),
  ('l2', 'power-banks', '行動電源', 'Power Banks'),
  ('l2', 'wireless-charging', '無線充電', 'Wireless Charging'),
  ('l2', 'earphones-and-headphones', '耳機', 'Earphones & Headphones'),
  ('l2', 'speakers', '藍牙喇叭', 'Speakers'),
  ('l2', 'stands-and-mounts', '支架', 'Stands & Mounts'),
  ('l2', 'storage-devices', '儲存裝置', 'Storage Devices'),
  ('l2', 'security-cameras', '攝影機', 'Security Cameras'),
  ('l2', 'smart-doorbells', '智慧門鈴', 'Smart Doorbells'),
  ('l2', 'hiking-and-camping-gear', '登山・露營用品', 'Hiking & Camping Gear'),
  ('l2', 'picnic-supplies', '野餐用品', 'Picnic Supplies'),
  ('l2', 'wetsuits-and-water-sports', '防寒衣・水上運動', 'Wetsuits & Water Sports'),
  ('l2', 'cycling-and-riding', '自行車・騎士用品', 'Cycling & Riding'),
  ('l2', 'helmets', '安全帽', 'Helmets'),
  ('l2', 'outdoor-accessories', '戶外配件', 'Outdoor Accessories'),
  ('l2', 'yoga-gear', '瑜珈用品', 'Yoga Gear'),
  ('l2', 'fitness-equipment', '健身器材', 'Fitness Equipment'),
  ('l2', 'massage-and-recovery', '按摩・放鬆', 'Massage & Recovery'),
  ('l2', 'protective-gear', '護具', 'Protective Gear'),
  ('l2', 'care-and-mobility-aids', '照護輔具', 'Care & Mobility Aids'),
  ('l2', 'kids-clothing', '童裝', 'Kids'' Clothing'),
  ('l2', 'family-matching', '親子裝', 'Family Matching'),
  ('l2', 'baby-clothing', '嬰幼兒服飾', 'Baby Clothing'),
  ('l2', 'baby-bedding', '嬰幼兒寢具', 'Baby Bedding'),
  ('l2', 'bibs-and-muslin', '圍兜・紗布巾', 'Bibs & Muslin'),
  ('l2', 'kids-tableware', '兒童餐具', 'Kids'' Tableware'),
  ('l2', 'toys', '玩具', 'Toys'),
  ('l2', 'learning-aids', '教具', 'Learning Aids'),
  ('l2', 'play-mats-and-fences', '遊戲地墊・圍欄', 'Play Mats & Fences'),
  ('l2', 'parenting-essentials', '育兒用品', 'Parenting Essentials'),
  ('l2', 'pet-food', '寵物食品', 'Pet Food'),
  ('l2', 'pet-treats', '寵物零食', 'Pet Treats'),
  ('l2', 'pet-supplements', '寵物保健', 'Pet Supplements'),
  ('l2', 'pet-apparel', '寵物服飾・配件', 'Pet Apparel'),
  ('l2', 'pet-beds-and-scratchers', '貓抓板・寵物床窩', 'Pet Beds & Scratchers'),
  ('l2', 'pet-grooming', '寵物清潔・美容', 'Pet Grooming'),
  ('l2', 'pet-supplies', '寵物生活用品', 'Pet Supplies'),
  ('material', 'ceramic', '陶瓷', 'Ceramic'),
  ('material', 'wood', '木', 'Wood'),
  ('material', 'textile', '織品', 'Textile'),
  ('material', 'glass', '玻璃', 'Glass'),
  ('material', 'metal', '金屬', 'Metal'),
  ('material', 'bamboo', '竹', 'Bamboo'),
  ('material', 'wool', '羊毛', 'Wool'),
  ('material', 'leather', '皮革', 'Leather'),
  ('material', 'paper', '紙', 'Paper'),
  ('material', 'stone', '石', 'Stone'),
  ('material', 'rattan', '藤', 'Rattan'),
  ('material', 'lacquer', '漆', 'Lacquer');

do $seed$
declare
  v_expected constant jsonb := '{"l1":13,"l2":175,"material":12}'::jsonb;
  v_actual jsonb;
begin
  select coalesce(jsonb_object_agg(counted.axis, counted.total), '{}'::jsonb)
    into v_actual
    from (
      select axis, count(*) as total
      from public.taxonomy_terms
      group by axis
    ) as counted;

  if v_actual is distinct from v_expected then
    raise exception
      'DEV-1510 taxonomy_terms axis counts are %, expected %',
      v_actual, v_expected
      using errcode = 'P0001';
  end if;
end
$seed$;
-- <<< end generated block

-- 6. Widened closing contract: no slug echoes its label, on ANY axis now.
do $migration$
declare v_offenders text;
begin
  select string_agg(t.axis || ':' || t.slug, ', ' order by t.axis || ':' || t.slug)
    into v_offenders from public.taxonomy_terms as t where t.name_zh = t.slug;
  if v_offenders is not null then
    raise exception 'DEV-1525 taxonomy_terms row(s) carry a slug as their zh-TW label: %',
      v_offenders using errcode = 'P0001';
  end if;
end
$migration$;

commit;
