-- `taxonomy_terms` — the SQL-side mirror of src/lib/taxonomy/ontology.ts
-- (DEV-1510, Task 6).
--
-- WHY THE TABLE EXISTS
-- ---------------------------------------------------------------------------
--
-- DEV-1510 changes `brands.subcategories` from zh-TW labels to English slugs.
-- The moment it does, the `cjk_bigrams` weight-C arm of
-- `brands_search_document` (20260809100000_cjk_bigram_search.sql:107-113) has
-- no CJK text left to tokenise, and `後背包` stops matching a brand tagged
-- `backpacks`. Nothing asserts a ranking weight, so that loss is silent: the
-- slug filter keeps working, the row just disappears from search.
--
-- Task 7 rewrites the search functions to expand each stored slug back to its
-- `name_zh` before indexing. This table is what they expand through.
--
-- WHY IT IS GENERATED
-- ---------------------------------------------------------------------------
--
-- The seed block below is emitted by `scripts/generate-taxonomy-terms.ts`,
-- which IMPORTS the ontology module rather than parsing it. A hand-written
-- copy of a 200-term vocabulary drifts on the first rename, and a drifted row
-- is undetectable at runtime — the label simply stops being indexed. The parity
-- test (`src/lib/taxonomy/__tests__/taxonomy-terms-parity.test.ts`) compares
-- ontology to committed SQL, so it gates CI with no database.
--
-- The generator is deliberately not a regex. `scripts/model-ab/report.py:19`
-- reads `ontology.ts` with a Python regex and under-counts silently; the same
-- shape reports 172 of the 175 L2 nodes because three entries wrap onto extra
-- lines. Task 18 removes that regex for the same reason.
--
-- WHAT IT REPLACES, AND WHAT IT DOES NOT
-- ---------------------------------------------------------------------------
--
-- It replaces `subcategory_translations` (20260819090000:323-333), a
-- label-keyed cache the enrichment phase writes into. It does NOT replace
-- `product_tag_translations` — the DEV-1503 contract migration already dropped
-- that one (20260819090000:839).
--
-- `subcategory_translations` is NOT dropped here. The search trigger and
-- `canonicalize_subcategory_translations` still read it at this point in the
-- ledger; Task 7 (20260820110000_search_expands_slugs.sql) inverts both and
-- drops the table in the same transaction that stops reading it. Dropping it
-- one migration early would take the enrichment RPC down between deploys.
--
-- AXES
-- ---------------------------------------------------------------------------
--
--   l1        13 rows   slug = the L1 category slug
--   l2       175 rows   slug = the L2 subcategory slug (what `subcategories`
--                       stores after Task 9)
--   material  12 rows   slug = the zh-TW term itself, because that is what
--                       `brands.material` stores and what `?material=` carries
--
-- `crafts` and its 12 L2s are present on purpose. DEV-1507 retires them;
-- DEV-1510 does not.
--
-- Composite primary key on (axis, slug): an L1 slug and an L2 slug are drawn
-- from different namespaces and a future collision must not be a load error.

begin;

create table public.taxonomy_terms (
  axis text not null,
  slug text not null,
  name_zh text not null,
  name_en text not null,
  constraint taxonomy_terms_pkey primary key (axis, slug),
  constraint taxonomy_terms_axis_check check (axis in ('l1', 'l2', 'material')),
  constraint taxonomy_terms_slug_check check (slug <> ''),
  constraint taxonomy_terms_name_zh_check check (name_zh <> ''),
  constraint taxonomy_terms_name_en_check check (name_en <> '')
);

comment on table public.taxonomy_terms is
  'Generated mirror of src/lib/taxonomy/ontology.ts. Regenerate with '
  '`pnpm exec tsx scripts/generate-taxonomy-terms.ts --write`; never edit by '
  'hand. Read by brands_search_document to expand stored slugs to zh-TW labels '
  'before tokenising.';

-- Grants mirror `subcategory_translations` (20260819090000:328-333): RLS on
-- with a read policy, but no anon/authenticated grant. Only `postgres` and
-- `service_role` write `public.brands` (checked live: those are the sole
-- INSERT/UPDATE grantees), so those are the only roles whose search-vector
-- trigger ever needs to read this table. Widening the grant would publish a
-- new PostgREST collection for no caller.
alter table public.taxonomy_terms enable row level security;
create policy taxonomy_terms_public_read
  on public.taxonomy_terms for select
  using (true);
revoke all on table public.taxonomy_terms from public, anon, authenticated;
grant all on table public.taxonomy_terms to postgres, service_role;

-- >>> generated by scripts/generate-taxonomy-terms.ts - do not edit by hand
insert into public.taxonomy_terms (axis, slug, name_zh, name_en) values
  ('l1', 'fashion', '服飾鞋履', 'Fashion & Apparel'),
  ('l1', 'bags-accessories', '包袋配件', 'Bags & Accessories'),
  ('l1', 'jewelry', '飾品珠寶', 'Jewelry'),
  ('l1', 'beauty', '美妝保養', 'Beauty & Personal Care'),
  ('l1', 'home', '居家生活', 'Home & Living'),
  ('l1', 'food-drink', '食品飲料', 'Food & Beverage'),
  ('l1', 'crafts', '工藝文創', 'Crafts & Art'),
  ('l1', 'stationery', '文具設計', 'Stationery & Design'),
  ('l1', 'tech', '3C科技', 'Tech & Electronics'),
  ('l1', 'outdoor', '戶外露營', 'Outdoor & Camping'),
  ('l1', 'fitness', '運動健身', 'Sports & Fitness'),
  ('l1', 'kids', '母嬰童', 'Kids & Baby'),
  ('l1', 'pets', '寵物', 'Pets'),
  ('l2', 'tops-and-tshirts', '上衣・T恤', 'Tops & T-shirts'),
  ('l2', 'dresses', '洋裝', 'Dresses'),
  ('l2', 'skirts', '裙裝', 'Skirts'),
  ('l2', 'pants', '褲裝', 'Pants'),
  ('l2', 'outerwear', '外套', 'Outerwear'),
  ('l2', 'underwear-and-intimates', '貼身衣物', 'Underwear & Intimates'),
  ('l2', 'loungewear', '睡衣・居家服', 'Loungewear'),
  ('l2', 'swimwear', '泳裝', 'Swimwear'),
  ('l2', 'performance-apparel', '機能服飾', 'Performance Apparel'),
  ('l2', 'activewear', '運動服飾', 'Activewear'),
  ('l2', 'socks', '襪子', 'Socks'),
  ('l2', 'casual-shoes', '休閒鞋', 'Casual Shoes'),
  ('l2', 'leather-shoes', '皮鞋', 'Leather Shoes'),
  ('l2', 'heels', '高跟鞋', 'Heels'),
  ('l2', 'sandals-and-slippers', '涼鞋・拖鞋', 'Sandals & Slippers'),
  ('l2', 'boots', '靴子', 'Boots'),
  ('l2', 'backpacks', '後背包', 'Backpacks'),
  ('l2', 'tote-bags', '托特包', 'Tote Bags'),
  ('l2', 'crossbody-bags', '斜背包', 'Crossbody Bags'),
  ('l2', 'handbags', '手提包', 'Handbags'),
  ('l2', 'clutches', '手拿包', 'Clutches'),
  ('l2', 'clasp-frame-bags', '口金包', 'Clasp-Frame Bags'),
  ('l2', 'bucket-bags', '水桶包', 'Bucket Bags'),
  ('l2', 'belt-and-sling-bags', '腰包・胸包', 'Belt & Sling Bags'),
  ('l2', 'eco-and-shopping-bags', '環保袋・購物袋', 'Eco & Shopping Bags'),
  ('l2', 'wallets', '皮夾・錢包', 'Wallets'),
  ('l2', 'coin-purses', '零錢包', 'Coin Purses'),
  ('l2', 'card-holders', '卡夾・證件套', 'Card Holders'),
  ('l2', 'storage-pouches', '收納包', 'Storage Pouches'),
  ('l2', 'cosmetic-bags', '化妝包', 'Cosmetic Bags'),
  ('l2', 'laptop-bags', '筆電包', 'Laptop Bags'),
  ('l2', 'camera-bags', '相機包', 'Camera Bags'),
  ('l2', 'luggage-and-travel', '行李箱・旅行袋', 'Luggage & Travel'),
  ('l2', 'hats', '帽子', 'Hats'),
  ('l2', 'scarves-and-shawls', '圍巾・披肩', 'Scarves & Shawls'),
  ('l2', 'eyewear', '眼鏡・太陽眼鏡', 'Eyewear'),
  ('l2', 'watches', '手錶', 'Watches'),
  ('l2', 'keychains', '鑰匙圈', 'Keychains'),
  ('l2', 'charms', '吊飾', 'Charms'),
  ('l2', 'phone-bags', '手機袋', 'Phone Bags'),
  ('l2', 'phone-straps', '手機背帶', 'Phone Straps'),
  ('l2', 'umbrellas', '雨傘・陽傘', 'Umbrellas'),
  ('l2', 'gloves', '手套', 'Gloves & Mittens'),
  ('l2', 'earrings', '耳環', 'Earrings'),
  ('l2', 'necklaces', '項鍊', 'Necklaces'),
  ('l2', 'rings', '戒指', 'Rings'),
  ('l2', 'bracelets-and-bangles', '手鍊・手環', 'Bracelets & Bangles'),
  ('l2', 'wedding-and-couple-rings', '婚戒・對戒', 'Wedding & Couple Rings'),
  ('l2', 'brooches', '胸針', 'Brooches'),
  ('l2', 'hair-accessories', '髮飾', 'Hair Accessories'),
  ('l2', 'cufflinks-and-tie-clips', '袖扣・領帶夾', 'Cufflinks & Tie Clips'),
  ('l2', 'handmade-soap', '手工皂', 'Handmade Soap'),
  ('l2', 'skincare', '臉部保養', 'Skincare'),
  ('l2', 'face-masks', '面膜', 'Face Masks'),
  ('l2', 'body-care', '身體保養', 'Body Care'),
  ('l2', 'bath-and-shower', '洗沐清潔', 'Bath & Shower'),
  ('l2', 'hair-care', '髮品・頭皮護理', 'Hair Care'),
  ('l2', 'makeup', '彩妝', 'Makeup'),
  ('l2', 'sun-care', '防曬', 'Sun Care'),
  ('l2', 'fragrance', '香水', 'Fragrance'),
  ('l2', 'essential-oils-and-hydrosols', '精油・純露', 'Essential Oils & Hydrosols'),
  ('l2', 'oral-care', '口腔護理', 'Oral Care'),
  ('l2', 'protective-sprays', '防蚊・止汗噴霧', 'Protective Sprays'),
  ('l2', 'feminine-care', '生理用品', 'Feminine Care'),
  ('l2', 'beauty-tools', '美妝工具・儀器', 'Beauty Tools & Devices'),
  ('l2', 'bedding', '寢具', 'Bedding'),
  ('l2', 'mattresses', '床墊', 'Mattresses'),
  ('l2', 'furniture', '家具', 'Furniture'),
  ('l2', 'kids-furniture', '兒童家具', 'Kids'' Furniture'),
  ('l2', 'lighting', '燈飾', 'Lighting'),
  ('l2', 'clocks', '時鐘', 'Clocks'),
  ('l2', 'home-decor', '居家擺飾', 'Home Décor'),
  ('l2', 'towels', '毛巾', 'Towels'),
  ('l2', 'home-textiles', '居家織品', 'Home Textiles'),
  ('l2', 'rugs-and-mats', '地墊・地毯', 'Rugs & Mats'),
  ('l2', 'tableware', '餐具', 'Tableware'),
  ('l2', 'tea-and-coffee-ware', '茶具・咖啡器具', 'Tea & Coffee Ware'),
  ('l2', 'cookware', '鍋具', 'Cookware'),
  ('l2', 'tumblers-and-bottles', '隨行杯・保溫瓶', 'Tumblers & Bottles'),
  ('l2', 'reusable-utensils-and-straws', '環保餐具・吸管', 'Reusable Utensils & Straws'),
  ('l2', 'storage', '收納用品', 'Storage'),
  ('l2', 'cleaning', '清潔用品', 'Cleaning'),
  ('l2', 'home-appliances', '生活家電', 'Home Appliances'),
  ('l2', 'home-fragrance', '居家香氛', 'Home Fragrance'),
  ('l2', 'candles', '蠟燭', 'Candles'),
  ('l2', 'floral-arrangements', '花藝', 'Floral Arrangements'),
  ('l2', 'plants', '植栽', 'Plants'),
  ('l2', 'curtains', '窗簾', 'Curtains'),
  ('l2', 'bath-accessories', '衛浴用品', 'Bath Accessories'),
  ('l2', 'hand-tools', '手工具', 'Hand Tools'),
  ('l2', 'pest-control', '防蟲用品', 'Pest Control'),
  ('l2', 'figurines-and-plush', '公仔・玩偶', 'Figurines & Plush'),
  ('l2', 'tea', '茶葉', 'Tea'),
  ('l2', 'tea-bags', '茶包', 'Tea Bags'),
  ('l2', 'tea-drinks', '茶飲', 'Tea Drinks'),
  ('l2', 'coffee', '咖啡', 'Coffee'),
  ('l2', 'chocolate-and-cacao', '巧克力・可可', 'Chocolate & Cacao'),
  ('l2', 'honey', '蜂蜜', 'Honey'),
  ('l2', 'jams-and-spreads', '果醬・抹醬', 'Jams & Spreads'),
  ('l2', 'desserts-and-pastries', '甜點・糕點', 'Desserts & Pastries'),
  ('l2', 'cookies-and-rice-crackers', '餅乾・米餅', 'Cookies & Rice Crackers'),
  ('l2', 'snacks', '零食', 'Snacks'),
  ('l2', 'dried-fruits', '果乾', 'Dried Fruits'),
  ('l2', 'rice-and-grains', '米・雜糧', 'Rice & Grains'),
  ('l2', 'fresh-produce', '生鮮蔬果', 'Fresh Produce'),
  ('l2', 'dairy', '乳製品', 'Dairy'),
  ('l2', 'milk-powder', '奶粉', 'Milk Powder'),
  ('l2', 'alcohol', '酒類', 'Alcohol'),
  ('l2', 'beverages', '飲品', 'Beverages'),
  ('l2', 'seasonings-and-sauces', '調味料・醬料', 'Seasonings & Sauces'),
  ('l2', 'ready-meals', '料理包・加工食品', 'Ready Meals'),
  ('l2', 'supplements', '保健食品', 'Supplements'),
  ('l2', 'ceramics', '陶瓷・陶藝', 'Ceramics'),
  ('l2', 'woodcraft', '木藝・木作', 'Woodcraft'),
  ('l2', 'metalwork', '金工', 'Metalwork'),
  ('l2', 'bamboo-craft', '竹編・竹藝', 'Bamboo Craft'),
  ('l2', 'glass-art', '玻璃・琉璃', 'Glass Art'),
  ('l2', 'natural-dyeing', '藍染・植物染', 'Natural Dyeing'),
  ('l2', 'leather-craft', '皮革工藝', 'Leather Craft'),
  ('l2', 'embroidery', '刺繡', 'Embroidery'),
  ('l2', 'needle-felting', '羊毛氈', 'Needle Felting'),
  ('l2', 'weaving-and-crochet', '編織・鉤織', 'Weaving & Crochet'),
  ('l2', 'illustration-and-art', '插畫・畫作', 'Illustration & Art'),
  ('l2', 'dried-flowers-and-floral-design', '乾燥花・花藝設計', 'Dried Flowers & Floral Design'),
  ('l2', 'journals-and-notebooks', '手帳・筆記本', 'Journals & Notebooks'),
  ('l2', 'washi-tape', '紙膠帶', 'Washi Tape'),
  ('l2', 'stickers', '貼紙', 'Stickers'),
  ('l2', 'stamps-and-seals', '印章', 'Stamps & Seals'),
  ('l2', 'cards-and-postcards', '卡片・明信片', 'Cards & Postcards'),
  ('l2', 'pens-and-writing', '筆具', 'Pens & Writing'),
  ('l2', 'calendars', '月曆・日曆', 'Calendars'),
  ('l2', 'desk-mats', '桌墊', 'Desk Mats'),
  ('l2', 'paper-goods', '紙品', 'Paper Goods'),
  ('l2', 'desk-organization', '文具收納', 'Desk Organization'),
  ('l2', 'bookmarks', '書籤', 'Bookmarks'),
  ('l2', 'craft-kits-and-supplies', '手作材料・工具', 'Craft Kits & Supplies'),
  ('l2', 'phone-cases', '手機殼', 'Phone Cases'),
  ('l2', 'device-sleeves', '保護套・皮套', 'Device Sleeves'),
  ('l2', 'chargers-and-cables', '充電器・充電線', 'Chargers & Cables'),
  ('l2', 'power-banks', '行動電源', 'Power Banks'),
  ('l2', 'wireless-charging', '無線充電', 'Wireless Charging'),
  ('l2', 'earphones-and-headphones', '耳機', 'Earphones & Headphones'),
  ('l2', 'speakers', '藍牙喇叭', 'Speakers'),
  ('l2', 'stands-and-mounts', '支架', 'Stands & Mounts'),
  ('l2', 'storage-devices', '儲存裝置', 'Storage Devices'),
  ('l2', 'security-cameras', '攝影機', 'Security Cameras'),
  ('l2', 'smart-doorbells', '智慧門鈴', 'Smart Doorbells'),
  ('l2', 'hiking-and-camping-gear', '登山・露營用品', 'Hiking & Camping Gear'),
  ('l2', 'picnic-supplies', '野餐用品', 'Picnic Supplies'),
  ('l2', 'wetsuits-and-water-sports', '防寒衣・水上運動', 'Wetsuits & Water Sports'),
  ('l2', 'cycling-and-riding', '自行車・騎士用品', 'Cycling & Riding'),
  ('l2', 'helmets', '安全帽', 'Helmets'),
  ('l2', 'outdoor-accessories', '戶外配件', 'Outdoor Accessories'),
  ('l2', 'yoga-gear', '瑜珈用品', 'Yoga Gear'),
  ('l2', 'fitness-equipment', '健身器材', 'Fitness Equipment'),
  ('l2', 'massage-and-recovery', '按摩・放鬆', 'Massage & Recovery'),
  ('l2', 'protective-gear', '護具', 'Protective Gear'),
  ('l2', 'care-and-mobility-aids', '照護輔具', 'Care & Mobility Aids'),
  ('l2', 'kids-clothing', '童裝', 'Kids'' Clothing'),
  ('l2', 'family-matching', '親子裝', 'Family Matching'),
  ('l2', 'baby-clothing', '嬰幼兒服飾', 'Baby Clothing'),
  ('l2', 'baby-bedding', '嬰幼兒寢具', 'Baby Bedding'),
  ('l2', 'bibs-and-muslin', '圍兜・紗布巾', 'Bibs & Muslin'),
  ('l2', 'kids-tableware', '兒童餐具', 'Kids'' Tableware'),
  ('l2', 'toys', '玩具', 'Toys'),
  ('l2', 'learning-aids', '教具', 'Learning Aids'),
  ('l2', 'play-mats-and-fences', '遊戲地墊・圍欄', 'Play Mats & Fences'),
  ('l2', 'parenting-essentials', '育兒用品', 'Parenting Essentials'),
  ('l2', 'pet-food', '寵物食品', 'Pet Food'),
  ('l2', 'pet-treats', '寵物零食', 'Pet Treats'),
  ('l2', 'pet-supplements', '寵物保健', 'Pet Supplements'),
  ('l2', 'pet-apparel', '寵物服飾・配件', 'Pet Apparel'),
  ('l2', 'pet-beds-and-scratchers', '貓抓板・寵物床窩', 'Pet Beds & Scratchers'),
  ('l2', 'pet-grooming', '寵物清潔・美容', 'Pet Grooming'),
  ('l2', 'pet-supplies', '寵物生活用品', 'Pet Supplies'),
  ('material', '陶瓷', '陶瓷', 'Ceramic'),
  ('material', '木', '木', 'Wood'),
  ('material', '織品', '織品', 'Textile'),
  ('material', '玻璃', '玻璃', 'Glass'),
  ('material', '金屬', '金屬', 'Metal'),
  ('material', '竹', '竹', 'Bamboo'),
  ('material', '羊毛', '羊毛', 'Wool'),
  ('material', '皮革', '皮革', 'Leather'),
  ('material', '紙', '紙', 'Paper'),
  ('material', '石', '石', 'Stone'),
  ('material', '藤', '藤', 'Rattan'),
  ('material', '漆', '漆', 'Lacquer');

do $seed$
declare
  v_expected constant jsonb := '{"l1":13,"l2":175,"material":12}'::jsonb;
  v_actual jsonb;
begin
  select coalesce(jsonb_object_agg(counted.axis, counted.total), '{}'::jsonb)
    into v_actual
    from (
      select axis, count(*) as total
      from public.taxonomy_terms
      group by axis
    ) as counted;

  if v_actual is distinct from v_expected then
    raise exception
      'DEV-1510 taxonomy_terms axis counts are %, expected %',
      v_actual, v_expected
      using errcode = 'P0001';
  end if;
end
$seed$;
-- <<< end generated block

-- Closing contract: every axis is populated and no display name is a slug
-- echo. A material row is the one legitimate case where slug = name_zh, so it
-- is excluded rather than the check being dropped.
do $migration$
declare
  v_offenders text;
begin
  select string_agg(t.axis || ':' || t.slug, ', ' order by t.axis || ':' || t.slug)
  into v_offenders
  from public.taxonomy_terms as t
  where t.axis <> 'material'
    and t.name_zh = t.slug;

  if v_offenders is not null then
    raise exception
      'DEV-1510 taxonomy_terms row(s) carry a slug as their zh-TW label: %',
      v_offenders
      using errcode = 'P0001';
  end if;
end
$migration$;

commit;
