import type { RunLog } from '../schema'

export const enrichRunFixture = {
  schemaVersion: '1.0',
  run: {
    id: '7f482459-83ce-40fb-8d33-c0f0c8dfbdf8',
    workflow: 'enrich',
    trigger: 'cron',
    actor: 'curation-worker',
    status: 'completed',
    startedAt: '2026-07-15T02:00:00.000Z',
    completedAt: '2026-07-15T02:00:18.450Z',
  },
  summary: {
    durationMs: 18_450,
    phaseCount: 4,
    callCount: 3,
    queryCount: 2,
    tokens: { input: 5_940, output: 1_180, total: 7_120 },
    outcomes: { succeeded: 2, failed: 1 },
    extraChips: [{ label: 'Targets', value: '3' }],
  },
  phases: [
    {
      index: 1,
      name: 'discover',
      kind: 'search',
      status: 'succeeded',
      summary: 'Search results collected for 3 targets',
      durationMs: 2_800,
      barWeight: 2_800,
      events: [
        {
          timestamp: '2026-07-15T02:00:00.210Z',
          actor: 'HTTP',
          name: 'serper.search',
          summary: 'Taiwan brand profile search',
          status: 'ok',
          latencyMs: 710,
          labels: { target: 'acme-taiwan' },
        },
        {
          timestamp: '2026-07-15T02:00:01.020Z',
          actor: 'HTTP',
          name: 'serper.search',
          summary: 'Official site search',
          status: 'ok',
          latencyMs: 640,
          labels: { target: 'island-tools' },
        },
      ],
    },
    {
      index: 2,
      name: 'detect',
      kind: 'llm',
      status: 'failed',
      summary: 'Brand detection completed with one retry failure',
      durationMs: 9_450,
      barWeight: 9_450,
      tokens: { input: 5_940, output: 1_180, total: 7_120 },
      events: [
        {
          timestamp: '2026-07-15T02:00:03.100Z',
          actor: 'LLM',
          name: 'chat.completion',
          summary: 'Classified brand and product type',
          status: 'ok',
          model: 'deepseek-v4-flash',
          tokens: { input: 2_100, output: 410, total: 2_510 },
          latencyMs: 2_430,
          labels: { target: 'acme-taiwan' },
        },
        {
          timestamp: '2026-07-15T02:00:06.000Z',
          actor: 'LLM',
          name: 'chat.completion',
          summary: 'Image classification request rejected',
          status: 'error',
          model: 'gpt-4o-mini',
          tokens: { input: 3_840, output: 770, total: 4_610 },
          latencyMs: 3_820,
          labels: { target: 'island-tools' },
          error: 'Provider returned a rate-limit response',
        },
      ],
    },
    {
      index: 3,
      name: 'scrape',
      kind: 'scrape',
      status: 'succeeded',
      summary: 'Official pages extracted',
      durationMs: 4_600,
      barWeight: 4_600,
      events: [
        {
          timestamp: '2026-07-15T02:00:10.100Z',
          actor: 'SCRAPE',
          name: 'site.extract',
          summary: 'Extracted product and about pages',
          status: 'ok',
          latencyMs: 1_920,
          labels: { target: 'acme-taiwan' },
        },
      ],
    },
    {
      index: 4,
      name: 'persist',
      kind: 'persist',
      status: 'succeeded',
      summary: 'Enrichment patches persisted',
      durationMs: 1_600,
      barWeight: 1_600,
      events: [
        {
          timestamp: '2026-07-15T02:00:16.400Z',
          actor: 'DB',
          name: 'brand.update',
          summary: 'Updated enrichment fields',
          status: 'ok',
          latencyMs: 320,
          labels: { target: 'acme-taiwan' },
        },
      ],
    },
  ],
  provenance: {
    producer: { name: 'formoria/runlog-export', version: '0.1.0' },
    components: [
      { name: 'formoria-enrich', version: '7bb54a2' },
      { name: 'runlog-renderer', version: '1.0' },
    ],
    sourceRef: '7f482459-83ce-40fb-8d33-c0f0c8dfbdf8',
    generatedAt: '2026-07-15T02:00:19.000Z',
  },
  gaps: ['One failed provider response did not include a retry-after value.'],
} satisfies RunLog
